### ISSUE TITLE
Fix phone look and text (reduce size little bit)

### ISSUE THREAD

**Issue by codervivek5** [codervivek5/VigyBag#10]

**Comment by afeefuddin** [comment]
Hey @codervivek5 . I want to work on this issue. Please assign me this under GSSOC'23

**Comment by s0oraj** [comment]
Hi @codervivek5, iam a GSSOC23 contributer and I would like to resolve this issue

Can you assign me this issue? Or any other issues you might have?
Heres My Resume which you might find useful: [Resume](https://github.com/codervivek5/VigyBag/files/11521351/Resume.pdf)
Ive more than 1 year of experience in android development(check profile for more details)

**Comment by SamridhiNancy** [comment]
"Hi there! I'm excited to contribute to this project'GSSOC;'23 I've taken a look at the codebase and I believe I can make some valuable improvements. I'll start working on it right away. If you have any specific requirements or suggestions, please let me know. Looking forward to collaborating with you all on this!

**Comment by afeefuddin** [comment]
Hey @codervivek5, thanks for assigining this issue, already working on it
