### ISSUE TITLE
Create Product Detail page.

### ISSUE THREAD

**Issue by codervivek5** [codervivek5/VigyBag#100]
kindly refer this design.
https://www.figma.com/file/hXcM6chTK70O6rAqCTFxuc/VigyBag?type=design&node-id=0%3A1&t=XsHlxKAHMDFgsOwr-1

**Comment by bishalde** [comment]
I would like to Contribute to the Product detail page...! and it  will be easy for me to follow your FIGMA desing.

so kindly assign me this under #GSSOC'2023.
![image](https://github.com/codervivek5/VigyBag/assets/67416966/66c0a816-0e70-4e45-8c5c-7aafa9a51bf4)

**Comment by ManasaKaza** [comment]
I would like to work on this issue under GSSoC

**Comment by codervivek5** [comment]
@bishalde Any update about it ?

**Comment by bishalde** [comment]
yes almost done..!
