### ISSUE TITLE
Toggle Button is not working in the Team Page

### ISSUE THREAD

**Issue by suraj-9849** [codervivek5/VigyBag#1001]
![image](https://github.com/codervivek5/VigyBag/assets/146669517/7191764c-4eae-4f2d-891c-39bd25ed02b2)
I will improve the design also. But when I am clicking on the toggle button I saw there is no change at all in the page. so as the @GSSOC'24 Contributor I would like to work on this issue so can u please assign this issue to me @codervivek5

**Comment by Kadambini30** [comment]
@suraj-9849 Can you please assign this issue to me?

**Comment by suraj-9849** [comment]
> @suraj-9849 Can you please assign this issue to me?

I am a contributor not the mentor and this issue is completed @Kadambini30

**Comment by codervivek5** [comment]
@suraj-9849 if this issue it solve then kindly close it
