### ISSUE TITLE
Same title and  images for all cards in products section.

### ISSUE THREAD

**Issue by shnwz-solves** [codervivek5/VigyBag#1006]
The images in product section ( eg: Headphones, t-shirts, Mobiles) have same title and  image for a section.
For better UX, different products should be listed there. I can fix this issue by adding new images and adding title according to the product.

![image](https://github.com/codervivek5/VigyBag/assets/126380641/bbf787a3-f835-43f4-b700-b939c9918f4b)

Hey PA, I want to contribute, please assign this issue to me. Thankyou!

**Comment by codervivek5** [comment]
we will fix it with backend
