### ISSUE TITLE
Login form hover effect's color is not according to the look of website.

### ISSUE THREAD

**Issue by shnwz-solves** [codervivek5/VigyBag#1007]
The login form's buttons (verify and send otp)'s hover effect is not according to the look and feel of the website.
![Screenshot 2024-05-11 214333](https://github.com/codervivek5/VigyBag/assets/126380641/403727b0-04a0-4a09-9059-43c23246e3f6)

Hey PA, I want to contribute, please assign this issue to me. Thankyou!

**Comment by ankiiitagupta** [comment]
@codervivek5 Can you assign this issue to me under GSSOC'24 please? I would love to use my skills to provide you with desired and enhanced result.

**Comment by shnwz-solves** [comment]
Hey PA @codervivek5 What happened? Why you unassigned me the task?
I have raised the issue also I have mentioned that I want to contribute.

**Comment by codervivek5** [comment]
@shnwz-solves I have already assign an issue before this so acc. to the gssoc policy I need to assign it to another candidate but dont worry you can find another issue and I will assign to you.


I hope you got the point

**Comment by shnwz-solves** [comment]
> @shnwz-solves I have already assign an issue before this so acc. to the gssoc policy I need to assign it to another candidate but dont worry you can find another issue and I will assign to you.
> 
> 
> I hope you got the point 

Okay understood✅, but I have a doubt: Can't we get multiple tasks assigned at once?

**Comment by Shamyuktha06** [comment]
Can u please assign to me this I will work on it and make sure to be a better option

**Comment by somrima-09** [comment]
Hi. Under GSSOC'24, I would like to work on this issue.
Please Assign me this task.

**Comment by ritikaguptaa** [comment]
@codervivek5 hi under gssoc 24. I can resolve this issue. Please give me a chance to assign this project to me.

**Comment by Kadambini30** [comment]
@codervivek5 I have experience with the some issue in one of my projects. I kindly request you to assign me the issue
