### ISSUE TITLE
Same description of products and content being out of alert box

### ISSUE THREAD

**Issue by kritzxd8** [codervivek5/VigyBag#1009]
![Screenshot 2024-05-11 041500](https://github.com/codervivek5/VigyBag/assets/162461631/6e64ca22-ee8c-46b8-94a8-b7e8eca10638)

The content is not aligned properly . Also saw the same description in all products. Kindly assign me this issue i would like to work on it . Thank you.

**Comment by kritzxd8** [comment]
Checklist

[ x] I have checked the existing issues *
[x ] I have read the Contributing Guidelines *
[ x] I have starred the repository *
[x ] Working under Gssoc24*

**Comment by toodiv** [comment]
I can contribute to the issue with a clean and efficient code. Kindly accept my issue under GSSOC'24.

**Comment by kritzxd8** [comment]
hello @codervivek5 could u give me the "level" label
