### ISSUE TITLE
Frequently Ask Question UI fixing

### ISSUE THREAD

**Issue by Che140401** [codervivek5/VigyBag#1012]
Hey hello subscribed to your channel !!!!!

- [ ] Here is the issue we are getting jerk when we open the text
 

https://github.com/codervivek5/VigyBag/assets/109230049/6ac3e595-eb54-4c6e-bf2b-d033117c1055

- [ ] Here we can solve this issue
 
 

https://github.com/codervivek5/VigyBag/assets/109230049/31bb7cd6-6832-4729-93a7-c2d10fa0f3c5

**Comment by codervivek5** [comment]
Its look like fine so no need to add another type of UI
