### ISSUE TITLE
Enhancement: Search Input and Heading Text Alignment Issue on Home Page

### ISSUE THREAD

**Issue by mukulpythondev** [codervivek5/VigyBag#1014]
### Description
On the home page of the application, there are two issues observed:
1. The search input is not displaying properly.
2. The heading text is not properly aligned.

### Expected Behavior
1. The search input should be visible and properly aligned on the home page.
2. The heading text should be correctly aligned with the rest of the content on the page.

### Steps to Reproduce
1. Navigate to the home page of the application.
2. Observe the search input and heading text alignment issues.

### Additional Context
These issues affect the visual appeal and usability of the home page. It's essential to address them to ensure a consistent and pleasant user experience across the application.

### Screenshot
![Home Page](https://github.com/codervivek5/VigyBag/assets/134795697/72332f9d-fc08-4182-a892-8e8b5efc7707)

**Comment by mukulpythondev** [comment]
I wanna interested fo work on this issue.

**Comment by MishraTanishq619** [comment]
I am starting to work on this issue.
Kindly assign this to me for GSSOC 2024.

**Comment by MishraTanishq619** [comment]
GSSoc label please..
