### ISSUE TITLE
Correction in the Cart Section

### ISSUE THREAD

**Issue by anagha-chaudhari** [codervivek5/VigyBag#1018]
After adding the product to the cart through the "see more" section, the cart is displaying incorrect price details and total, and it's not showing any product details. I would love to work on resolving this issue. 

Please assign this task to me for GSSOC'24.

![vigybag](https://github.com/codervivek5/VigyBag/assets/143149376/fe93d4d4-a7d2-41d4-baa5-a74e59e49bab)

**Comment by toodiv** [comment]
I can contribute to the issue with a clean and efficient code. Kindly accept my issue under GSSOC'24.

**Comment by khushi-igupta** [comment]
Hello I am a GsSOC'24 contributor and I would like to work on this issue. Can you please assign it to me?
