### ISSUE TITLE
Enhancement of Contact forms and correction of improper alignment of qucik links section and also wanted to add a preloader if possible 

### ISSUE THREAD

**Issue by pand-coder** [codervivek5/VigyBag#1024]
Hello @codervivek5 

I would like to enhance the contact forms 
###Screenshot
![Screenshot 2024-05-12 191253](https://github.com/codervivek5/VigyBag/assets/82692757/88172597-0dfd-44f7-ad2d-021df71cf6e8)
There is imprpoer alignment of the Quick links section and lack of responsiveness according to screen width and height 
![image](https://github.com/codervivek5/VigyBag/assets/82692757/45d77eb6-4a0c-43ce-ab8b-3971ba8c3942)
- [x] I agree to follow this project's Code of Conduct
- [x] I'm a GSSOC'24 contributor
- [x] I want to work on this issue
Please assign this issue to me...
would like to work upon this

**Comment by somrima-09** [comment]
Hi. Under GSSOC'24, I would like to work on this issue.
Please Assign me this task.

**Comment by codervivek5** [comment]
@pand-coder somone is alrady working  on this issue so I can't assign it to  you now
