### ISSUE TITLE
Regarding website animation

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [codervivek5/VigyBag#1025]
Regarding website animation
i want to add some cool animations in your website which look more interactive
tech stack to be used
-aos.js
-ityped.js

**Comment by FatemaBaig** [comment]
Hii,
I would like to work on this part of project please assign it to me under GSSOC-24.

**Comment by somrima-09** [comment]
Hi. Under GSSOC'24, I would like to work on this issue.
Please Assign me this task.

**Comment by toodiv** [comment]
I can contribute to the issue with a clean and efficient code. Kindly accept my issue under GSSOC'24.

**Comment by RamakrushnaBiswal** [comment]
Hi @codervivek5 I can add animation now or let the landing page fully complete?

**Comment by codervivek5** [comment]
bro also have many bugs in the landing page

**Comment by toodiv** [comment]
@codervivek5 brother please assign me the issue for fixing

**Comment by RamakrushnaBiswal** [comment]
issue solved PR #1123
