### ISSUE TITLE
[FEATURE] Issue in search bar

### ISSUE THREAD

**Issue by ujj654** [codervivek5/VigyBag#1026]
"When we give the more input  into the search bar, icon of the search bar overlap the text " which will decrease the user experience. So we have to solve this issue.

 screenshot:-
![image](https://github.com/codervivek5/VigyBag/assets/81877649/cd5dc606-8a98-43fc-aacd-e6f3a76f5642)

I would like to work on this issue so please assign this issue to me.

**Comment by ujj654** [comment]
Please assign this issue to me.

**Comment by zoyafatima382** [comment]
There is some issue in search bar of overlapping the text on search icon. I want to work on thus issue can u please assign me this issue.

**Comment by Azhar-0401** [comment]
Helo, I am currently a GSSOC contributor, kindly assign the issue to me

**Comment by AtharvaSonar-21** [comment]
I would like to work on this issue .sir, @codervivek5, please assign it to me.

**Comment by codervivek5** [comment]
whose solve it first I will merge their PR with level 3

**Comment by ujj654** [comment]
@codervivek5, I solved the problem of the Search Bar Please look the changes and merge the PR.

**Comment by toodiv** [comment]
I can contribute to the issue with a clean and efficient code. Kindly accept my issue under GSSOC'24.
