### ISSUE TITLE
[FEATURE] Add a animated Onboarding tour of our website. 

### ISSUE THREAD

**Issue by Rahulsingh1939** [codervivek5/VigyBag#1028]
The animated onboarding tour feature provides new users with a guided introduction to our website's interface,  
Engaging animations will be used to draw attention to important elements of the interface.

 By using React Onboarding Libraries, we can implement a quick go through of our website .
![react-joyride-example](https://github.com/codervivek5/VigyBag/assets/56185613/02884a53-d533-4eee-bb96-1b183e23133e)

**Comment by Rahulsingh1939** [comment]
I would like to work on this feature @codervivek5, please assign it to me.

**Comment by khushi-igupta** [comment]
Hello @codervivek5 I am a GsSOC'24 contributor and I would like to work on this issue. Can you please assign it to me?
