### ISSUE TITLE
team section 

### ISSUE THREAD

**Issue by jayanththalla** [codervivek5/VigyBag#1029]
footer of the team section and social link
please @codervivek5 assign me

**Comment by somrima-09** [comment]
Hi. Under GSSOC'24, I would like to work on this issue.
Please Assign me this task.

**Comment by jayanththalla** [comment]
Yes definitely

**Comment by codervivek5** [comment]
kindly explain what change you want to make

**Comment by varshithar12** [comment]
I would like to work on this issue.
Please Assign me this task.

**Comment by jayanththalla** [comment]
> kindly explain what change you want to make

I want change the footer with media and all make it flex and giving alignment



![image](https://github.com/codervivek5/VigyBag/assets/121346142/f7331195-c678-4459-9b00-f1e661545181)
