### ISSUE TITLE
Enhancing the Password strength

### ISSUE THREAD

**Issue by Yuvasri-b** [codervivek5/VigyBag#1030]
Description : 

It suggest whether a password is strong /weak/ medium based on runtime of user input with different emojis use too describing strength to weakness during sign up process.

Screenshots
![Screenshot 2024-05-13 182849](https://github.com/codervivek5/VigyBag/assets/155957336/c9930dce-a729-457f-9d23-bd9d2e57242d)

I agree to follow this project's code of conduct.

Please assign this to me under GSSOC'24

**Comment by Yuvasri-b** [comment]
Please assign this issue to me @codervivek5

**Comment by Yuvasri-b** [comment]
Please assign this issue to me @codervivek5

**Comment by AtharvaSonar-21** [comment]
I would like to work on this feature @codervivek5, please assign it to me.

**Comment by ghost** [comment]
Would like to work on this issue can you assign me this issue?
 I'm working Under GSSOC'24
