### ISSUE TITLE
Adding proper texts in place of lorem to make it look authentic.

### ISSUE THREAD

**Issue by souvik-maity** [codervivek5/VigyBag#1031]
![IMG_20240513_184959.jpg](https://github.com/codervivek5/VigyBag/assets/145227417/0d4a36e8-0aa4-43db-89c0-a190ea1687a9)

**Comment by souvik-maity** [comment]
Kindly assign this to me.

**Comment by vaishnavip27** [comment]
Hey @codervivek5 I can work on this issue as I have good experience in coding websites.  Please assign me this issue. Looking forward for your approval.
