### ISSUE TITLE
mobile responsiveness missing

### ISSUE THREAD

**Issue by sahithinandikula** [codervivek5/VigyBag#1033]
issues existed on the web page:
1) lack of mobile responsiveness
2) fonts are of  basic type
3) no proper alignment of components in the hero section
4)  
![WhatsApp Image 2024-05-13 at 21 01 00_215656a5](https://github.com/codervivek5/VigyBag/assets/138794574/ca67b020-1c48-4e87-9649-909ab44cc063)
this part of the UI is not proper it needs to be fixed  

I can solve this and make the website look better.

**Comment by sahithinandikula** [comment]
@codervivek5 I am interested in working on this. please   label it and allow me to work on this

**Comment by codervivek5** [comment]
someone is already working on it
