### ISSUE TITLE
want to fix the space between different section.

### ISSUE THREAD

**Issue by PrachiChauhan23** [codervivek5/VigyBag#104]
want to change margin between different sections. that will make the website look good and spacious.

**Comment by PrachiChauhan23** [comment]
please assign me this issue @codervivek5 under GSSOC'23.

**Comment by codervivek5** [comment]
kindly add issue number at PR time

**Comment by PrachiChauhan23** [comment]
ok sir. Sir what's the deadline for this. @codervivek5
