### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by SDprogramer** [codervivek5/VigyBag#1040]
Real time GitHub URL of website not working showing privacy errors

So I want to fix this issue

![Screenshot 2024-05-14 171134](https://github.com/codervivek5/VigyBag/assets/155221332/3be5ffdd-41f2-4050-ade3-2a15542c0e75)

**Comment by codervivek5** [comment]
someone already working on it but if you can then start woking and after resolve just tell me

**Comment by SDprogramer** [comment]
Okay i will try to do that

**Comment by codervivek5** [comment]
just try and give me  proper update  plz

**Comment by toodiv** [comment]
I can contribute to the issue with a clean and efficient code. Kindly accept my issue under GSSOC'24.
