### ISSUE TITLE
NAvbar overlapping homepage content and Category icons alignement.

### ISSUE THREAD

**Issue by sharmi4590** [codervivek5/VigyBag#1048]
hello @codervivek5 
While opening in the phone the navbar is overlapping the content in the home page.
![Screenshot (391)](https://github.com/codervivek5/VigyBag/assets/102676949/d3c91240-f31a-4586-af6c-e7a6a76c853a)
As you can see above it is cutting the "DONT LEAVE" Text . 
I will seperate the home page and navbar to remove the collision.
Also the category icons alignement is not good .
![Screenshot (393)](https://github.com/codervivek5/VigyBag/assets/102676949/45b8868d-4ccc-4937-846b-1c5d48c5f959)
I will make it such that it will resize according to the device dimensions i.e.larger icons for bigger dimensions and smaller for smaller dimensions such that it will look with a good alignement.
I am a GSSoC'24 contributor.

**Comment by codervivek5** [comment]
@sharmi4590 someone is working on it wait for 1 day more then again tell me I will assign it to you

**Comment by Tanisha-b3** [comment]
can you assign me this issue

**Comment by sharmi4590** [comment]
Okay @codervivek5
