### ISSUE TITLE
correction in team navbar  

### ISSUE THREAD

**Issue by Tanisha-b3** [codervivek5/VigyBag#1051]
When we open the team tab the navbar is disappearing when the window is in dark mode I want to work on this issue can you assign me this

**Comment by toodiv** [comment]
I can contribute to the issue with a clean and efficient code. Kindly accept my issue under GSSOC'24.

**Comment by SanaAzeem512** [comment]
@codervivek5 Hello
please assign this issue to me under GSSOC24

**Comment by momin-mubash** [comment]
> When we open the team tab the navbar is disappearing when the window is in dark mode I want to work on this issue can you assign me this

Hi @Tanisha-b3 , I noticed there hasn't been any update on this issue for a while. Are you still working on it? I'd be happy to help or take it over if you're busy.
