### ISSUE TITLE
disappearance of Dark mode/light mode option 

### ISSUE THREAD

**Issue by K-Tikaraya** [codervivek5/VigyBag#1054]
Hello @codervivek5  
When we open login page or contact us page dark mode option disappeared I want to work on this issue please level it and assign it to me.

![Screenshot (215)](https://github.com/codervivek5/VigyBag/assets/165303736/14ddaac0-a5f0-400c-8af6-6fc4fa6f825e)

![Screenshot (214)](https://github.com/codervivek5/VigyBag/assets/165303736/28383edc-21a9-4fae-a8cd-d4737b882f04)
in login page when we click on verify or sign in with Google then there is collision between lines.
![Screenshot (213)](https://github.com/codervivek5/VigyBag/assets/165303736/93bf82ff-2abe-42d8-89a8-b8c8fa190645)

**Comment by Nirvanjha2004** [comment]
Heyy...Can U please assign me this issue...i would love to work on this issue.....as i have done this earlier also ....Thanks

**Comment by SanaAzeem512** [comment]
@codervivek5 Hello
please assign this issue to me under GSSOC24
