### ISSUE TITLE
Adding  Responsiveness in About Us page

### ISSUE THREAD

**Issue by K-Tikaraya** [codervivek5/VigyBag#1055]
Hello @codervivek5 
in About Us page Read More button is not working and footer part and fonts and colour contrast is not too good I can make it more attractive and responsive so please label this issue and assign it to me under gssoc@2024.
![Screenshot (217)](https://github.com/codervivek5/VigyBag/assets/165303736/3af46f18-ca7d-47ac-bf88-5b8c1028565b)
![Screenshot (216)](https://github.com/codervivek5/VigyBag/assets/165303736/e896d13e-afb4-4af6-90f0-0c3c6f2b78a4)

**Comment by Nirvanjha2004** [comment]
Heyy...Can U please assign me this issue...i would love to work on this issue.....as i have done this earlier also ....Thanks

**Comment by somrima-09** [comment]
Please assign me this issue
I can solve it with in 2 hours of assignment

**Comment by ArjitaSahu123** [comment]
hey @codervivek5   i am working on the mern stack, i can make changes on this to make it more responsive and attractive.
Please assign this task to me to level up my skills.

**Comment by toodiv** [comment]
I can contribute to the issue with a clean and efficient code. Kindly accept my issue under GSSOC'24.

**Comment by SanaAzeem512** [comment]
@codervivek5 Hello
please assign this issue to me under GSSOC24
