### ISSUE TITLE
 Update Footer Alignment in About Us Page

### ISSUE THREAD

**Issue by SaiTejaswaniBikkasani** [codervivek5/VigyBag#1058]
Hey @codervivek5 . The current footer alignment is not consistent and needs to be adjusted for better visual appeal and responsiveness.

Before making the changes:

![Screenshot 2024-05-15 205225](https://github.com/codervivek5/VigyBag/assets/159511364/6a4d1fcf-2d0b-445c-98db-e268ffc26e4b)

After making the changes:

![Screenshot 2024-05-15 205006](https://github.com/codervivek5/VigyBag/assets/159511364/5c57108d-2066-4af9-919e-e6b926c39ba6)

**Please add the gssoc labels and I would like to work on it under GSSOC'24. Thank you!!**

**Comment by abhishekdumaniya** [comment]
I would like to resolve this issue @codervivek5  can you please assign this issue to me under Gssoc24?
