### ISSUE TITLE
Update navbar and footer in team section

### ISSUE THREAD

**Issue by PuR-vI** [codervivek5/VigyBag#1059]
In Team section the navbar goes invisible in dark mode id like to fix that. Additionally the footer needs to be aligned properly. I can do it. please assign it to me under GSSOC24. Thankyou! 
Before:
![image](https://github.com/codervivek5/VigyBag/assets/97090750/ecf576ad-62ab-4075-88ea-3fb9058cbe2c)

After:
![image](https://github.com/codervivek5/VigyBag/assets/97090750/ad3b2f1d-2e79-44da-824b-41e69d1cfb11)

**Comment by abhishekdumaniya** [comment]
I would like to resolve this issue @codervivek5 can you please assign this issue to me under Gssoc24?

**Comment by jayanththalla** [comment]
I would like to resolve this issue . can you please assign this issue to me under Gssoc24?

please assign me @codervivek5

**Comment by SanaAzeem512** [comment]
@codervivek5 Hello
please assign this issue to me under GSSOC24
