### ISSUE TITLE
[Feature] : Create an Help Page  #GSSoc2023

### ISSUE THREAD

**Issue by bishalde** [codervivek5/VigyBag#106]
- I can desing an HELP Page similar to your Figma design.
- Basically this will have a form that will allow user to report their problem
- it will also include FAQ for most common problems.

![image](https://github.com/codervivek5/VigyBag/assets/67416966/e6e26963-38aa-4ec5-8c86-43bdf121a202)

**Comment by Chavisn** [comment]
I would like to work on this project.
kindly assign this issue to me.

**Comment by codervivek5** [comment]
try to add the FAQ section below to help page

**Comment by bishalde** [comment]
Okay i will complete this task on time.!

**Comment by sagnik-p** [comment]
This issue has been inactive for a long time
I would like to work on this issue
Please assign

**Comment by Nishitbaria** [comment]
@codervivek5 ,please assign me this issue,i will create pull request in a day
