### ISSUE TITLE
Redesign About page

### ISSUE THREAD

**Issue by dhruv389** [codervivek5/VigyBag#1061]
**Description:**
----
I want to change About Page design along with Text style , background image  and  many other things in this page

Hello @codervivek5 ,
Please assign me this issue, i want to work on it.

![image](https://github.com/codervivek5/VigyBag/assets/117587892/bd89b225-5af3-4cde-85f2-10de5f66bc34)

**Comment by Rish-tech1** [comment]
pls assign me this project
