### ISSUE TITLE
Change full Home page design

### ISSUE THREAD

**Issue by dhruv389** [codervivek5/VigyBag#1063]
Description : 
I want to change Home page design and responsiveness . and make it eye catching and attractive.

Hello @codervivek5 ,
Please assign me this issue , i want to work on it.
![image](https://github.com/codervivek5/VigyBag/assets/117587892/f2dd8597-d498-458a-9dd4-6af07a9512a2)

**Comment by codervivek5** [comment]
can you share any design

**Comment by dhruv389** [comment]
@codervivek5 ,
I have not Specific Design , But i want to change Vector Png ,some font size and color and responsiveness.

**Comment by dhruv389** [comment]
If you give me this issue  , then i  will send my progress with Screenshots.

**Comment by codervivek5** [comment]
Redesigned it accordingly your creativity... Remember it that this will be a evo friendly product selling website who will sell handmade eco-friendly product so use color similar to eco friendly theme

**Comment by NAhmad231** [comment]
@codervivek5 hey please sign this issue to me , i want use some pastel colors to make it more attractive and to match with your website  , once done i'll share it with you

**Comment by dhruv389** [comment]
Hello @codervivek5 

**I have made this design for home page** . Is it okay???

![image](https://github.com/codervivek5/VigyBag/assets/117587892/115062c3-cc05-47b6-8974-4a6fa8ddb51c)

**Comment by 143divya** [comment]
Please assign this task to me. I want to work on this

**Comment by dhruv389** [comment]
Hello @codervivek5 , 
please checkout new pull request  i have mad changes for home section  - https://github.com/codervivek5/VigyBag/pull/1105#issue-2304760733.

**Comment by dhruv389** [comment]
Hello @codervivek5 ,

please checkout new pull request i have mad changes for home section - https://github.com/codervivek5/VigyBag/pull/1105#issuecomment-2123893076
