### ISSUE TITLE
Create a logo for VigyBag (Eco friendly) - Read First comment 

### ISSUE THREAD

**Issue by codervivek5** [codervivek5/VigyBag#1067]
**This issue is open to all**
_I will accept the PR who design a perfect logo_

- The logo should look like selling an eco-friendly product 
- contain natural color

**Comment by ira-mane** [comment]
hello @codervivek5 can you please assign me this issue ? I would look to work on the logo.

**Comment by codervivek5** [comment]
- the logo should be simple not fancy
- the logo contain the feeling of selling handmade eco friendy products.
- after the export logo should be in png and pdf
- logo use natural color pallets
![image](https://github.com/codervivek5/VigyBag/assets/62784060/b8fa97dd-5940-4738-b400-89daeaf9d47e)
![image](https://github.com/codervivek5/VigyBag/assets/62784060/8222143e-7585-4f55-8a20-b5e9fc605f36)
refer these images

**Comment by codervivek5** [comment]
Any update ?|

**Comment by ira-mane** [comment]
hello @codervivek5 I am working on it. I am making few option that would go well with the theme .One that I thought was abstract format and the other one which include element of e commerce plus eco friendly kinda element.

Link : https://new.express.adobe.com/id/urn:aaid:sc:AP:bf47eb31-8825-5c67-83f4-acf208e954c1?invite=true&promoid=Z2G1FQKR&mv=other

The link contains one of the initial design , the color scheme would be different. Will share you one other link which contain font and color scheme detail also.
Have decided the color pallete , and the font. Now I working on Logo. I will make few initial design from which we can select one and go forward.

**Comment by codervivek5** [comment]
it is not looking good .....continue on it and show me complete work

**Comment by ira-mane** [comment]
> it is not looking good .....continue on it and show me complete work

The logo should be more abstract right ? Also how do you want the logo to be ?Any specific suggestions

**Comment by codervivek5** [comment]
Se it will be look like natural and something relatable with name you know - VigyBag like a bag something similar to this and Don't to make it fancy just make it simple and precise

**Comment by soumojeet-mondal** [comment]
Hey, greetings! Can you assign me this issue, I am a contributor for GsSOC as well.

**Comment by solanki505** [comment]
I want to work on this issue please assign me .
![Screenshot 2024-05-18 174852](https://github.com/codervivek5/VigyBag/assets/158484284/d0a4a2b1-4ad8-499b-af39-30e334597f80)

**Comment by Anuja1227** [comment]
Please assign me this issue. This is my first draft and i am working on the second one.
![VB logo](https://github.com/codervivek5/VigyBag/assets/121712572/c7ac1144-fbba-47f6-8546-21f73d823cd7)

**Comment by Anuja1227** [comment]
This is my second and third draft. Please take this into consideration and reply back so that i can continue further work @codervivek5 
![vg logo](https://github.com/codervivek5/VigyBag/assets/121712572/965b818f-863c-49e4-9257-1b0321f55965)

**Comment by codervivek5** [comment]
> This is my second and third draft. Please take this into consideration and reply back so that i can continue further work @codervivek5 ![vg logo](https://private-user-images.githubusercontent.com/121712572/331811077-965b818f-863c-49e4-9257-1b0321f55965.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwNTcwNjEsIm5iZiI6MTcxNjA1Njc2MSwicGF0aCI6Ii8xMjE3MTI1NzIvMzMxODExMDc3LTk2NWI4MThmLTg2M2MtNDllNC05MjU3LTFiMDMyMWY1NTk2NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxOFQxODI2MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMDE0OWQ1MDQxYTFmZWYzN2NiYTI1MjMzMWM4NGU2MGQ5Mzk2ODk5ODRjNzVjOTU2MDg4YTI4OTQwZTI5ZmFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vZzdNXAJUnEgc8ZnyD7tf-Vk3KEZYdNGZRg1C4fAALY)

This is looking good can you modified it little bit more

**Comment by codervivek5** [comment]
> I want to work on this issue please assign me . ![Screenshot 2024-05-18 174852](https://private-user-images.githubusercontent.com/158484284/331800462-d0a4a2b1-4ad8-499b-af39-30e334597f80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwNTcxMTIsIm5iZiI6MTcxNjA1NjgxMiwicGF0aCI6Ii8xNTg0ODQyODQvMzMxODAwNDYyLWQwYTRhMmIxLTRhZDgtNDk5Yi1hZjM5LTMwZTMzNDU5N2Y4MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxOFQxODI2NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ODUyN2ZiN2ZjZjFjMjQzMTRmNjZlNTIxMjdkMjkzZmFjODliZDhkODRiNTYxZmM4MTZjMzBlMWIwYTMzYmIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FUC-7Jhtg5J5KHxLz0Cu9rLH8tsNDvkYL3-mzCHYBdE)

Can you some more designs with different looks

**Comment by Anuja1227** [comment]
> > This is my second and third draft. Please take this into consideration and reply back so that i can continue further work @codervivek5 ![vg logo](https://private-user-images.githubusercontent.com/121712572/331811077-965b818f-863c-49e4-9257-1b0321f55965.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwNTcwNjEsIm5iZiI6MTcxNjA1Njc2MSwicGF0aCI6Ii8xMjE3MTI1NzIvMzMxODExMDc3LTk2NWI4MThmLTg2M2MtNDllNC05MjU3LTFiMDMyMWY1NTk2NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxOFQxODI2MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMDE0OWQ1MDQxYTFmZWYzN2NiYTI1MjMzMWM4NGU2MGQ5Mzk2ODk5ODRjNzVjOTU2MDg4YTI4OTQwZTI5ZmFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vZzdNXAJUnEgc8ZnyD7tf-Vk3KEZYdNGZRg1C4fAALY)
> 
> This is looking good can you modified it little bit more

Sure.. could you tell me which colour combination you like better?....so that i can work on that particular one

**Comment by Anuja1227** [comment]
And can you specify few changes you want please?

**Comment by Anuja1227** [comment]
I had made a modification. Should i send it here? And please assign me this.

**Comment by ira-mane** [comment]
@codervivek5  Hello , even I was working on the design .But you unassigned me without even tagging me here.

**Comment by jayraj175coder** [comment]
Hi @codervivek5  I have one design I think better than earlier ones ,Check it 
![vigyBagg](https://github.com/codervivek5/VigyBag/assets/135996214/73da7f1d-0b5f-461b-a8f0-5fe1e2099128)
![vigyBagg](https://github.com/codervivek5/VigyBag/assets/135996214/73da7f1d-0b5f-461b-a8f0-5fe1e2099128)
![vigyBagg](https://github.com/codervivek5/VigyBag/assets/135996214/73da7f1d-0b5f-461b-a8f0-5fe1e2099128)

**Comment by jayraj175coder** [comment]
Hi @codervivek5 , I have one design check it .  HOPE YOU like 
![image](https://github.com/codervivek5/VigyBag/assets/135996214/0e796cf0-c7cc-408e-9ba5-ea5a90ca0334)

**Comment by jayraj175coder** [comment]
Hi @codervivek5 , I have made two designs hope you like. 
![Screenshot 2024-05-20 220116](https://github.com/codervivek5/VigyBag/assets/135996214/ca52c08f-ab99-456f-bd77-5a44f991ce8e)
![Screenshot 2024-05-20 220116](https://github.com/codervivek5/VigyBag/assets/135996214/ca52c08f-ab99-456f-bd77-5a44f991ce8e)

**Comment by jayraj175coder** [comment]
HI @codervivek5 , I made one design Hope You like it seems beautiful   than previous ones...
![Screenshot 2024-05-20 220116](https://github.com/codervivek5/VigyBag/assets/135996214/fc7e4c18-182a-4a51-bdf6-cdcb9256c0af)

**Comment by numitasahu** [comment]
I want to work on this issue please assign me. and I made one design Hope You like it
![logo](https://github.com/codervivek5/VigyBag/assets/148805208/85b64237-b1fc-43d7-a181-791ff92643ac)
