### ISSUE TITLE
Re-design UI of VigyBag - Make it look like eco friendly

### ISSUE THREAD

**Issue by codervivek5** [codervivek5/VigyBag#1068]
**Read these points carefully**

- The design should look like eco friendly
- In this new design, we will try to add handmade and eco-friendly products.
- use a natural color pallet it will look like a natural theme.

 Figma page link given below:
https://www.figma.com/file/hXcM6chTK70O6rAqCTFxuc/Vigy?node-id=0%3A1&t=px6VNjlFCos5Ll9z-1

Do not remove the old design just start your creativity in the below section.

**Comment by ira-mane** [comment]
@codervivek5  can you please assign me this issue ? I would look to work on the issue.

**Comment by codervivek5** [comment]
@ira-mane this is very serious task so if you can do it then I can assign it to you


can you share your previous work.

**Comment by ira-mane** [comment]
> @ira-mane this is very serious task so if you can do it then I can assign it to you
> 
> can you share your previous work.

I think I can work on the issue. I will share my previous work with you .
Thankyou.

**Comment by codervivek5** [comment]
I am waiting for your response:

**Comment by codervivek5** [comment]
if possible share your profile or any social handles where you have share your work.

**Comment by Tanmay-Mirgal** [comment]
Hello @codervivek5 can you please assign me this issue ? I would look to work on the issue.
I can share you my previous work or its been on my github repos .
1. https://magma-clone-tanlucifer.netlify.app/
2. https://port-card-tanlucifer-26.netlify.app/
3. https://independent-designer-clone.netlify.app/
4. https://hunch-website-design.netlify.app/
I am sure that you will like my UI design which i will make only the thing what color combos you will prefer?
I hope that you will like my work from above experiences.

**Comment by Tanmay-Mirgal** [comment]
how can i share my work with you ?

**Comment by syrnxalno** [comment]
Hello @codervivek5 , I am interested in redesigning the UI of this website as well. Here are some of my previous UI design works : 
1. https://www.figma.com/design/HkBtu5lNSCyCzGpz4UIwgV/Techy-Software-Company?node-id=0%3A1&t=Hk60HL4Ir7G1T9qw-1
2. https://www.figma.com/design/uvfeGTKC0cUOpzpf8UCQoC/Music-App-UI?node-id=0%3A1&t=xJyvzuzbo1lkxK2Y-1

Thank you for considering. I hope you can assign this issue to me

**Comment by codervivek5** [comment]
Osm designs... ok now you can start working and remember after each page complettion tell me first 
and create a PR so that you can get  your points of each page.

**Comment by codervivek5** [comment]
@ira-mane kindly share your work in have then I will also assign it.
but share your genuine work

**Comment by syrnxalno** [comment]
@codervivek5 Sure, I'll start working on this and keep you updated. Is it possible to send you the finished work of each page via discord first? 

That way I can work on it incase there are any feedbacks from your end and then raise a PR after the design is finalized.

**Comment by codervivek5** [comment]
sure this will fine :)

**Comment by codervivek5** [comment]
- Now I will wait for you first page design....remember it that this is a e-commerce website.

**Comment by codervivek5** [comment]
ping me on discord then i will send you product image so you can take an idea about the website UI

**Comment by Tanmay-Mirgal** [comment]
can you assign me the task
I have showcase my work
1.https://magma-clone-tanlucifer.netlify.app/
2.https://port-card-tanlucifer-26.netlify.app/
3.https://independent-designer-clone.netlify.app/
4.https://hunch-website-design.netlify.app/

**Comment by codervivek5** [comment]
I have to assign it to the first person who comments first ... so wait if other person will not work.

**Comment by codervivek5** [comment]
Thankyou for your Interest

**Comment by syrnxalno** [comment]
Hello @codervivek5 ,I've contacted you over discord. Please look into it.

**Comment by vaishnavip27** [comment]
Hey @codervivek5 I can work on this issue as a designer and a developer. I have good experience in designing and building the website. Please assign this issue to me. Looking forward for your approval

**Comment by codervivek5** [comment]
> Hey @codervivek5 I can work on this issue as a designer and a developer. I have good experience in designing and building the website. Please assign this issue to me. Looking forward for your approval

I already assigned this issue to other but if you want to work on it then you can collaborate with them just try to ask them if they agree then I will also assign this to you

**Comment by Tanmay-Mirgal** [comment]
> I have to assign it to the first person who comments first ... so wait if other person will not work.
See that I had raised the comment before her still you didnt replied !!

**Comment by Tanmay-Mirgal** [comment]
Seems to be biased then !

**Comment by codervivek5** [comment]
> Seems to be biased then !
No I am not biasing dude ... Actually don't mind but I have to follow the gssoc guidelines but if you can improve it then definitely you can.


I appreciate your amazing work bro. 👏 👏 

You can also start working and show me a sample work if it will perfect then I will assign you abd akso will give you level3 tag for your good points.


Ans sorry for not giving your response actually I am not a single person who is handling this project so it's happened

**Comment by Tanmay-Mirgal** [comment]
> > Seems to be biased then !
> > No I am not biasing dude ... Actually don't mind but I have to follow the gssoc guidelines but if you can improve it then definitely you can.
> 
> I appreciate your amazing work bro. 👏 👏
> 
> You can also start working and show me a sample work if it will perfect then I will assign you abd akso will give you level3 tag for your good points.
> 
> Ans sorry for not giving your response actually I am not a single person who is handling this project so it's happened

cant we work both on same project @syrnxalno  ? It will be more creative and fast 
@codervivek5 So assigned to both of us will make it out ..

**Comment by Tanmay-Mirgal** [comment]
> > Seems to be biased then !
> > No I am not biasing dude ... Actually don't mind but I have to follow the gssoc guidelines but if you can improve it then definitely you can.
> 
> I appreciate your amazing work bro. 👏 👏
> 
> You can also start working and show me a sample work if it will perfect then I will assign you abd akso will give you level3 tag for your good points.
> 
> Ans sorry for not giving your response actually I am not a single person who is handling this project so it's happened

@codervivek5 So assigned to both of us will make it out ..Then you decide which to have ,is that okay?

**Comment by Anuja1227** [comment]
Hello @codervivek5 , Please assign me the issue if there is no one to work on it , I have good experience in UI design. I am sharing some of my work with you :
https://www.figma.com/design/JSaMDcEbKInEHquoxdacVy/Among-Us-game?node-id=3-2

**Comment by codervivek5** [comment]
> Hello @codervivek5 , Please assign me the issue if there is no one to work on it , I have good experience in UI design. I am sharing some of my work with you : https://www.figma.com/design/JSaMDcEbKInEHquoxdacVy/Among-Us-game?node-id=3-2

Ok read oll the above comments and design a single page I will be good then I will tell you for continuing

**Comment by Tanmay-Mirgal** [comment]
@codervivek5 can you share your discord acc link i want share the UI so i can continue building  it ..
And thanks for giving me opportunty and i believe that you like my Design

**Comment by Anuja1227** [comment]
Sure @codervivek5

**Comment by Tanmay-Mirgal** [comment]
@codervivek5  sir pls check your discord

**Comment by ira-mane** [comment]
@codervivek5 can you check this , and assign me the issue. I would like to work on it .
Link : https://www.figma.com/design/Sple5nVDow2Z5BfxDqqXMv/VigyBag?node-id=1%3A7&t=DGRsNCjGLZXNf8mF-1
check the link ,I have designed few initial draft pages

**Comment by Anuja1227** [comment]
> > Hello @codervivek5 , Please assign me the issue if there is no one to work on it , I have good experience in UI design. I am sharing some of my work with you : https://www.figma.com/design/JSaMDcEbKInEHquoxdacVy/Among-Us-game?node-id=3-2
> 
> Ok read oll the above comments and design a single page I will be good then I will tell you for continuing

Hey @codervivek5 ,  i had made half of landing page (can say home page) and shared with you via mail, please check and tell whether I should continue working on it or not?

**Comment by codervivek5** [comment]
> > > Hello @codervivek5 , Please assign me the issue if there is no one to work on it , I have good experience in UI design. I am sharing some of my work with you : https://www.figma.com/design/JSaMDcEbKInEHquoxdacVy/Among-Us-game?node-id=3-2
> > 
> > 
> > Ok read oll the above comments and design a single page I will be good then I will tell you for continuing
> 
> Hey @codervivek5 , i had made half of landing page (can say home page) and shared with you via mail, please check and tell whether I should continue working on it or not?

sure I will give you feedback via mail

**Comment by codervivek5** [comment]
Thankyou @Anuja1227 for making the perfect design
