### ISSUE TITLE
Improving Sign in with Google Button

### ISSUE THREAD

**Issue by kesharwaniyanshi** [codervivek5/VigyBag#1069]
![image](https://github.com/codervivek5/VigyBag/assets/123561974/63f87c62-d615-4677-9d89-bb7fe34d3b45)
Here the Sign in with Google button is overlapping with 'or' . This can be fixed by improving the dimensions and change some css code. 
Please assign it to me .

**Comment by kesharwaniyanshi** [comment]
I have corrected the issue and now it looks like 
![image](https://github.com/codervivek5/VigyBag/assets/123561974/e7e4b41d-2178-450a-bb85-007da7a30bcc)
on hovering .
I have sent PR ,please accept and merge it.

**Comment by toodiv** [comment]
I can contribute to the issue with a clean and efficient code. Kindly accept my issue under GSSOC'24.
