### ISSUE TITLE
Fixing Search Bar Padding 

### ISSUE THREAD

**Issue by dhritiluthra** [codervivek5/VigyBag#107]
The search bar needs padding and text pointer alignment to left.

**Comment by dhritiluthra** [comment]
Hi!
I want to do this under Gssoc!
from this ->

![Screenshot (33)](https://github.com/codervivek5/VigyBag/assets/92994956/bfb2277a-db95-4e6d-a218-ebb6ef289097)

to this ->
![Screenshot (34)](https://github.com/codervivek5/VigyBag/assets/92994956/e4f37e72-2e03-47c5-924e-a500c01b3739)

**Comment by codervivek5** [comment]
try to remove inner border which is looking like black
