### ISSUE TITLE
 Navigation Bar Text Visibility Issue in Dark Mode in Team Tab

### ISSUE THREAD

**Issue by YSULTRA** [codervivek5/VigyBag#1071]
## Description
The navigation bar text is not clearly visible when the dark mode is enabled. The text colour appears to blend with the background, making it difficult to read. This issue does not occur in light mode, where the text remains perfectly legible.

## Expected Behavior
The navigation bar text should be easily readable in both dark and light modes.

## Screenshots
![image](https://github.com/codervivek5/VigyBag/assets/125336687/3239b372-f6ed-4365-95d9-0782a1596552)

![image](https://github.com/codervivek5/VigyBag/assets/125336687/389ca04e-85f3-404a-b3bc-6898707ce04c)

## Steps to Reproduce
1. Switch to dark mode.
2. Observe the navigation bar text visibility in Team section.

Please assign this issue to me. 
GSSoC 24

**Comment by YSULTRA** [comment]
@codervivek5 please assign this issue to me.

**Comment by NAhmad231** [comment]
@codervivek5 hey can you assign this issue to me
