### ISSUE TITLE
Improve the UI of the hero section

### ISSUE THREAD

**Issue by binary-amigo** [codervivek5/VigyBag#1074]
The colors and text placement seems a bit off in the hero section. I will change it to look more pleasing and pretty.

![Screenshot from 2024-05-16 23-25-10](https://github.com/codervivek5/VigyBag/assets/100588766/6a7e063a-cebc-4f4a-9c83-011a49705e7f)

Assign me this issue

**Comment by officialhemant511** [comment]
hi @codervivek5  i really wanna work on it can u pls assign this issue to me under gssoc label

**Comment by toodiv** [comment]
I can contribute to the issue with a clean and efficient code. Kindly accept my issue under GSSOC'24.
