### ISSUE TITLE
Typo Issue in the See More section

### ISSUE THREAD

**Issue by anagha-chaudhari** [codervivek5/VigyBag#1075]
I just noticed a typo error in the product cards within the "See More" section. It currently says "Add to card" instead of "Add to cart." May I correct this issue under GSSOC'24?

![typoissue](https://github.com/codervivek5/VigyBag/assets/143149376/874a723a-4d78-4f7a-bd42-d07f5c137deb)

**Comment by toodiv** [comment]
I can contribute to the issue with a clean and efficient code. Kindly accept my issue under GSSOC'24.

**Comment by tejj74** [comment]
Since I'm a begginer , this issue will help me understanding how to contribute by correcting typo's , I'll be gratefull if u help me to put my 1st PR, by assigning this issue to me under label "gssoc"
@codervivek5
