### ISSUE TITLE
Contact form needs to be responsive 

### ISSUE THREAD

**Issue by kapilG0** [codervivek5/VigyBag#1079]
Contact form needs to be responsive 
![Screenshot_20240517_200859](https://github.com/codervivek5/VigyBag/assets/59639410/38a0b005-b977-4113-85ef-06ff3392ff66)

**Comment by kapilG0** [comment]
Hello @codervivek5 please assign this issue to me under gssoc 24

**Comment by officialhemant511** [comment]
Hello @codervivek5 please assign this issue to me under gssoc 24 i also wanna work on it

**Comment by toodiv** [comment]
I can contribute to the issue with a clean and efficient code. Kindly accept my issue under GSSOC'24.

**Comment by kapilG0** [comment]
Hello @codervivek5 i have generate pull request https://github.com/codervivek5/VigyBag/pull/1125 for this. please check
