### ISSUE TITLE
create login/signup page 

### ISSUE THREAD

**Issue by Nikita06211** [codervivek5/VigyBag#108]
Hello @codervivek5 
I want to create a login/signup page.
it will have details like - email id, password. for login and a register form which will have details like name, email id, enter password, confirm password.
kindly assign me this issue under gssoc'23.
Thank You

**Comment by Chavisn** [comment]
I would like to work on this project.
kindly assign this issue to me.
I will work according to the guidlines mentioned.
Thank You.

**Comment by codervivek5** [comment]
another candidate is also working on a similar to this issue so at this time I cant assign it to you.
