### ISSUE TITLE
After click on hamburger icons details is hiding behind header

### ISSUE THREAD

**Issue by kapilG0** [codervivek5/VigyBag#1080]
After click on hamburger icon details is hiding behind hamburger icons
![Screenshot_20240517_201253](https://github.com/codervivek5/VigyBag/assets/59639410/1cae4386-e142-4ab0-be87-eff83377f433)

**Comment by kapilG0** [comment]
Hello @codervivek5 please assign this issue to me under gssoc 24

**Comment by khushi-igupta** [comment]
Hello I am a GsSOC'24 contributor and I would like to work on this issue. Can you please assign it to me?

**Comment by kapilG0** [comment]
Hello @codervivek5 please close this issue i am checking that issue but it is working fine and after click on hamburgen pop up box is open that why data is hiding

**Comment by kapilG0** [comment]
Hello @codervivek5 i am closing this issuebecause after checking that issue it is working fine and after click on hamburger pop up box is open that why data is hiding
