### ISSUE TITLE
Add icons on the nav bar beside home,aboutUs,services,team,contact us

### ISSUE THREAD

**Issue by Saimanjari777** [codervivek5/VigyBag#1084]
It would look good if there are icons present beside the list items on the nav bar.
![image](https://github.com/codervivek5/VigyBag/assets/130165687/8475fb46-ad30-43c2-890d-1cd39d4bcf2e)
Please assign this issue to me @codervivek5

**Comment by khushikunte** [comment]
Hello .I am intrested in contributing for this task.I can add icons in the nav bar .Please assign me this under GSSOC'24.
