### ISSUE TITLE
Update the FAQ section

### ISSUE THREAD

**Issue by Saimanjari777** [codervivek5/VigyBag#1086]
The answers to the FAQ section are lorem ipsum which need to be changed.
![image](https://github.com/codervivek5/VigyBag/assets/130165687/fdcd57dd-7ecc-4048-9913-0380a5cfb015)
I am working under GSSoC'24
Please assign this task to me @codervivek5

**Comment by Vassu627** [comment]
Hey! @codervivek5 , I would like to contribute on this issue under GSSOC' 24 contribution.
