### ISSUE TITLE
issue: IMPROVE UI give worst user experience 

### ISSUE THREAD

**Issue by officialhemant511** [codervivek5/VigyBag#1087]
<img width="863" alt="gggg" src="https://github.com/codervivek5/VigyBag/assets/120431671/9fd25270-5ea5-4c21-831c-5944e772d8b4">
hi @codervivek5 can u pls assign this issue to me under gssoc  i really wanna work on it:)

**Comment by Sanujkumar** [comment]
I will be resolve this issue, please assign to me
