### ISSUE TITLE
create animated search bar 

### ISSUE THREAD

**Issue by CodeSage4** [codervivek5/VigyBag#1090]
with an animated search bar improves aesthetics of the website

**Comment by CodeSage4** [comment]
please assign this issue to me

**Comment by toodiv** [comment]
I can contribute to the issue with a clean and efficient code. Kindly accept my issue under GSSOC'24.

**Comment by khushikunte** [comment]
Hello .I am intrested in contributing for this task .Please assign me this under GSSOC'24
