### ISSUE TITLE
[FEATURE]:  Improve in the cart delete button

### ISSUE THREAD

**Issue by ujj654** [codervivek5/VigyBag#1091]
Improvement in the UI of the cart delete button which make the cart more beautiful and user friendly.

Problem Screenshot:-

![image](https://github.com/codervivek5/VigyBag/assets/81877649/b4e74e5f-639b-4ded-85f4-56109adcf722)

Solution Screenshot:- 

![image](https://github.com/codervivek5/VigyBag/assets/81877649/45b0ada9-2c69-493c-b7e7-be202daeb3dd)

**Comment by ujj654** [comment]
@codervivek5 Please assign this issue to me i want to work on it .  #GSSoc'24

**Comment by SanaAzeem512** [comment]
@codervivek5 Hello
please assign this issue to me under GSSOC24
