### ISSUE TITLE
[Documentation] Issue template is missing as per Github Community Standards

### ISSUE THREAD

**Issue by 4darsh-Dev** [codervivek5/VigyBag#1093]
## Description
There is no issue template, 
Adding an issue template will be beneficial as per Github Community Standards segregating the issues : 
1. Bug Report
2. Feature update
3. Custom template
4. Reporting a security vulnerability under security policy

### Assign me under gssoc contributor @codervivek5

**Comment by khushikunte** [comment]
Hello .I am intrested in contributing for this task .Please assign me this under GSSOC'24
