### ISSUE TITLE
Reduced Footer Height

### ISSUE THREAD

**Issue by codervivek5** [codervivek5/VigyBag#11]

**Comment by treasure363** [comment]
@codervivek5 
I'll design the footer and match the appropriate theme taking **_footer height_** into careful consideration.
I would like to solve this issue by myself. You may assign it to me. **Thank you!**

**Comment by s0oraj** [comment]
I would like to resolve this issue @codervivek5 

Can you assign me this issue?
Heres My Resume which you might find useful: [Resume](https://github.com/codervivek5/VigyBag/files/11521351/Resume.pdf)
Ive more than 1 year of experience in android development(check profile for more details)

**Comment by codervivek5** [comment]
@treasure363 any update?

**Comment by treasure363** [comment]
Yes I made the design. It's similar to the footer of Geeksforgeeks. Thought it is more appropriate.
Just taking some time to center the div if you know what I mean
