### ISSUE TITLE
Bug: Mobile Responsiveness of AboutUs page 

### ISSUE THREAD

**Issue by Aniket-2504** [codervivek5/VigyBag#1100]
Hello @codervivek5 ,

I noticed there is a problem in the about Us section if we switch in mobile screen there content is not align properly,

i want to fix this issue and give you the best output , can you please assign me the task , I will give my best, Adding screenshot for more understanding.

![Screenshot 2024-05-19 182220](https://github.com/codervivek5/VigyBag/assets/145179532/f2ef2e33-fd57-4277-9d7b-1311b9931e6a)

Looking forward to your response

**Comment by manishprasad9156** [comment]
Assign me this Issue I can Fix this issue under GSSoC'24
