### ISSUE TITLE
Create Popular Categories section according to New Figma Design in React js

### ISSUE THREAD

**Issue by dhruv389** [codervivek5/VigyBag#1106]
I want to create New  Popular Categories section according to New Figma Design in React js.
---

**PLease asign me this issue , I want to work on it.**

**i fully understand Your Code structure , and also completed previous Full Home section task.**

![Screenshot 2024-05-20 013620](https://github.com/codervivek5/VigyBag/assets/117587892/021a4584-637c-4844-8bc7-d449679488ed)

**Comment by dhruv389** [comment]
Hello @codervivek5,
This issue is valid or not according to new figma design ?? otherwise i close this issue. or assign me this issue.

**Comment by dhruv389** [comment]
Please reply  me @codervivek5 .

**Comment by khushikunte** [comment]
Hello .I am intrested in contributing for this task .Please assign me this under GSSOC'24

**Comment by dhruv389** [comment]
hello @codervivek5 @BTANISHA11 ,
Please assign me this issue.

**Comment by dhruv389** [comment]
hello @codervivek5 @BTANISHA11 ,
Please assign me this issue.

**Comment by dhruv389** [comment]
hello @codervivek5 @BTANISHA11 ,
Please assign me this issue.
