### ISSUE TITLE
Create New Footer according to New Figma design in React js.

### ISSUE THREAD

**Issue by dhruv389** [codervivek5/VigyBag#1107]
I want create New footer Section according to new figma design eco friendly theme in react js.
---
**I want to work on it . please assign me this task.**

![image](https://github.com/codervivek5/VigyBag/assets/117587892/1099a391-c100-424f-9b55-92d6554a8551)

**Comment by dhruv389** [comment]
Hello @codervivek5,
This issue is valid or not according to new figma design ?? otherwise i close this issue. or assign me this issue.

**Comment by dhruv389** [comment]
Please reply  @codervivek5 ,

**Comment by khushikunte** [comment]
Hello .I am intrested in contributing for this task .Please assign me this under GSSOC'24
