### ISSUE TITLE
🌈Create new SignUp page according to  New  figma design in react js (Eco friendly theme)

### ISSUE THREAD

**Issue by dhruv389** [codervivek5/VigyBag#1108]
I want to Create new SignUp page according to  New  figma design in react js (Eco friendly theme).
---

Please assign me this issue . i want to work  on it. i also completed my previous full new Home section task according to  New  figma design in react js .
Please checkout and merge Pull request -  https://github.com/codervivek5/VigyBag/pull/1105

![Screenshot 2024-05-20 014435](https://github.com/codervivek5/VigyBag/assets/117587892/3102c036-b8d4-4208-bea3-3b5f3273c1c0)

**Comment by toodiv** [comment]
I can contribute to the issue with a clean and efficient code. Kindly accept my issue under GSSOC'24.

**Comment by dhruv389** [comment]
Hello @codervivek5 
, **This issue is valid or not according to new figma design ?? otherwise  i close this issue. or assign me this issue.**

**Comment by khushikunte** [comment]
Hii .I am really good at React .I am intrested to contribute for this .Please assign me this under GSSOC'24

**Comment by dhruv389** [comment]
hello @codervivek5 @BTANISHA11 ,
Please assign me this issue.

**Comment by dhruv389** [comment]
hello @codervivek5 @BTANISHA11 ,
Please assign me this issue.

**Comment by dhruv389** [comment]
hello @codervivek5 @BTANISHA11 ,
Please assign me this issue.
