### ISSUE TITLE
[FEATURE] : Adding answers of all the questions in FAQ section

### ISSUE THREAD

**Issue by SadafKausar2025** [codervivek5/VigyBag#1109]
I have seen that no answers where in the FAQ section so I added the answers

https://github.com/codervivek5/VigyBag/assets/137484958/a7e87a94-2445-4763-8ad6-95d648731d2c

**Comment by SadafKausar2025** [comment]
hi @codervivek5 
Can you please assign me this issue?

**Comment by toodiv** [comment]
I can contribute to the issue with a clean and efficient code. Kindly accept my issue under GSSOC'24.

**Comment by codervivek5** [comment]
Thank you for your contribution :)

**Comment by SadafKausar2025** [comment]
Thank You for assigning me
