### ISSUE TITLE
Adding Order Page 

### ISSUE THREAD

**Issue by SyedImtiyaz-1** [codervivek5/VigyBag#1111]
Hello @codervivek5 ,
The Order Page is not ready yet.
Creating a order page for the website.

Kindly assign this issue.

## Screenshot  :
![image](https://github.com/codervivek5/VigyBag/assets/121503426/9eda6efb-d5e7-444c-b0ff-b7e1682f5135)

**Comment by SakiraAli1115** [comment]
Please assign me

**Comment by SyedImtiyaz-1** [comment]
@codervivek5 ,
Please assign this issue to @SakiraAli1115 👍🏻

**Comment by toodiv** [comment]
I can contribute to the issue with a clean and efficient code. Kindly accept my issue under GSSOC'24.

**Comment by codervivek5** [comment]
change it order to Your Order

**Comment by codervivek5** [comment]
before making any changes kindly share any sample image first then start working

**Comment by SyedImtiyaz-1** [comment]
> before making any changes kindly share any sample image first then start working

Yeah, she will.

**Comment by ghost** [comment]
Can you please assign me this issue i can work on it and im also working under GSSOC'24
