### ISSUE TITLE
Number and Mail is not redirecting us on the gmail and dial pad.

### ISSUE THREAD

**Issue by SyedImtiyaz-1** [codervivek5/VigyBag#1112]
Hello @codervivek5 ,
Let's fix this out.

### Screenshot - 
![image](https://github.com/codervivek5/VigyBag/assets/121503426/e28483a6-9841-4464-933c-2bde96234916)

**Comment by SakiraAli1115** [comment]
Please assign me

**Comment by SyedImtiyaz-1** [comment]
Please assign this issue to @SakiraAli1115 👍🏻

**Comment by toodiv** [comment]
I can contribute to the issue with a clean and efficient code. Kindly accept my issue under GSSOC'24.

**Comment by codervivek5** [comment]
and another email - vigybag@gmail.com

**Comment by theashikagupta** [comment]
@codervivek5 Kindly assign me this issue under GSSOC'24
