### ISSUE TITLE
BUG: There is a gap after Nav bar & before products. And Nav bar links.

### ISSUE THREAD

**Issue by gaddevinay** [codervivek5/VigyBag#1113]
Fixing the the gap after Nav bar and before the products.
Improving CSS making website responsive.
Another bug is after clicking on nav bar nav bar services , about and contact it doesn't go to there.
These are two bugs as a GSSOC contributor I can fix them.
![Screenshot_20240520-221024](https://github.com/codervivek5/VigyBag/assets/128584849/c92d2e14-5397-4f41-8524-f3339e7b8538)

**Comment by TheNikhilRaj** [comment]
I would like to work on this issue , please assign this to me.
@codervivek5

**Comment by gaddevinay** [comment]
Solved in pr #1122 @codervivek5
