### ISSUE TITLE
#Login page in not responsive

### ISSUE THREAD

**Issue by roushanverma23** [codervivek5/VigyBag#1121]
the login page is not responsive "Alignment" is not perfect and the hamburger icon is not perfectly implemented

![image](https://github.com/codervivek5/VigyBag/assets/137530796/993c40b6-e49a-4538-bf6f-982cd2e6a077)

<br/>
![image](https://github.com/codervivek5/VigyBag/assets/137530796/4b7e45b6-d820-4139-8be0-3b0b0e5300e4)

**Comment by Shruti0628** [comment]
I would like to contribute to this. Could you please assign this task to me?

**Comment by SDprogramer** [comment]
We can collab here and can do it. I would also like to contribute in it

**Comment by khushikunte** [comment]
Hello .I am intrested in contributing for this task .Please assign me this under GSSOC'24.I can make login page responsive

**Comment by rishuraj1708** [comment]
hey there, I would like to work on this . Please could you assign me this issue.
