### ISSUE TITLE
[FEAT] : Redesign Customer Review Section with New UI and Responsiveness

### ISSUE THREAD

**Issue by dhruv389** [codervivek5/VigyBag#1135]
Description:
The current customer review section on our website needs a redesign to improve its user interface and make it responsive across various devices. The existing design is outdated and does not adapt well to different screen sizes, resulting in a suboptimal user experience. We aim to enhance the visual appeal, usability, and accessibility of the customer review section.

`PLEASE ASSIGN ME THIS  ISSUE. I have made Below design.`
   
`SCREENSHOT:`

After The Chnages THIS Section Looks like this:
---
![Screenshot 2024-05-22 103603](https://github.com/codervivek5/VigyBag/assets/117587892/84a2698d-724e-496e-9288-f03c406f2247)

**Comment by dhruv389** [comment]
hello  @codervivek5 @BTANISHA11  ,
Please assign me this issue.

**Comment by dhruv389** [comment]
hello  @BTANISHA11 ,
Please assign me this issue.

**Comment by codervivek5** [comment]
start working

**Comment by SHARUKA-2005** [comment]
hello @codervivek5 , I am extremely interested in contributing to your project. Could you please assign this issue to me. I can make an even better design than the existing one. Thanking you in advance
