### ISSUE TITLE
FEATURE: Adding new (Buy Now) Buttons in every products.

### ISSUE THREAD

**Issue by SadafKausar2025** [codervivek5/VigyBag#1136]
It will be very good to add this Buy Now button in the product so that if someone wants to buy only one product then it will be easy

https://github.com/codervivek5/VigyBag/assets/137484958/0cfccbac-d20c-4ce9-a079-bd30a1b4a0a1

**Comment by SadafKausar2025** [comment]
Hey @codervivek5 
can you please assign me this issue?

**Comment by TheNikhilRaj** [comment]
I would like to work on this issue , please assign this to me.
@codervivek5
