### ISSUE TITLE
Dangerous Site Show when open in laptop deviceS

### ISSUE THREAD

**Issue by jayraj175coder** [codervivek5/VigyBag#1140]
I need to work on this issue under gssoc24 could you assign me this label level 3 and gsoc.
This is not good when for  your website..  See this
I try to fix within a day.. @codervivek5 
![Screenshot 2024-05-22 200833](https://github.com/codervivek5/VigyBag/assets/135996214/f51faf52-ed74-4b4c-8016-12781333d4f3)

**Comment by codervivek5** [comment]
lets try if you can

**Comment by jayraj175coder** [comment]
https://664ee5ce2fe4dfb7b5d9c2bc--eclectic-travesseiro-ae184a.netlify.app/    
Here is deployment of your website but I could not able to change from your about us section.  You change it.
I only able to add in readme file.
