### ISSUE TITLE
Issue in footer !! (About Us and Team pages)

### ISSUE THREAD

**Issue by SrijaVuppala295** [codervivek5/VigyBag#1145]
The footer is not in the proper format , for about us and team pages.

![Screenshot 2024-05-23 121712](https://github.com/codervivek5/VigyBag/assets/140592148/f58adf61-671b-4037-b09c-91385630f3ce)

![Screenshot 2024-05-23 121730](https://github.com/codervivek5/VigyBag/assets/140592148/c1f0ec86-a4aa-4f27-8394-2e06bbc5a78d)

**Comment by SrijaVuppala295** [comment]
\assign this issue to me

**Comment by codervivek5** [comment]
someone is already working on this same issue
