### ISSUE TITLE
NO PROPER ICONS IN THE NAVBAR FOR MANY PAGES!!!

### ISSUE THREAD

**Issue by SrijaVuppala295** [codervivek5/VigyBag#1147]
No icons for the navabar items .Want to add icons to the navbar items

![Screenshot 2024-05-23 122423](https://github.com/codervivek5/VigyBag/assets/140592148/3f2f2d14-2dd5-40f8-b42c-0ac9a84bf5e0)

![Screenshot 2024-05-23 122436](https://github.com/codervivek5/VigyBag/assets/140592148/0546ad0c-9d5c-450c-9dba-1f047f1f2d8c)

![Screenshot 2024-05-23 122522](https://github.com/codervivek5/VigyBag/assets/140592148/a3c3d135-57d8-4058-906a-65950392acdd) 

![Screenshot 2024-05-23 122530](https://github.com/codervivek5/VigyBag/assets/140592148/e5305329-185c-4419-9802-bf953278ae7a)

**Comment by SrijaVuppala295** [comment]
please assign this issue to me

**Comment by abhinav120304** [comment]
please assign this issue to me
