### ISSUE TITLE
[BUG] : Dark Mode functionality is not working in the about us page!!

### ISSUE THREAD

**Issue by SrijaVuppala295** [codervivek5/VigyBag#1148]
![Screenshot 2024-05-23 122635](https://github.com/codervivek5/VigyBag/assets/140592148/662c6937-d1f3-4206-bd07-7444fd14fece)

**Comment by SrijaVuppala295** [comment]
please /assign this issue to me

**Comment by SanaAzeem512** [comment]
Hello
please assign this issue to me under GSSOC24
