### ISSUE TITLE
Auto commenting feature for new PR raised 

### ISSUE THREAD

**Issue by suhanipaliwal** [codervivek5/VigyBag#1152]
This feature aims to address the problem of delayed and inconsistent communication following the raising of PRs. By automatically commenting on PRs as soon as they are raised, it ensures that contributors receive immediate feedback and acknowledgment for their efforts. This fosters a positive and supportive environment for collaboration, encouraging continued participation and engagement from contributors.

Could you please assign me this issue under GSSOC'24.

**Comment by codervivek5** [comment]
Add comment something like this - KIndly wait for the review and if it is not reviewed within 24 hours then connect with us on Linked In or discord

**Comment by Tejsvapandey1** [comment]
@codervivek5 I was trying to make the bot and i am successful in making that could you pleasee assign me this so that i could raise a pr
