### ISSUE TITLE
Add a dynamic year with copyright section

### ISSUE THREAD

**Issue by arpit4521** [codervivek5/VigyBag#1154]
![Screenshot 2024-05-24 142100](https://github.com/codervivek5/VigyBag/assets/127679958/39508275-2d3e-49ac-8747-f602ed69f721)

> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### What happened?
> BUG:Add a dynamic js function for date  !
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I want to work on this issue

**Comment by arpit4521** [comment]
@codervivek5 and @BTANISHA11 please assign me this issue under gssoc label

**Comment by BTANISHA11** [comment]
Ok start working on the issue
