### ISSUE TITLE
Dark mode functionality is not working for the nav bar.

### ISSUE THREAD

**Issue by I-Saara** [codervivek5/VigyBag#1158]
When switching to dark mode on the website, the nav is unchanged. Please assign me the issue so that I can work on it and make the required edits for it to change too along with the website when switched to dark mode.
Please assign it to me.
I am a contributor at GSSOC'24. @codervivek5

**Comment by SanaAzeem512** [comment]
@codervivek5 Hello
please assign this issue to me under GSSOC24
