### ISSUE TITLE
Contact us page needs a few changes.

### ISSUE THREAD

**Issue by I-Saara** [codervivek5/VigyBag#1159]
On the contact page, first of all, the indentation of the content is not looking good. 
Secondly, the "Contact Us" blue box is rounded at two of the four edges, making it look shabby.
Thirdly, the information collection boxes aren't properly in place, they need corrections about the corners for a neat look.
Please assign it to me.
I am a contributor at GSSOC'24.

**Comment by SanaAzeem512** [comment]
Hello
please assign this issue to me under GSSOC24

**Comment by abhinav120304** [comment]
Hello
please assign this issue to me under GSSOC24
