### ISSUE TITLE
footer at the team page need to improved

### ISSUE THREAD

**Issue by SuhainaFathimaM** [codervivek5/VigyBag#1169]
footer at the team page need to improved
@codervivek5 Please assign me this under GSSoC 2024

**Comment by SuhainaFathimaM** [comment]
@codervivek5 Please assign me this under GSSoC 2024

**Comment by newcodergit** [comment]
Please assign me this issue under Gssoc'24.

**Comment by SanaAzeem512** [comment]
Hello
please assign this issue to me under GSSOC24
