### ISSUE TITLE
[FEATURE] Add sign-up and login using django.

### ISSUE THREAD

**Issue by spaul-12** [codervivek5/VigyBag#117]
Please assign this task to me. I have already made the template for the issue.

**Comment by samsorrahman** [comment]
@codervivek5 would you like to assign it to me Sir

**Comment by spaul-12** [comment]
@codervivek5 would you like me to use django restful framework or just  django authentication for sign-up and login?

**Comment by spaul-12** [comment]
@JigarJoshi04 What should be the credentials for Superuser?

**Comment by JigarJoshi04** [comment]
Firstly, thanks for picking this task.
This would be one of the first and most important backend contribution in this project.

About credentials of superuser,
We should not put this in the issue, as that would be visible to everyone.
In the localsetup you can use the credentials as you want, in the production the maintainer of the project will create the credentials.
So you choose to have your own credentials locally.

PS: Just a reminder, Do not share sensitive information in PR, issues etc.
