### ISSUE TITLE
[FEATURE]  Adding a Attractive Light and dark mode logo

### ISSUE THREAD

**Issue by ujj654** [codervivek5/VigyBag#1170]
The light and dark mode logo is not attractive and it doesn't look better. So we have to add better attractive logo for the theme.
Also the position of logo is not fixed.

Screecshot:- 

![image](https://github.com/codervivek5/VigyBag/assets/81877649/1a088417-ee64-41ba-8b26-803f21c904bf)

Solution image:-

![image](https://github.com/codervivek5/VigyBag/assets/81877649/f71a622a-be86-4fca-9f09-f487f623ca11)

**Comment by SanaAzeem512** [comment]
Hello 
please assign this issue to me under GSSOC24

**Comment by codervivek5** [comment]
no need to change it
