### ISSUE TITLE
Bug: Website not responsive

### ISSUE THREAD

**Issue by Madhuri36** [codervivek5/VigyBag#1174]
The website is not responsive across all devices and also has overflows in many sections.
like:
![image](https://github.com/codervivek5/VigyBag/assets/146222028/bd1245a2-b69b-4112-b64d-6e3f9b969149)
here the elements are getting cut and are overflowing.
I would like to fix this. @codervivek5 please assign this to me under GSSoC'24.

**Comment by abhinav120304** [comment]
I would like to fix this. @codervivek5 please assign this to me under GSSoC'24.
