### ISSUE TITLE
Improving Cards in Home page.

### ISSUE THREAD

**Issue by nagalakshmi08** [codervivek5/VigyBag#1177]
Content in the cards is overflowing, making it difficult to view them properly, especially on smaller screens where the scrolling is too fast to navigate through each card seamlessly.

![Screenshot 2024-05-27 153836](https://github.com/codervivek5/VigyBag/assets/121669832/a19e969d-7639-4ab0-97c7-304b65c7683f)

https://github.com/codervivek5/VigyBag/assets/121669832/508cd84e-5aea-4804-abf2-a4967f03a6c4

Please assign me this task , I would like to contribute to this project under GSSoC'24.

**Comment by Tejsvapandey1** [comment]
@codervivek5 Sir i have prior experience with this . I would like to work on this issue.

**Comment by codervivek5** [comment]
check the price. it is overflowing. You set this price below to the product name then it will look like perfect
