### ISSUE TITLE
Responsive issue for mobile view 

### ISSUE THREAD

**Issue by Vishal-Parasram** [codervivek5/VigyBag#12]
Hey @codervivek5 I noticed that website is not responsive so I want to work on this issue please assign me under GSSoC-23 thanks. ![Screenshot_2023_0520_031017.jpg](https://github.com/codervivek5/VigyBag/assets/93524129/90b8a419-163b-4ef9-ae1f-d7a8cf05d2e3)

**Comment by s0oraj** [comment]
I would like to resolve this issue  @Vishal-Parasram 

Can you assign me this issue?Or any other open issue?
Heres My Resume which you might find useful: [Resume](https://github.com/codervivek5/VigyBag/files/11521351/Resume.pdf)
Ive more than 1 year of experience in android development(check profile for more details)

**Comment by Vishal-Parasram** [comment]
@s0oraj I'm also contributing. I'm not a owner create any other issues.

**Comment by Vishal-Parasram** [comment]
@codervivek5 Thanks for assigning me. I will work on this issue.

**Comment by Vishal-Parasram** [comment]
@codervivek5 Hey I'm working on this issue it take some time sorry for delay.

**Comment by vk20july** [comment]
@codervivek5 sir i want to do this task under gssoc'23

**Comment by Soumya1219** [comment]
@codervivek5 Can you assign me with this issue I want to work on this. I have some prior knowledge on web technologies. 
Kindly assign assign this to me :)
