### ISSUE TITLE
MISSING DARK MODE IN FEW SECTIONS

### ISSUE THREAD

**Issue by Dishika18** [codervivek5/VigyBag#1209]
Dark mode in few sections hasn't been applied properly. 
Please assign this issue to me under GSSoC'24, I can fix it and make the Dark mode look impressive.
![Screenshot 2024-05-30 215239](https://github.com/codervivek5/VigyBag/assets/152963337/6fa8c37e-e286-4c66-b88b-5289ecff1aad)

**Comment by nishant0708** [comment]
Hey i could do this please assign me this issue

**Comment by jahnavithutta129** [comment]
Please assign this to me on GSSOC'24
