### ISSUE TITLE
Enhance: Home section [GSSOC'23]

### ISSUE THREAD

**Issue by Pragati-3003** [codervivek5/VigyBag#122]
I would like to modify the container or home section . 
![IMG_20230522_224959](https://github.com/codervivek5/VigyBag/assets/132778037/ca644d26-7cfe-46ba-aecb-0fc4e3c5c677)

I would like to change the ui/ux of home page to make it more attractive . 
So, please assign this issue to me. 
Thanking you.

**Comment by codervivek5** [comment]
another candidate is also working on a similar to this issue so at this time I cant assign it to you.
