### ISSUE TITLE
Improving the cart page 

### ISSUE THREAD

**Issue by kesharwaniyanshi** [codervivek5/VigyBag#1224]
![image](https://github.com/codervivek5/VigyBag/assets/123561974/3b18cb12-0d5a-423d-9bd4-000ddb12af1b)
the price or number doesn't increment on clicking + or - . We can add functionality to it.

**Comment by Mansii8224** [comment]
can you please assign this task to me , as I already made same website as this here is the reference of mine https://github.com/Mansii8224/Ecommerece_website under GSSOC .
