### ISSUE TITLE
Fix improper alignment in product cards

### ISSUE THREAD

**Issue by kesharwaniyanshi** [codervivek5/VigyBag#1228]
![image](https://github.com/codervivek5/VigyBag/assets/123561974/38034480-0ee6-4d41-84b7-192998e5ac7b)
Alignment of text in these product cards should be fixed for better visual appearance.

**Comment by yashi-15** [comment]
I can work on this issue. Please assign it to me under GSSOC'24.

**Comment by jahnavithutta129** [comment]
I can work on this issue. Please assign it to me under GSSOC'24.
