### ISSUE TITLE
Change UI of chatbot , About and Contributors Page 

### ISSUE THREAD

**Issue by YukiP7** [codervivek5/VigyBag#1236]
I noticed that the chatbot looks different compared to the rest of the website's user interface. I suggest making some changes to the chatbot's appearance by switching the blue color to purple. Please do assign me this issue under gssoc with the appropriate label .

 user interface of each page appears to have inconsistencies, with each page having a different look and feel. This lack of uniformity is not visually appealing.

![Screenshot 2024-05-31 230000](https://github.com/codervivek5/VigyBag/assets/109288720/6c42a9fd-dc3a-46cb-8283-3b2fb127ecc2)

![Screenshot 2024-05-31 230800](https://github.com/codervivek5/VigyBag/assets/109288720/0fcb96c8-725d-4552-adf8-d9b394579acd)
![Screenshot 2024-05-31 230813](https://github.com/codervivek5/VigyBag/assets/109288720/bf0cb432-3b46-499f-b5d0-1c267f16ba08)

#Expected Behaviour 
I can change the background color of each page to be consistent with the home and contact page.

**Comment by YukiP7** [comment]
@codervivek5 Please assign me this issue under gssoc with the appropriate level .

**Comment by Mansii8224** [comment]
can you please assign me this task , you can check my shopping we site here https://github.com/Mansii8224/Ecommerece_website I can make this more attractive with beautiful UI under GSOOC .
