### ISSUE TITLE
Missing of navbar icons on about page 

### ISSUE THREAD

**Issue by YukiP7** [codervivek5/VigyBag#1237]
The about page is currently missing the icons that are supposed to be displayed in the navigation bar.

Current Behaviour 
![Screenshot 2024-05-31 231240](https://github.com/codervivek5/VigyBag/assets/109288720/72b5551f-af8d-4a6b-82f3-89adeeeda4d3)

Expected Behaviour
![Screenshot 2024-05-31 231227](https://github.com/codervivek5/VigyBag/assets/109288720/bb81c5a2-a448-4d54-9211-53e9040ffd8e)

Please assign me this issue under gssoc with appropriate level .

**Comment by KavyaBS123** [comment]
Hey @codervivek5 I am GSSOC Contributor qcan you please assign this issue to me I would be glad to work on it!
