### ISSUE TITLE
BUG: Dark mode button is not working on About Page 

### ISSUE THREAD

**Issue by YukiP7** [codervivek5/VigyBag#1238]
The dark mode button is currently not active on the About Page. The dark mode button is also unavailable for the contact page.

##Current Behaviour 

https://github.com/codervivek5/VigyBag/assets/109288720/32c391ba-4028-4bab-b818-42e6080b9dc6

##Excepted Behaviour 

You can add the toggle button on the Contact Page and make it active for the About page.

Please assign me this issue under gssoc with its appropriate level .

**Comment by YukiP7** [comment]
@BTANISHA11  Hey, Please label this issue under gssoc and its appropriate level . Also Please do checkout further issues I have  been raised in the same repo.

**Comment by ghost** [comment]
hey, Please assign me this issue under gssoc

**Comment by KavyaBS123** [comment]
Hey @codervivek5 I am GSSOC contributor can you please assign this issue to me. I would be glad to work on it!
