### ISSUE TITLE
[FEAT]:  "Fix Visibility Issue in Contact Page: Adjust Message Box 

### ISSUE THREAD

**Issue by Mahimatestgithub** [codervivek5/VigyBag#1239]
![image](https://github.com/codervivek5/VigyBag/assets/131277652/cd433b52-73a0-4d6a-af68-af5a03e03919)
The the font color of message box needs to be changed.

**Comment by Mahimatestgithub** [comment]
I want to work on this issue. Please assign me this issue.

**Comment by ananyabansal16** [comment]
If this issue is still pending, I can take this up. Lemme know. :)
