### ISSUE TITLE
Bug : Prices of products protrude outside the box

### ISSUE THREAD

**Issue by Mahimatestgithub** [codervivek5/VigyBag#1240]
![image](https://github.com/codervivek5/VigyBag/assets/131277652/2c5689d0-9036-4f13-ba79-21c9247a06b3)
Prices of every item is protruding outside its Box.

I want to work on this issue. Please assign me.

**Comment by codervivek5** [comment]
Mahima currently someone is working on this issue.
So I can't assign it you right now.

Wait for a day if they can't then I will assign you definitely
