### ISSUE TITLE
UI Enhancement of "What do our customers say" section.

### ISSUE THREAD

**Issue by sharmi4590** [codervivek5/VigyBag#1260]
The present UI is taking up a lot of space on the webpage and even some of the text is missing in the cards.
![Screenshot (527)](https://github.com/codervivek5/VigyBag/assets/102676949/a3c058fe-2ac7-4a66-91e8-69ec9e32113e)

I want to improve the testimonial sections.
This is my previous work
![Screenshot (398)](https://github.com/codervivek5/VigyBag/assets/102676949/43583291-9f54-46e2-92b9-98fef60ac34a)
![Screenshot (399)](https://github.com/codervivek5/VigyBag/assets/102676949/d8fc0574-ea89-434e-a6cd-dd35ece9ffc1)

On hover, the card rotates. I will make sure to match your whole UI as well.

**Comment by SHARUKA-2005** [comment]
codervivek5 could you please assign this issue to me. Also add labels gssoc, level 1 in this issue. Thanking you in advance!
