### ISSUE TITLE
FEATURE - Add CSS enhancement to the navbar

### ISSUE THREAD

**Issue by Abhay182005dat** [codervivek5/VigyBag#1268]
Greetings !!

I have a feature recommendation to this website by adding additional UI properties to the navbar to look it more interesting in the dak mode and light mode.I hope you will like it so please assign me this issue

**Comment by SHARUKA-2005** [comment]
Hello @codervivek5  could you please assign this issue to me, I am really interested to work your project, Hoping you to give me the chance, thanking you in advance

**Comment by SHARUKA-2005** [comment]
Also, @codervivek5 could you please add the necessary labels, Thank you
