### ISSUE TITLE
FIX ISSUE - Fix the issue of the containers on the main page

### ISSUE THREAD

**Issue by Abhay182005dat** [codervivek5/VigyBag#1269]
![git](https://github.com/codervivek5/VigyBag/assets/145827052/d0cc8e2e-1f22-4540-aa7d-a1e0aa7e1f5a)
Greetings !!
i would like to fix this issue of the containers as the price of the items are coming outside the box and it ofcourse doesnt look nice .
Also i would like to add some more css properties to this containers to enhance the website's UI.

**Comment by TAnisha016** [comment]
hey @codervivek5 I would like to work on this issue and improve it. Can you please assign this to me?

**Comment by Abhay182005dat** [comment]
> hey @codervivek5 I would like to work on this issue and improve it. Can you please assign this to me?

@TAnisha016  You need to create your own pull request with your innovative ideas on how you can develop or modify or enhance the website .I hope you understand :) .

Thanks

**Comment by TAnisha016** [comment]
Yes I completely understand, I'm a beginner so I was confused previously
but now I know that I need find the ideas myself then offer it. Thank you
for contacting.

**Comment by Abhay182005dat** [comment]
No probs :)
