### ISSUE TITLE
[New] create make payment page

### ISSUE THREAD

**Issue by codervivek5** [codervivek5/VigyBag#127]

**Comment by yellurividyendra** [comment]
i am GSSOC'23 contributor
i would like to do this project using kotlin
so kindly assign me this project 
@codervivek5

**Comment by yellurividyendra** [comment]
i am GSSOC'23 contributor
i would like to do this project using kotlin
so kindly assign me this project
@codervivek5

**Comment by s4shantanu** [comment]
> i am GSSOC'23 contributor i would like to do this project using kotlin so kindly assign me this project @codervivek5

But we use the Django framework as a backend so can you  please make in django?

**Comment by yellurividyendra** [comment]
sorry sir as i am not familiar with Django framework to do .so i choose kotlin to do it better.
@s4shantanu @codervivek5

**Comment by s4shantanu** [comment]
> sorry sir as i am not familiar with Django framework to do .so i choose kotlin to do it better. @s4shantanu @codervivek5

yeah, but our backend is build with Django someone is already working on that so please contact @codervivek5 for this issue.

**Comment by codervivek5** [comment]
@yellurividyendra  try to make at least the front end.

If you know kotlin then you can work in the android app

**Comment by yellurividyendra** [comment]
sure sir i will work on this pat using kotlin
@codervivek5

**Comment by codervivek5** [comment]
i will give you a figma design you can go through it
https://www.linkedin.com/safety/go?url=https%3A%2F%2Fwww.figma.com%2Ffile%2FNSzGo2uHvqgq4aruqRc5Jf%2FVigyBag%253A-Android-App%3Ftype%3Ddesign%26node-id%3D0%253A1%26t%3DmaRyRSMFf7sf0who-1&trk=flagship-messaging-web&messageThreadUrn=urn%3Ali%3AmessagingThread%3A2-MGY2YzUyMzktMmYzZS00MTk4LTg1NDgtZDIxZDhmZmM1ZGE0XzAxMA%3D%3D&lipi=urn%3Ali%3Apage%3Ad_flagship3_messaging_conversation_detail%3BwbYqw5BbRGSMbRIeq%2FzfVQ%3D%3D

**Comment by yellurividyendra** [comment]
sir it is showing as *PAGE NOT FIND*
@codervivek5  could you please provide me a correct link
