### ISSUE TITLE
Heart icon should not overlap image 

### ISSUE THREAD

**Issue by kapilG0** [codervivek5/VigyBag#1274]
![Screenshot_20240602_163229](https://github.com/codervivek5/VigyBag/assets/59639410/a84f9dd1-5574-4805-b3f4-84e644ad1c2e)

**Comment by kapilG0** [comment]
Hello @codervivek5 please assign this issue to me under gssoc 24

**Comment by TAnisha016** [comment]
Hello PA, It would be great if you could assign me this issue Under GSSOC'24
