### ISSUE TITLE
Content should not flow outside of card

### ISSUE THREAD

**Issue by kapilG0** [codervivek5/VigyBag#1275]
![Screenshot_20240602_163337](https://github.com/codervivek5/VigyBag/assets/59639410/a6190b58-6a7f-4000-80fb-68156661db81)

**Comment by kapilG0** [comment]
Hello @codervivek5 please assign this issue to me under gssoc 24

**Comment by TAnisha016** [comment]
Hello PA, It would be great if you could assign me this issue Under GSSOC'24
