### ISSUE TITLE
feat: adding feedback section

### ISSUE THREAD

**Issue by solanki505** [codervivek5/VigyBag#1279]
feedback is important feature to know the suggestion of the users, using this site. I would like to add a feedback icon in the home page section which will direct us to a feedback page like this
![Screenshot 2024-06-02 175155](https://github.com/codervivek5/VigyBag/assets/158484284/45c207f5-229e-41de-a6d4-d63ef94b9d77)

**Comment by tikaram1912** [comment]
Please assgin this issue to me under GSSoC'24, I want to work on it.
