### ISSUE TITLE
Update Splash Screen  - EcoFriendly Feature

### ISSUE THREAD

**Issue by Yatra052** [codervivek5/VigyBag#1286]
Hi,  I have update a Splash Screen, which consist of eco friendly feature.
Attaching a screenshot
![splash](https://github.com/codervivek5/VigyBag/assets/108984857/2f0e4743-4ad3-47da-8ab5-5b8a6153db48)

**Comment by Gaurav-Kushwaha-1225** [comment]
Hi  @codervivek5 ,
I am a contributor in GSSoC 24.
Can you please assign this issue to me ??

**Comment by codervivek5** [comment]
let's join meeting today at 10 pm [link](http://meet.google.com/gsi-tzvz-hkw)

**Comment by codervivek5** [comment]
@Gaurav-Kushwaha-1225 connect with me on Linked In for more discussion
