### ISSUE TITLE
Modern Looking UI for Landing Page

### ISSUE THREAD

**Issue by satyam8932** [codervivek5/VigyBag#1291]
Hi @codervivek5
I want to update the existing landing page UI with a modern looking sleek desing UI so that it can be visually appealing with multiple sections and components.
It will going to have a lot of work related to the desining stuff. I will create a Figma desing then will start implementaion to make it amazing looking.

Please assign me this issue under gssoc, level 3 , enhancement labels.

Thanks
Satyam

**Comment by codervivek5** [comment]
@satyam8932  connect with me in Linkedin or discord for more detail

**Comment by satyam8932** [comment]
> @satyam8932 connect with me in Linkedin or discord for more detail

Hey I messaged you on linkedin can you please assign me the issue now

**Comment by BrindaManani** [comment]
I would like to contribute to designing the UI for landing page using Figma.
So kindly assign me this task.

**Comment by satyam8932** [comment]
That's my issue... I have created it so you don't have to be sneaky and goofy here fr.
