### ISSUE TITLE
Bug: Twitter should be replaced with X

### ISSUE THREAD

**Issue by AkhilaSunesh** [codervivek5/VigyBag#1300]
![image](https://github.com/codervivek5/VigyBag/assets/140897461/749f103a-09f3-4bdf-a780-42a46e15c69e)
Location: Documentation
Kindly assign me this issue

**Comment by KavyaBS123** [comment]
Hey @codervivek5 I am GSSOC contributor can you please assign this issue to me. I would be glad to work on it!
