### ISSUE TITLE
Website design Bug

### ISSUE THREAD

**Issue by chaanakyaaM** [codervivek5/VigyBag#1302]
The price text is coming out of the container, which makes the website odd.
I would like to fix this bug under Gssoc'24.

Screenshot:

![image](https://github.com/codervivek5/VigyBag/assets/131477601/201ab134-60df-4326-bcd0-1f46fd8a2862)

**Comment by 14Mayank2004** [comment]
Try putting it into a div and then put this div inside the main div. You can use flexbox or the grid both after that to take it to the correct place
