### ISSUE TITLE
Issue: Improve UI Design - Better Colors, Fonts, and Background

### ISSUE THREAD

**Issue by ChanchalTolani** [codervivek5/VigyBag#1308]
The current UI design of the project could benefit from enhancements to the color scheme, fonts, and background to improve overall user experience and accessibility. Proposed Changes:
1. **Color Scheme:**
   - Introduce a more cohesive and modern color palette.
   - Ensure sufficient contrast between text and background for better readability.
   - Consider using color-blind friendly colors to make the interface more accessible.

2. **Fonts:**
   - Adopt a more readable and aesthetically pleasing font.
   - Ensure consistent font usage across different components of the UI.
   - Adjust font sizes to improve readability and hierarchy of information.

3**. Background:**
   - Update the background to a cleaner and more visually appealing design.
   - Avoid overly bright or dark backgrounds that can strain the eyes.
   - Consider subtle patterns or gradients to add depth without distraction.
   
   @codervivek5 Please assign me to work om this issue.

**Comment by richadubeyes** [comment]
I would like to work on this issue,please assign me.
