### ISSUE TITLE
Proper alignment in name and price of product  

### ISSUE THREAD

**Issue by ShahHetviIT** [codervivek5/VigyBag#1318]
Feature Description:
- Add proper margin and padding between name and price of product in every product card.

Add ScreenShots:
<img width="908" alt="image" src="https://github.com/codervivek5/VigyBag/assets/96531029/4cc3b0f4-6fff-4e7d-9552-cd7b8f63bcce">

Record:
- I have read the Contributing Guidelines.
- I'm a GSSOC'24 contributor.
- I have starred the repository.

**Comment by KeerthiPadamata** [comment]
I would like to work on this issue. Please assign me this issue under GSSoC' 24 to contribute to this project
