### ISSUE TITLE
[style] Navbar hover effect

### ISSUE THREAD

**Issue by puneet426** [codervivek5/VigyBag#1319]
here in this site the navbar does not hover please assign this issue to me 

https://github.com/codervivek5/VigyBag/assets/168094736/7fe19c3a-0043-4baa-9f3b-fbfc4b3929b2

i make the navbar like i made it for previous thts looking good

https://github.com/codervivek5/VigyBag/assets/168094736/079b7a6d-3e52-462e-afc3-3af04a9c55c2

@codervivek5 please assign this issue to me

**Comment by Aashka19** [comment]
plz assign it to me
