### ISSUE TITLE
Footer is not properly responsive

### ISSUE THREAD

**Issue by purvathnere** [codervivek5/VigyBag#1331]
I have resolved this problem. Please assign this issue to me. 

![IMG_20240609_110541](https://github.com/codervivek5/VigyBag/assets/93878803/2f3206bd-0e4b-4dfc-9830-14694bd73894)
![IMG_20240609_110456](https://github.com/codervivek5/VigyBag/assets/93878803/bf47f0f1-cf0a-4c30-9948-3a2eb425670e)

**Comment by Aashka19** [comment]
plz assign this to me
