### ISSUE TITLE
Correct the spelling of a word

### ISSUE THREAD

**Issue by rolikaagarwal** [codervivek5/VigyBag#14]
I want to correct the spelling of the word "CLOTHS" to "CLOTHES"
![image](https://github.com/codervivek5/VigyBag/assets/81984963/854964ef-5607-4e2a-8f6c-e4d35127ba04)

**Comment by s0oraj** [comment]
I would like to resolve this issue or any other open issue. @rolikaagarwal 

Can you assign me this issue?
Heres My Resume which you might find useful: [Resume](https://github.com/codervivek5/VigyBag/files/11521351/Resume.pdf)
Ive more than 1 year of experience in android development(check profile for more details)

**Comment by rolikaagarwal** [comment]
@codervivek5 I've linked a pull request regarding this issue. Kindly review it. Thanks
