### ISSUE TITLE
Add social media links in the footer section

### ISSUE THREAD

**Issue by s4shantanu** [codervivek5/VigyBag#142]
I would like to add social media links in the social connection section in the footer. 

@codervivek5 Please assign me this issue.

I want to work on this issue as a GSSoc'23 contributor. :)

**Comment by samsorrahman** [comment]
Sir would you like to assign to me I am ready to work on it

**Comment by s4shantanu** [comment]
Hey @codervivek5 please can you share exactly which links ill add there, means can I add your social handles bcoz we don't have a VigyBags LinkedIn, or Instagram account?
So can I pus with your link?

**Comment by codervivek5** [comment]
- email: vigybag@gmail.com

in another place, you add my social media handles
....we will update it later on

**Comment by s4shantanu** [comment]
> * email: [vigybag@gmail.com](mailto:vigybag@gmail.com)
> 
> in another place, you add my social media handles ....we will update it later on



https://github.com/codervivek5/VigyBag/pull/175. 
please check my PR I add output video please review and Merged my PR.

**Comment by ParthMadhvani2** [comment]
hey, @codervivek5 please assign this issue it has been solved & accept my pull request.
