### ISSUE TITLE
Footer and nav bar is facing page redirection issues

### ISSUE THREAD

**Issue by madtitan02** [codervivek5/VigyBag#143]
I would like to improve the footer by adding hover feature and adding correct link to the social media pages and in the section of about us,contact  also nav bar buttonsare irresponsive.I would like to work on this issue, please assign this issue to me under GSSoC'23.

**Comment by samsorrahman** [comment]
Sir I would like to work on this issue!
would you like to assign it to me

**Comment by madtitan02** [comment]
@codervivek5 i cant find social media handles of VigyBag website anywhere in the readme file.The links i found were personal social media handle of your.Do provide me the social media handles of the product i will update it .also i am unable to find html files of aboutus and services kindly update it so it will be functional

**Comment by codervivek5** [comment]
you can get the links from the readme file
