### ISSUE TITLE
Add link to the logo 

### ISSUE THREAD

**Issue by silwite** [codervivek5/VigyBag#144]
I would like to work on this under gssoc'23 as a contributor.

**Comment by s4shantanu** [comment]
Hey @codervivek5 ,
Can you please assign me this issue so I can push my PR!!
I have already done work on this issue.
![Screenshot 2023-05-23 at 12 32 48 PM](https://github.com/codervivek5/VigyBag/assets/67189790/b5656ba5-6faa-4d02-8e82-bf58879ef96a)



Please assign me <3
