### ISSUE TITLE
Adding about us page

### ISSUE THREAD

**Issue by anwesha2002** [codervivek5/VigyBag#1488]
@codervivek5 there is no about us page . I want to add a whole about us page.
![Screenshot 2024-06-25 023511](https://github.com/codervivek5/VigyBag/assets/116761608/1c020f31-98d7-400a-949a-34637b63fc6f)
this is what it looks like

I want to make someting like this
![Screenshot 2024-06-25 024420](https://github.com/codervivek5/VigyBag/assets/116761608/e9731757-9d85-4fda-bde4-75f317d00790)
I am a gssoc'24 contributor. please assign this to me

**Comment by codervivek5** [comment]
This issue is already assign to another candidate so I can't assign to you
