### ISSUE TITLE
Design "Terms and Conditions" Page for new VigyBag Website

### ISSUE THREAD

**Issue by MastanSayyad** [codervivek5/VigyBag#1490]
Hey @codervivek5 i would like to add Terms and conditions page for the newly made VigyBag website

I do have experince with React js As i have previously worked and Created Multiple legal pages 

For reference:

https://github.com/Nactore-Org/Nacto-Care/pull/67

Also congratulations for the new startup! 
Eger to work on it! @codervivek5

**Comment by codervivek5** [comment]
check again privacy policy is added and also some one is working on this for terms and conditions
