### ISSUE TITLE
[Feat]Add hover effect on social media icons

### ISSUE THREAD

**Issue by theashikagupta** [codervivek5/VigyBag#1492]
Add hover effect on social media icons

![Screenshot 2024-06-25 114924](https://github.com/codervivek5/VigyBag/assets/136061047/16502395-dcb8-4c8d-a480-f1be31141221)

Program: GSSoC'24

**Comment by theashikagupta** [comment]
@codervivek5 Kindly assign me this issue under GSSOC'24

**Comment by codervivek5** [comment]
before raise the PR send screen shot of changes

**Comment by heli0707** [comment]
@codervivek5 assign this issue to me i really want to work on this

**Comment by tkshsbcue** [comment]
@codervivek5 i would like to work on this issue please

**Comment by theashikagupta** [comment]
Somebody already fixed this issue .This issue is no longer relevant.

**Comment by codervivek5** [comment]
This issue is solved
