### ISSUE TITLE
Changing the heading style

### ISSUE THREAD

**Issue by mahek0620** [codervivek5/VigyBag#1500]
![image](https://github.com/codervivek5/VigyBag/assets/136893675/0b6908e0-dd63-4143-b3a2-b320751b0713)
![image](https://github.com/codervivek5/VigyBag/assets/136893675/b99f5cfb-697b-4a6c-bc35-57fd556c2829)
Making it attractive and different from others

**Comment by codervivek5** [comment]
don,t make these silly changes... try to find bug then raise PR
