### ISSUE TITLE
Addition of upcoming Sales As Cards

### ISSUE THREAD

**Issue by taniya542** [codervivek5/VigyBag#1504]
Upcoming Sales can be added as cards just above the footer for enhancement.

**Comment by taniya542** [comment]
Please assign me this issue under GSSOC 24

**Comment by codervivek5** [comment]
can you show me any sample for this ?

**Comment by taniya542** [comment]
@codervivek5 Just like this with some hover effects.
![WhatsApp Image 2024-06-25 at 20 31 59_7b060e25](https://github.com/codervivek5/VigyBag/assets/143064148/e03b79b7-89da-49bd-9006-74574b8e5fa8)

**Comment by codervivek5** [comment]
actually some one is working on it
