### ISSUE TITLE
Want to add underline on hover effect on the items of navbar

### ISSUE THREAD

**Issue by piyushkhurana2019** [codervivek5/VigyBag#151]
I want to add underline on hover anumation effect so the the website will look more interactive to the users 
here:- 
<img width="1440" alt="Screenshot 2023-05-23 at 2 29 13 PM" src="https://github.com/codervivek5/VigyBag/assets/96003210/dda8ab13-033c-4fe4-a9fd-f930323879fa">

**Comment by codervivek5** [comment]
another candidate is already working on it so I can assign it to you.

I am really sorry you can work on another issue..but try to comment in a predefined case so that you can clarify all the problems which are not assigned to any other candidate
