### ISSUE TITLE
Making Shop now button responsive 

### ISSUE THREAD

**Issue by Saipradyumnagoud** [codervivek5/VigyBag#1523]
When we click on the shop now there is no response so i want to make the button  responsive when the shop now button is pressed.

**Comment by Saipradyumnagoud** [comment]
@codervivek5 Please assign me the issue

**Comment by codervivek5** [comment]
it is looking fine. let me know what changes you want to make

**Comment by Saipradyumnagoud** [comment]
> it is looking fine. let me know what changes you want to make

When you press on shop now it goes to popular categories

**Comment by codervivek5** [comment]
Join discord then I will share meeting link we discuss more about the project

**Comment by Saipradyumnagoud** [comment]
> Join discord then I will share meeting link we discuss more about the project 
> 

discord link please @codervivek5

**Comment by codervivek5** [comment]
Check the second comment...

**Comment by Saipradyumnagoud** [comment]
@codervivek5 why did you unassign me again

**Comment by codervivek5** [comment]
Actually this was already assigned to someone so that's why

**Comment by codervivek5** [comment]
You ca check if find any issue then let me know plz

**Comment by Saipradyumnagoud** [comment]
> Actually this was already assigned to someone so that's why

That issue is not exist i hope @codervivek5
