### ISSUE TITLE
Enhancement: UI of the website and header update.

### ISSUE THREAD

**Issue by Nikhiljangra04** [codervivek5/VigyBag#1528]
In the website, there should be some changes to make it excellent and the user feels nice when he/she comes to the website. Firstly, in the header section the logo size is very much small in which the name VigyBag is looking vey small that should be updated. Then in the popular categories section the  name  of the items is not properly visible so there should also be a nice one color used to improve it and making it dashing.
![Vbag1](https://github.com/codervivek5/VigyBag/assets/169473705/97af5f78-e9c6-4729-9b66-ce5aebbb14d5)
![Vbag2](https://github.com/codervivek5/VigyBag/assets/169473705/0f4bde26-59f1-4527-afbc-54a58651e6d8)

**Comment by codervivek5** [comment]
someone is already working in it.
