### ISSUE TITLE
No content in About us page

### ISSUE THREAD

**Issue by ankiiitagupta** [codervivek5/VigyBag#1536]
There is no content in About us page. If you want I can add the content in about us page as per the webapp.
![Uploading Screenshot 2024-06-26 233056.png…]()
![Uploading Screenshot 2024-06-26 233056.png…]()

Kindly assign me this issue under GSSOC'24.

**Comment by codervivek5** [comment]
It is underdevelopment...if you want to work on it then come to join discord and take a look of new figma design of about page

**Comment by 143divya** [comment]
Can you please assign this issue to me under Gssoc'24? I want to work on this.

**Comment by codervivek5** [comment]
This done you can raised a new issue by finding bug on it
