### ISSUE TITLE
BUG: Unresponsive Contact Us page

### ISSUE THREAD

**Issue by techy4shri** [codervivek5/VigyBag#1538]
The contact us page is unresponsive and doesn't work. I can make it active, add compulsory fields, define input type and ensure it takes input data and submits it.
![image](https://github.com/codervivek5/VigyBag/assets/141991095/374484c9-ca7a-4f52-914d-dd2f6e8f05f4)

**Comment by srilekha279** [comment]
I also want to contribute to this issue.
I want to collaborate with @techy4shri 
Please assign me this issue.

**Comment by techy4shri** [comment]
@srilekha279 no need.
