### ISSUE TITLE
BUG: "404 Page not found Error" on Page Refresh 

### ISSUE THREAD

**Issue by MastanSayyad** [codervivek5/VigyBag#1542]
Hey @codervivek5 

The Pages on the website only work for short time, When navigating to pages other than the homepage on the website and then refreshing the page, a 404 error is displayed. This issue does not occur on the homepage.

Upon refreshing any page other than the homepage, users encounter a 404 error with the following message: 
`404: NOT_FOUND Code: NOT_FOUND ID: bom1::5gvdl-1719439676658-77720d0fe35c.`

![image](https://github.com/codervivek5/VigyBag/assets/101971980/aaf57973-324d-4a8c-a329-c0b14953e0e4)

 This error prevents users from accessing the page content 

### Steps to Reproduce
- Navigate to any page other than the homepage.
- Refresh the page.
- Observe the 404 error message displayed instead of the expected content.

https://github.com/codervivek5/VigyBag/assets/101971980/ba3ef1e5-8182-46b2-97dc-2976f608c46f

### Expected behaviour
After refreshing any page, users should be able to view the content without encountering a 404 error. The website should maintain consistent navigation functionality across all pages.

Could you please assign this issue to me?

**Comment by codervivek5** [comment]
Kindly pull the code... It's working properly

**Comment by MastanSayyad** [comment]
@codervivek5 No it's not working kindly check the website pages and refresh them

**Comment by MastanSayyad** [comment]
> Kindly pull the code... It's working properly

In preview and local server it will not cause any error but after deployment it shows this error due to vite frameworks redirect rewrting rules are not configured, You can check , just open the pages except Home and refresh them they will show this error as you can see in above screen record @codervivek5
