### ISSUE TITLE
Feature✨ : Add "Dark Mode" and "Light Mode" Toggle Functionality

### ISSUE THREAD

**Issue by Tejashri-Taral** [codervivek5/VigyBag#1545]
Hey @codervivek5 ,

**Feature Description**

-    The website currently only supports a single theme (light or dark).

-    Implementing a dark mode and light mode toggle feature would significantly enhance user experience by allowing users to switch between light and dark themes based on their preference or lighting conditions.

**Use Case**

 -   A user wants to switch to a different theme (dark mode or light mode).
 -   User Navigates to the website.
 -   User Clicks on the dark mode/light mode toggle button.
 -   System Switches the website's theme to the selected mode (dark or light).

**Benefits**

 -   To improve user experience and accessibility,
 -   This feature allows users to switch between light and dark themes,
 -   Better readability and comfort in different lighting environments

Are you contributing under any open-source program?
GSSOC'24

I hope I was able to explain the issue and the expected solution.
If so, Could you please assign this issue to me under GSSoC 24?

**Comment by codervivek5** [comment]
Ok you va start working on it

**Comment by 143divya** [comment]
Can you please assign this issue to me under Gssoc'24? I want to work on this.

**Comment by abhay-sen** [comment]
@codervivek5 sir could you please assign this issue to me as its been a complete month and yet no pr has been raised yet i assure you that i will work on this at the latest and raise the pr as soon as possible

**Comment by codervivek5** [comment]
this is an e-commerce website so at this time we'll not add this darkmode feature at this time..kindly find another issue
