### ISSUE TITLE
bug: fixing the error page

### ISSUE THREAD

**Issue by SadafKausar2025** [codervivek5/VigyBag#1546]
![Screenshot (2035)](https://github.com/codervivek5/VigyBag/assets/137484958/12bfa825-4f1d-4699-9d59-a5db9aab94ed)

**Comment by Tanmay-Mirgal** [comment]
its working fine

**Comment by SadafKausar2025** [comment]
> its working fine

check it again , in mine it was not working

![Screenshot (2038)](https://github.com/codervivek5/VigyBag/assets/137484958/9a245857-3881-469b-b8e9-2f516c6597c1)
