### ISSUE TITLE
Newsletter Section Addition

### ISSUE THREAD

**Issue by Damini2004** [codervivek5/VigyBag#1567]
Adding the newsletter section in the footer of the website where user get regular update.
![image](https://github.com/codervivek5/VigyBag/assets/119414762/0f4d40ea-9758-4d68-bfbd-dad667378206)

**Comment by codervivek5** [comment]
Let me know first. Where you will add this feature ?

**Comment by Damini2004** [comment]
![image](https://github.com/codervivek5/VigyBag/assets/119414762/eeb33c92-aaf2-4a9e-81ae-71fc0f3a0732)
Footer section

**Comment by codervivek5** [comment]
Your image in showing

**Comment by codervivek5** [comment]
https://formsubmit.co/

Use this service send email (official email- vigybag@gmail.com)

**Comment by Damini2004** [comment]
after the phone number or at the bottom side of appstore

**Comment by Damini2004** [comment]
![image](https://github.com/codervivek5/VigyBag/assets/119414762/c8645d06-be20-4593-bd52-1d6e8f3cf7e5)
 Here i have implemeted the the newsletter section in two place kindly let me know where i have to add the newsletter section then i will create PR.
 @codervivek5
