### ISSUE TITLE
Nav Header is Not  perfect

### ISSUE THREAD

**Issue by GleanCoder** [codervivek5/VigyBag#157]
![2023-05-23 (2)](https://github.com/codervivek5/VigyBag/assets/121458753/b40739d4-261d-4fcd-8063-6d3d7b391ff5)

**Comment by GleanCoder** [comment]
@codervivek5 can you assign me this I would like to work on it.

**Comment by codervivek5** [comment]
try to fix this nav bar at the top when scrolling and add some animation effects. also, add the issue number at PR time and add output so that I can review your changes.
