### ISSUE TITLE
Add hover effects on scrollbar thumb

### ISSUE THREAD

**Issue by zalabhavy** [codervivek5/VigyBag#1575]
![image](https://github.com/codervivek5/VigyBag/assets/126322584/21e74322-619f-46dc-a7fa-961af44d66de)

By adding hover effects user can feel that he/she holding the scrollbar.
I will also add cursor pointer.

**Comment by zalabhavy** [comment]
@codervivek5 Please assign me !

**Comment by codervivek5** [comment]
@zalabhavy I am assigning this issue to you but remember if your Chang's will not worthit then we can merge it so make it impressive. So that user can feel a personal touch

**Comment by codervivek5** [comment]
Also take a look on corner radius

**Comment by codervivek5** [comment]
After your Changea contact me on discord then show me your chages if everything will fine then raised PR
