### ISSUE TITLE
{ENHANCEMENT] of about us page 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [codervivek5/VigyBag#1586]
I  want to enhance the about us page by adding a fade up animation and fixed some desigining .
![Screenshot 2024-06-29 135300](https://github.com/codervivek5/VigyBag/assets/118350936/8dda7172-8d0d-418d-ad0e-e0f75727d424)

**Comment by codervivek5** [comment]
look at this page again and connect with me in linkedin or discord for more discussion if you find
