### ISSUE TITLE
feat: Sending mail to owner on contact form submission

### ISSUE THREAD

**Issue by Ayesha-Siddiqua88** [codervivek5/VigyBag#1596]
**Description**
Adding a feature where mail will be sent to owner when user submits the contact form to convey some message. This feature will send mail to owner that will contain the user's email address, and all the information that is filled in the form. This enhancement will improve user engagement. I will implement this feature using Emailjs.

@codervivek5 , please assign this issue to me under GSSoC'24

**Comment by codervivek5** [comment]
add this feature in news later

**Comment by codervivek5** [comment]
connect with me in discord and send me test screenshot then Raise PR

**Comment by Ayesha-Siddiqua88** [comment]
Sure, I will send the ss on discord when I complete it on my localhost.

**Comment by Ayesha-Siddiqua88** [comment]
Okay, I will create another issue when I am adding it to newsletter. Is that ok?

**Comment by codervivek5** [comment]
can you choose any other service for this feature

**Comment by Ayesha-Siddiqua88** [comment]
Yes, nodemailer can also be used to implement the same feature. I will do it and create a new PR.

**Comment by Ayesha-Siddiqua88** [comment]
I tried using nodemailer for email sending but I think it is not secure, as it requires an app password, which can expire and pose security risks to your google account. I also thought to use sendGrid but the website itself is having some problems currently. What do you suggest?
