### ISSUE TITLE
Issue with Navbar Icon Spacing

### ISSUE THREAD

**Issue by NAVYA260** [codervivek5/VigyBag#1605]
Hello @codervivek5 ,
I noticed that the icons in the navbar on the left side are currently positioned too closely together. It would greatly enhance the visual appeal if there was a bit more spacing between each icon. This adjustment would help improve readability and overall user experience.
![image](https://github.com/codervivek5/VigyBag/assets/141401827/80252e13-5a47-41b0-aa66-80b62e1b9464)
I would like to take on this issue and make the necessary adjustments. Please assign this issue to me, and I will ensure that it’s addressed promptly.

**Comment by codervivek5** [comment]
before make any change kindly connect with us in discord or linkedIn

**Comment by codervivek5** [comment]
no need to make this change it was looking fine already.
