### ISSUE TITLE
Feature🌟: Add a dedicated "Terms and Conditions" Page 

### ISSUE THREAD

**Issue by aslams2020** [codervivek5/VigyBag#1609]
Hey @codervivek5,

I **want to add a dedicated terms and conditions** page for the website.
currently, **there is an unlinked text in the footer** named as "Terms and conditions" But It is not navigating to the respective page because it is not present in the website.

### What will i do - 
1. **Create a Dedicated "Terms and Conditons"** Page.
2. Styling the **Page to follow the theme** of the website.
3. **Add Naviating link** to go to the page from the footer.

**This is where we will add the Dedicated Page :** 

![image](https://github.com/codervivek5/VigyBag/assets/131389695/7ba9f51b-f2bc-49a9-83e4-a956954efda3)

Could you please assign me this issue under GSSoC'24 ?
thankyou !

**Comment by codervivek5** [comment]
aslam first check the file structure . I think there is already added this place if not then connect with me in discord I'll tell you then which type of page we need

**Comment by aslams2020** [comment]
Hi @codervivek5,
I have checked the file structure as you suggested. I found that there is no existing "Terms and Conditions" page, so I will proceed to create one. 
Please provide me the your discord link

**Comment by aslams2020** [comment]
@codervivek5

**Comment by aslams2020** [comment]
@codervivek5 I messaged you on discord. Please tell me which type of page you need.

**Comment by codervivek5** [comment]
Someone has added this page you can check and if find any bug then lt me know.
