### ISSUE TITLE
Feature Update: To add CSS style in "Frequently Asked Question" section <P> tag.

### ISSUE THREAD

**Issue by sakeel-103** [codervivek5/VigyBag#1612]
@codervivek5 
Dear PS,
assign this task to me under gssoc'24.
I want to work on that section without changing the html format of the section.

video -

https://github.com/codervivek5/VigyBag/assets/136844498/18bb1b68-e83e-47fa-91bb-6310428c46c4

**Comment by codervivek5** [comment]
Someone it already working on it so I can't assign this issue to you at this time
