### ISSUE TITLE
Help Page integration 

### ISSUE THREAD

**Issue by Damini2004** [codervivek5/VigyBag#1624]
![image](https://github.com/codervivek5/VigyBag/assets/119414762/892590e1-03bb-4aeb-9d62-c70d43a15026)
![image](https://github.com/codervivek5/VigyBag/assets/119414762/ce445aa4-5592-44c5-8971-5bfe50a38409)

 Help page is an essential tool for any website or application. It supports user autonomy, enhances the user experience, reduces operational costs, builds trust, and provides continuous, accessible support. Investing in a robust Help page is a strategic move that benefits both the users and the organization.

**Comment by codervivek5** [comment]
Try to find some ecommerce page for help

**Comment by Damini2004** [comment]
sure kindly assign this to me i want to work on it.

**Comment by codervivek5** [comment]
@Damini2004 connect with me on meeting for this issue... Then we'll decide to design help page.. then I'll assign you

**Comment by codervivek5** [comment]
any update ?

**Comment by Damini2004** [comment]
> any update ?
> 

Yess i will update you on discord today

**Comment by codervivek5** [comment]
Yap I got your msg.
