### ISSUE TITLE
[BUG] Event-listeners-visible-on-page

### ISSUE THREAD

**Issue by bhuvangoel04** [codervivek5/VigyBag#1649]
Due to a pull request merge for dynamic nav bar by someone, the event listeners have moved out of the tag and are now visible on the screen.
![Screenshot 2024-07-02 234738](https://github.com/codervivek5/VigyBag/assets/156914582/216676f4-3849-40a6-9053-7b85614b6610)

##CHECKLIST
- [X] I want to work on this issue.
- [X] I have checked for existing issues.
- [X] I am a GSSOC 2024 contributor.

**Comment by codervivek5** [comment]
This is fixed. I'll merge pt in Mrng
