### ISSUE TITLE
Implement complete cart functionalities.

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [codervivek5/VigyBag#1657]
Currently in the website the cart is not working.

I can do the following changes.

1. Add items to cart when user clicks on add to cart button. If item already exists quantity will be increased.
2. In the cart page selected items will be listed. 
3. Users can update (+/-) the quantity.
4. Users can remove an item from the cart.

There are 2 options to implement cart feature. One is using local storage. Other one is storing in server.

I will be okay with both options.  Please let me know, which method you would like to proceed with this approach or if you have any further suggestions.

**Comment by codervivek5** [comment]
join discord for further communication and discussion
