### ISSUE TITLE
Bug: Scroll Down Button Not Working

### ISSUE THREAD

**Issue by tkshsbcue** [codervivek5/VigyBag#1674]
![ezgif-4-38ff13e7a9](https://github.com/codervivek5/VigyBag/assets/32425567/1a15daed-9ea6-4c96-ba4f-4670bcf470a7)
The scroll down button in site is not working

**Comment by tkshsbcue** [comment]
please assign this under GSSOC

**Comment by tkshsbcue** [comment]
@codervivek5 i would like to work on this issue

**Comment by codervivek5** [comment]
we don't need this that's why I remove it ... its only show the indication
