### ISSUE TITLE
Search functionality

### ISSUE THREAD

**Issue by PDBharadwaj** [codervivek5/VigyBag#1676]
Search tab is not working in the nav bar. So, I would like to add search functionality.
@codervivek5 Please assign this to me. I am GSSoC contributor.

**Comment by codervivek5** [comment]
firstly let me know that how you will add this like we need to search like recommendation type...same like amazon  flipcart and other

**Comment by PDBharadwaj** [comment]
I want to implement fuzzy search using fuse.js.
