### ISSUE TITLE
Alignments and Duplicate "Footer Links" in Footer

### ISSUE THREAD

**Issue by MastanSayyad** [codervivek5/VigyBag#1677]
Hey @codervivek5 

- As you can see there are duplicate links for the same in footer section which is unnecessary, I suggest you to remove it 

![image](https://github.com/codervivek5/VigyBag/assets/101971980/e5bc9359-a78e-46e1-99ee-e9717e2bfd00)

- Also We should add the copyright in center and the card details at the left or right side 

![image](https://github.com/codervivek5/VigyBag/assets/101971980/27f494de-2626-4404-96df-4600cfca652a)

Could you pls assign this issue to me?

**Comment by codervivek5** [comment]
remove HOME menu only from the footer as you indicate

**Comment by MastanSayyad** [comment]
![image](https://github.com/codervivek5/VigyBag/assets/101971980/b7e63af1-1341-464f-a6ba-dcd17ab2cc38)


Should i remove these too ? or just home link @codervivek5
