### ISSUE TITLE
Improving UI of HeadPhone section cards to enhance user experience

### ISSUE THREAD

**Issue by abhiruchisarswat** [codervivek5/VigyBag#168]
I would like to add animated hover effect to the cards and also improve the overall design to make it more attractive.
I am well versed in html, css , javascript and react js. Please assign this task to me under Gssoc'23.

**Comment by codervivek5** [comment]
try to ignore react at this time we will add it later on.

**Comment by abhiruchisarswat** [comment]
Please assign me this task.

**Comment by abhiruchisarswat** [comment]
> try to ignore react at this time we will add it later on.

ok

**Comment by abhi03ruchi** [comment]
Hi @codervivek5, I by mistake used my redundant GitHub id for requesting this task, @abhi03ruchi is my official GitHub Id through which I am contributing in Gssoc '23. Please assign this task to me via this id. 


> try to ignore react at this time we will add it later on.
ok

**Comment by codervivek5** [comment]
Try to solve it as soon as possible

**Comment by abhi03ruchi** [comment]
Resolved Issue #168, Plz review and merge my PR.

**Comment by abhi03ruchi** [comment]
I would like to enhance the 'Clothes For You' Section too in a similar manner. Should I create a new issue for the same?

**Comment by codervivek5** [comment]
![Screenshot 2023-05-25 144605](https://github.com/codervivek5/VigyBag/assets/62784060/04e25940-225b-4b62-a3f9-a90a67009d94)
