### ISSUE TITLE
Fix : the nav bar  and mobile menu nav [GSSOC 2023]

### ISSUE THREAD

**Issue by Gurnav224** [codervivek5/VigyBag#17]
I want to fix this for the mobile and tablet  add a hamburger menu for the mobile and tablet view

https://github.com/codervivek5/VigyBag/assets/72142482/4bed556e-a13b-49ea-8412-c23cde3adb22

I work on the issue for Gssoc 2023

**Comment by jessicacb12** [comment]
Greetings! I would like to work on this under GSSOC'23. I have been working as Frontend Engineer for 2.5 years using React TypeScript. Looking forward to be assigned in this project!

**Comment by Gun2902** [comment]
can u assign me this issue

**Comment by purviporwal1812** [comment]
Pls assign this issue to me , I would love to contribute

**Comment by codervivek5** [comment]
@Gurnav224 any update?
if you can't do it kindly give me respond so that I can assign to another candidate.

**Comment by Gurnav224** [comment]
I am doing it

**Comment by ParthMadhvani2** [comment]
hey, I have fixed the navbar issue please merge my pull request. I am a GSSoC'23 contributor.

**Comment by codervivek5** [comment]
> hey, I have fixed the navbar issue please merge my pull request. I am a GSSoC'23 contributor.

sorry @ParthMadhvani2 I can not assign this issue to you....this is against the GSSOC policy...if you want to work on it then raised a new issue then tell me.

but check the website regarding the problem or bug before raising the issue ...
