### ISSUE TITLE
Fix cart functionality using Redux toolkit 

### ISSUE THREAD

**Issue by codervivek5** [codervivek5/VigyBag#1710]

**Comment by shivansh84ya** [comment]
hey @codervivek5 ,
Could you please assign the #1710 issue to me ??

**Comment by codervivek5** [comment]
First conduct a meeting regarding the issue then start working on it ...let me kno the timing and also join discord

**Comment by shivansh84ya** [comment]
hey @codervivek5  Please let me know the timing for the meeting. Also, I will join the Discord server for further communication.
