### ISSUE TITLE
No Hovering Effect to Website Logo

### ISSUE THREAD

**Issue by shivnandk** [codervivek5/VigyBag#1729]
The current website logo lacks a hovering effect. This feature request is to add a hovering effect to the website logo to enhance its visual appeal and provide a better user experience. The effect should include a subtle shadow and a slight scaling to make the logo more interactive and visually engaging.

Comment
Describe the new feature or enhancement you'd like to see.
I would like to see a hovering effect implemented for the website logo. The effect should include:

A subtle shadow that appears when a user hovers over the logo.
A slight scaling effect to give the logo a sense of depth and interactivity.
Use Case
How would this feature enhance your use of the project?
This feature would improve the overall user experience by providing visual feedback when interacting with the website logo. It would make the website appear more modern and engaging.

Describe a specific use case or scenario where this feature would be beneficial.
When users hover over the website logo, the hovering effect will provide a clear indication of interactivity, making the website feel more dynamic and responsive. This can enhance brand recognition and make the site more visually appealing.

**Comment by shivnandk** [comment]
@codervivek5 sir please assign this task to me
under gssoc 2024

**Comment by codervivek5** [comment]
no need to add these type of effects
