### ISSUE TITLE
Adding social media icons 

### ISSUE THREAD

**Issue by Soumya6Tiwari** [codervivek5/VigyBag#1730]
In the footer section the "github" social media icon is missing , which is a must to be there , I would like to add it.
![Screenshot 2024-07-08 170859](https://github.com/codervivek5/VigyBag/assets/117037441/cd48acb6-a1ad-4351-8270-3bd5588310a0)
@codervivek5  kindly assign me the issue under gssoc '24

**Comment by codervivek5** [comment]
find a all the animated icons then add otherwise do not
