### ISSUE TITLE
BUG🐞: Improper Alignment in The Navbar Due to Repetitive Links

### ISSUE THREAD

**Issue by aslams2020** [codervivek5/VigyBag#1749]
Hey @codervivek5 ,

here is the Bug i encounted -
Currently, **In the navbar there is an alignment issue for "About Us" ,** This Occured **due to the repetitive links present in the Navbar.**

**Here is the issue -**
![image](https://github.com/codervivek5/VigyBag/assets/131389695/651e12f2-52b5-45d6-a71f-9b07e58bc9ec)

As you can see, in the "Products" Section all the other links are **already present.**

**And this is how it looks like after resolving -**

![WhatsApp Image 2024-07-09 at 15 10 46_53959bee](https://github.com/codervivek5/VigyBag/assets/131389695/e85c8716-d5f8-49e0-b93b-d9745cc6a9c1)

**Comment by aslams2020** [comment]
@codervivek5 please assign this issue to me

**Comment by prachi0701** [comment]
Hey @codervivek5 , please assign this to me!!
