### ISSUE TITLE
💥Implement a Feedback Form/Page for VigyBag Website

### ISSUE THREAD

**Issue by aslams2020** [codervivek5/VigyBag#1750]
Hey @codervivek5,

We need to implement a feedback form/page on the VigyBag website to gather user feedback and improve the Website services. 
The feedback form page should be accessible from the main navigation and allow users to easily provide their thoughts and suggestions.

### Here's What Will I Do 
- Form Fields **(Name, email, Rating, Feedback)**
- Will Ensure that **email field contains a valid email address.**
- **Rating must be between 1 and 5.**
- **The form will match the current website's design and aesthetics.**
- Provide a **thank you alert upon successful submission.**

Here's My Previous Work -
![image](https://github.com/codervivek5/VigyBag/assets/131389695/e79eed75-1864-4ebe-b9ce-d7b4da46c996)

Please Assign me this issue under GSSoC'24.
thankyou!

**Comment by aslams2020** [comment]
@codervivek5 I'd Like to contribute to this issue.

**Comment by aslams2020** [comment]
@codervivek5

**Comment by codervivek5** [comment]
firstly check...Maybe this page already exists if not then you can create your own.

follow the website theme color its mandatory.

**Comment by aslams2020** [comment]
> firstly check...Maybe this page already exists if not then you can create your own.
> 
> follow the website theme color its mandatory.

@codervivek5 Done!.. Please take a look

**Comment by aslams2020** [comment]
@codervivek5

**Comment by codervivek5** [comment]
sure
