### ISSUE TITLE
feature : Redesigned the login and sign up Page

### ISSUE THREAD

**Issue by SadafKausar2025** [codervivek5/VigyBag#1761]
![Screenshot (2096)](https://github.com/codervivek5/VigyBag/assets/137484958/1f666343-dbdd-4da7-91d7-d8e3cc5ea902)
![Screenshot (2097)](https://github.com/codervivek5/VigyBag/assets/137484958/9a5a8822-b961-488f-933d-e9f437e99080)

**Comment by shivansh84ya** [comment]
is this issue this is still open
