### ISSUE TITLE
💡[Feature]: Adding an AI bot

### ISSUE THREAD

**Issue by antriksh-9** [codervivek5/VigyBag#1790]
## Description
An AI chatbot can be extremely helpful and even necessary for an eCommerce website like VigyBag for several reasons:

- Chatbots can provide instant support to customers at any time, addressing common questions about products, shipping, returns, and more.
- Immediate answers to customer inquiries improve user experience.
- It can inform users about ongoing promotions, discounts, and new arrivals.
- It can provide detailed information about the materials, manufacturing processes, and environmental impact of products.
- It can guide users through the checkout process, ensuring they complete their purchases smoothly.

## Screenshots

![Screenshot 2024-05-21 013906](https://github.com/user-attachments/assets/7f700efb-4b39-4250-9b82-c518cd8fbd14)

![Screenshot 2024-06-17 164703](https://github.com/user-attachments/assets/d79421d2-dfcc-438a-82ee-bd807e191edd)

**Comment by antriksh-9** [comment]
Hey @codervivek5, I want to work on this issue. 
Please assign it to me under GSSoC '24.

**Comment by codervivek5** [comment]
Add this top of --top icon button in right

**Comment by codervivek5** [comment]
name it - VigyBot


something like this
