### ISSUE TITLE
Designing a login page

### ISSUE THREAD

**Issue by Saumya40-codes** [codervivek5/VigyBag#18]
On seeing the site, the page redirects to a non-existing login page. I want to design a login page for the same, keeping in mind the site's current structure.

GSSOC'23

**Comment by AbhishekPSingh07** [comment]
I am GSSoC'23 Contributor I would Like to Work on this Issue

**Comment by mridul45** [comment]
I would be happy to contribute to the project as I find my skills a good fit for the issue . As a GSSOC 23 member I humbly ask to allow me to contribute to the issue.

**Comment by mridul45** [comment]
I can work on some other issue or functionality in collaboration

**Comment by Gun2902** [comment]
can assign me this issue

**Comment by codervivek5** [comment]
@Saumya40-codes any update?
if you can't do it kindly give me a respond so that I can assign it to another candidate.

**Comment by Saumya40-codes** [comment]
I actually wasnt getting the preferred output thus I mentioned the same in pr section. Sorry for the delay

**Comment by codervivek5** [comment]
ok you can take your time but try to finish it soon so that the backend candidate work on it.

**Comment by Saumya40-codes** [comment]
@codervivek5 This is the final output I got, if it's ok I'll send a pr 

https://github.com/codervivek5/VigyBag/assets/115284013/2106caa1-2c96-4607-a5bd-43a0242862a8

**Comment by Saumya40-codes** [comment]
@codervivek5, this is the final output I got, if ok I'll send a pr

https://github.com/codervivek5/VigyBag/assets/115284013/8a392cc1-a3ec-4ea3-b562-e69695930e2c
