### ISSUE TITLE
SCROLL AWARE NAVBAR

### ISSUE THREAD

**Issue by ketanop321** [codervivek5/VigyBag#1827]
Adding a scroll aware navbar

**Comment by codervivek5** [comment]
Can you explain little bit more

**Comment by ketanop321** [comment]
> Can you explain little bit more

@codervivek5 
here's a video how your navbar will work⤵️

https://github.com/user-attachments/assets/ec7c02b1-36f3-4f5c-b26e-69c53d0b264f
Navbar will hide if someone starts scrolling downwards and if tries to scroll navbar will popup

**Comment by codervivek5** [comment]
no need to make navbar like this because this is an e-commerce website so we can't use this.
