### ISSUE TITLE
Footer overflows in vertical direction

### ISSUE THREAD

**Issue by Priyal208** [codervivek5/VigyBag#1829]
There is white line at the end of footer which appears , kindly aassign to me i can fix that, it looks unappealing and ruins look of whole website when scorlled down enough
![Screenshot 2024-07-15 221314](https://github.com/user-attachments/assets/ec993c92-a9b8-457e-bfc6-8e0e2cb33343)

**Comment by Priyal208** [comment]
@codervivek5 kindly assign to me

**Comment by codervivek5** [comment]
You are talking about buttom space?

**Comment by Priyal208** [comment]
Yes
