### ISSUE TITLE
feature: Redesign the whole webpage under the modern aesthetic standards.

### ISSUE THREAD

**Issue by AnkitLuhar512117** [codervivek5/VigyBag#1845]
**I am planning to implement the following features and changes to enhance the overall look and functionality of the website:**

1.when the user hover-over the navbar icons there will be the underline line which have the transition property which looks great, instead of the simple underline on hovering .

2.there is overlapping of the "wanna, help us improve " button  and the shop now button ,to prevent this , i move this button to the right hand side below the scroll-to-top button and make both them in the same alignment in one vertical line , with this approach the conflict can solve.

3.adding some css styling  and modern animation on the scroll-to-top button, which make better website standards.

4.changing all the card css styling and add transition on hovering which suite the website ("popular category" and "latest in market" section)

5.there is scroll-to-down button just below the Shop now button ,when user clicked on the button the window scroll to the "popular category" section.

6.adding smooth scrolling behaviour in both scroll-to-top button and the scroll-to-down button.

**here are the screenshot of the areas where changes are required:**

![Screenshot (889)](https://github.com/user-attachments/assets/a9b5619a-4e27-489d-967b-d58267b6f3bb)
![Screenshot (890)](https://github.com/user-attachments/assets/26d2eb0e-6410-43d0-83e3-dc60bd3bb6b8)
![Screenshot (891)](https://github.com/user-attachments/assets/3284d92a-3617-4cbe-b52f-ec1eacd0b2a4)

Assign this issue under the Gssoc'24.

**Comment by AnkitLuhar512117** [comment]
@codervivek5 assign this task under the gssoc'24 and excited to contribute in your amazing project.

**Comment by codervivek5** [comment]
@AnkitLuhar before raising your PR contact me on discord because many contributors are working on this project. 

so maybe this type of issue is already assigned or not. 

maybe conflict can occur so make sure contact with me so that i can let you know about it

**Comment by AnkitLuhar512117** [comment]
@codervivek5 should i work  on this task or not , i also join your discord channel from here i don't get any response.

**Comment by AnkitLuhar512117** [comment]
@codervivek5 and also increase the level ,i don't think it is good first issue.

**Comment by codervivek5** [comment]
Actually, VigyBag is not a project now this will go be a start so...................animations will not be good for an e-commerce store so you can find another issue to work on that and kindly do not  raise any issue for animation
