### ISSUE TITLE
In the filter section the dropdown fields z-index can be reduced so that on scroll it comes below footer.

### ISSUE THREAD

**Issue by Riddhi162** [codervivek5/VigyBag#1852]
In the filter section the z-index of dropdown field is more so when we scroll and when footer comes it goes above the footer which is an unexpected behaviour. I can fix that please assign me under GSSOC'24
![image](https://github.com/user-attachments/assets/26430bf3-1084-484f-81ab-0a2881b9305e)

**Comment by codervivek5** [comment]
some is already working in on this issue
