### ISSUE TITLE
Add mmargin from left to the heading on home page and bring it on the center also improve its font.

### ISSUE THREAD

**Issue by Riddhi162** [codervivek5/VigyBag#1855]
The font of Welcome to Viggybag can be improved also that whole div can be given some margin from left since it looks as if it has stick on the left also its font can be improved and size can be made bigger.
![image](https://github.com/user-attachments/assets/a3f3ef58-87b2-4482-a4a6-52098f08fb0b)

**Comment by codervivek5** [comment]
no need to fix it....will change the home page component later on so
