### ISSUE TITLE
Incorrect Navigation to Services Section and Missing Heading

### ISSUE THREAD

**Issue by premsaivarmachekuri** [codervivek5/VigyBag#189]
Hi @codervivek5 , I wanted to bring an issue to your attention that I have discovered while working on the VigyBag website. I believe addressing this issue will significantly improve the user experience.
## Problem

- The navigation to the "Services" section when clicked in the navbar is incorrect, leading users to the "Home" section instead of the intended section.
- The absence of a heading in the "Services" section makes the content appear messy and lacks clarity.

## Screenshots

Mobile:
![image](https://github.com/codervivek5/VigyBag/assets/110842297/2e638059-db8d-4ba6-9572-a2729be9ed97)

![image](https://github.com/codervivek5/VigyBag/assets/110842297/5128d6cd-98df-44a9-997a-26625537af76)

Desktop:
![image](https://github.com/codervivek5/VigyBag/assets/110842297/4cbf3d0a-385c-4a41-98cf-682cdeb80ffa)

## Features

- Fix the navigation issue, ensuring that clicking on the "Services" section in the navbar directs users to the correct "Services" section.
- Add a clear and prominent heading to the "Services" section for improved content organization and clarity.

### Problem

Currently, when a user clicks on the "Services" section in the navbar, it navigates them to the "Home" section instead of the intended "Services" section. This inconsistency confuses users and hampers the user experience. Additionally, the absence of a heading in the "Services" section adds to the confusion and makes the content appear messy.

### Features

1. Fix the navigation issue so that when users click on the "Services" section in the navbar, they are correctly directed to the "Services" section.
2. Add a clear and prominent heading to the "Services" section to provide clarity and structure to the content.

### Additional Information

This issue has been identified as part of the GSSOC23, and I have prior experience in successfully resolving similar issues. It is crucial to address this problem as it significantly impacts the user experience. By resolving the navigation inconsistency and adding a proper heading, users will be able to easily navigate to the desired "Services" section, resulting in an improved user experience and better content organization.

Please assign this issue to me as I will thoroughly address and resolve it, ensuring a seamless navigation experience for users.

Sincere Regards,
Premsai Varma

**Comment by yashveerdpts** [comment]
Please assign me this!

**Comment by yogeshjat23** [comment]
Please assign me this I can solve it !

**Comment by yashveerdpts** [comment]
i had seen your service bar and i am able to resolve the problem,please assign me ....

**Comment by codervivek5** [comment]
if you can fix it like responsive for each device then create PR
