### ISSUE TITLE
Make the headphones section responsive

### ISSUE THREAD

**Issue by rolikaagarwal** [codervivek5/VigyBag#19]
The headphones section is not responsive. I want to make it responsive across all screen sizes.
![image](https://github.com/codervivek5/VigyBag/assets/81984963/1cc8aaf1-cea9-4c9d-bde8-aefc74303deb)

**Comment by PatilHarshh** [comment]
Hello ,
I'm harsh. I want to work on this issue under Gssoc'23. I am really eager to work on open source projects and contribute to this community.I've taken a look at the codebase and I believe I can make some valuable improvements. I'll start working on it right away.

Skills
HTML5, CSS3, JS, Bootstrap | node js mongodb | Php, mysql | MERN | Responsive Design 

Can you please assign this issue to me.
@codervivek5

**Comment by codervivek5** [comment]
@rolikaagarwal if you cloned it already then try to clone it again so that conflict doesn't happen at PR time

**Comment by rolikaagarwal** [comment]
@codervivek5 Sure! Will do it again.

**Comment by vk20july** [comment]
@codervivek5 sir I want to do this taks under gsooc'23
