### ISSUE TITLE
Bug: The product are not separated according to navbar elements 

### ISSUE THREAD

**Issue by solanki505** [codervivek5/VigyBag#1905]
in body care , furniture ,stationary same product is shown I shall separate it according to its category so that it become easy for users to assess products 
![Screenshot 2024-07-19 094544](https://github.com/user-attachments/assets/42f62d6b-d4ff-42db-8e7a-d1ef03ebbbad)
![Screenshot 2024-07-19 094529](https://github.com/user-attachments/assets/7924efff-c69b-406f-8de6-8ba2fe197fb3)

**Comment by codervivek5** [comment]
actually, this is demo api that is reason the reason product are showing similar.

when we add real product then it will show the real one
