### ISSUE TITLE
[GSSOC'23] -  Poor UI of Footer section

### ISSUE THREAD

**Issue by VyjayantiN** [codervivek5/VigyBag#192]
Description:
The current state of the footer links in the project does not meet the desired design standards and falls short in terms of aesthetics. The links' appearance is not visually appealing and lacks consistency with the overall website design. This issue negatively impacts the overall look and feel of the footer section and hampers the user experience. To address this, it is crucial to improve the design and ensure a more visually pleasing and consistent presentation of the footer links.

Proposed Solution:
To address the issue of the unsatisfactory appearance of the footer links, the following steps are proposed:

- Design Enhancement: I will revise the styling of the footer links to improve their visual appeal and consistency with the overall website design. This may involve adjusting the font size, spacing, and color scheme to create a more harmonious and visually pleasing look.

- Consistency:  I will ensure that the design changes align with the established design standards and maintain consistency throughout the website. This will create a cohesive visual experience and reinforce the brand's identity.

**Comment by VyjayantiN** [comment]
Please assign me this issue under GSSOC'23. I would love to enhance the UI of the website.

**Comment by bilalshaikh292** [comment]
heyy is the issue Still open, I Would like to work on this issuse .
