### ISSUE TITLE
Making Page for notifications.

### ISSUE THREAD

**Issue by Saipradyumnagoud** [codervivek5/VigyBag#1937]

**Comment by Saipradyumnagoud** [comment]
@codervivek5 Please assign me the issue

**Comment by codervivek5** [comment]
where should you will add this notification.....this is already added in dashboard

**Comment by Saipradyumnagoud** [comment]
Yes in Dash Board Only after Pressing Notification option the notifications should be visible

**Comment by Saipradyumnagoud** [comment]
![image](https://github.com/user-attachments/assets/946c18fe-eae9-4935-b8e5-de721d3c36d0)



Here

**Comment by Saipradyumnagoud** [comment]
@codervivek5 Lets discuss more in the discord

**Comment by codervivek5** [comment]
be ready for meeting at near 10pm
I'll ping for meet then kindly join

**Comment by Saipradyumnagoud** [comment]
> or meet then kindly join

Yes okay
