### ISSUE TITLE
Misplaced text best seller 

### ISSUE THREAD

**Issue by whizzy23** [codervivek5/VigyBag#195]
![Screenshot 2023-05-24 195827](https://github.com/codervivek5/VigyBag/assets/129520458/533ac1e8-e1a7-4966-9db4-4b7cf4c9deae)
The text best seller is misplaced , I would to correct it as well as correct the spelling of cart 
Please assign this issue to me under Gssoc'23

**Comment by codervivek5** [comment]
also set the perfect margin
