### ISSUE TITLE
Emoji Review Section Addition in feedback

### ISSUE THREAD

**Issue by Damini2004** [codervivek5/VigyBag#1954]
![image](https://github.com/user-attachments/assets/dbdc8e18-c3e2-470f-acda-0a6a421c4ac0)

![image](https://github.com/user-attachments/assets/cf168627-73fd-41c5-8d89-39fed3e301ff)

Emoji Review Section Addition in feedback

**Comment by codervivek5** [comment]
try to use GIF / animated emoji

**Comment by Damini2004** [comment]
okay i will replace it.

**Comment by Damini2004** [comment]
![image](https://github.com/user-attachments/assets/19f53784-c378-4b86-b040-3551e7f02953)
Replace it with animated emoji kindly review it
