### ISSUE TITLE
Adding Download button to download the Private policy pdf 

### ISSUE THREAD

**Issue by Damini2004** [codervivek5/VigyBag#1956]
https://www.apple.com/in/legal/privacy/en-ww/

This website also has this feature 
Wanted to add this in your website too.

**Comment by codervivek5** [comment]
![image](https://github.com/user-attachments/assets/ffebf30e-1f45-4094-9c9d-eea29e1d1a84)
Add this line below t privacy policy content

**Comment by Damini2004** [comment]
![image](https://github.com/user-attachments/assets/e94afd13-3468-4ccc-a65a-b7ecc8f7ec1e)

Where after the Heading of Private policy or after the paragraph of private policy.
