### ISSUE TITLE
[GSSOC'23]Want to add Login page 

### ISSUE THREAD

**Issue by piyush-mahajan** [codervivek5/VigyBag#196]
hey, there I want to add a login page to the site and also want to make some changes to the page so it will become a consistent design. I am a UIUX designer and Full stack web developer,can you assign this task to me😇

**Comment by samsorrahman** [comment]
Please assign it for me

**Comment by piyush-mahajan** [comment]
thanks for assigning me😇

**Comment by codervivek5** [comment]
kindly show me the output so that I can review your change.

**Comment by piyush-mahajan** [comment]
this is the login page it also have animations😇
![login](https://github.com/codervivek5/VigyBag/assets/98900169/b9ef3fc1-2a32-46f4-b838-d42bb256a3d7)

**Comment by codervivek5** [comment]
kindly refer to this design and try make the login something like this.

https://www.figma.com/file/hXcM6chTK70O6rAqCTFxuc/VigyBag?type=design&node-id=0-1&t=EyIfRyVNlJIG31lQ-0
