### ISSUE TITLE
fixed wishlist heart and prices , fixed filter in mobile , corrected route name

### ISSUE THREAD

**Issue by SadafKausar2025** [codervivek5/VigyBag#1967]
![Screenshot (2204)](https://github.com/user-attachments/assets/a0bf0262-7034-4047-91ac-836b400f74e6)
![Screenshot (2205)](https://github.com/user-attachments/assets/89bf45bc-c148-436c-aa03-a1f2a8d247b5)

**Comment by vishanurag** [comment]
Filter issue for mobile view is already there. refer issue #1965
