### ISSUE TITLE
For fixing of the bugs in navbar and grammar error

### ISSUE THREAD

**Issue by SanaAzeem512** [codervivek5/VigyBag#1997]
for fixing of the bugs in navbar and fix the grammar ....
please assign this issue

**Comment by codervivek5** [comment]
Kindly add any screenshot so that I can understand where is the issue

**Comment by SanaAzeem512** [comment]
![Screenshot (519)](https://github.com/user-attachments/assets/9d7ec233-60a5-4a92-bb22-5e52e6d84faf)

Correct spelling in the navigation menu:

Stationary -> Stationery

**Comment by SanaAzeem512** [comment]
![Screenshot (520)](https://github.com/user-attachments/assets/9b71ebfa-954c-4442-bf21-b3ab819ae027)

In the provided screenshot, the phrase "Upto 50% Off" should be corrected to "Up to 50% Off.

**Comment by SanaAzeem512** [comment]
![Screenshot (521)](https://github.com/user-attachments/assets/025c3a3b-7ce6-43b6-a21a-084c12e60846)

Here are the necessary corrections:

"Upto 50% Off" -> "Up to 50% Off"

**Comment by codervivek5** [comment]
@SanaAzeem512  kindly find another genuine issue where you can learn something new so that you can mention it in your resume also.

I don't have any issue with assigning you but it is totally worthless
don't mind but I suggest you that find a genuine bug that you can add to your resume.

**Comment by codervivek5** [comment]
check whole landing page and also take a look of other page for typo mistake

**Comment by SanaAzeem512** [comment]
okay

**Comment by ghost** [comment]
can you please assign me this issue?
