### ISSUE TITLE
UI improvement

### ISSUE THREAD

**Issue by 7twik** [codervivek5/VigyBag#20]
I can add some on scroll animations to make the visual appeal of the website better, it will attract users and probably improve the website as a whole.
I would like to work on this issue as a part of @GSSOC'23. @codervivek5

**Comment by codervivek5** [comment]
@7twik before make design kindly tell me what you want to make changes  in UI

**Comment by 7twik** [comment]
@codervivek5 so i was planning that when we scroll down the item cards will have a fade-in effect

**Comment by codervivek5** [comment]
ok but try to make it simple so that loading time can be less
