### ISSUE TITLE
Adding My Profile Page

### ISSUE THREAD

**Issue by Saipradyumnagoud** [codervivek5/VigyBag#2006]

**Comment by Saipradyumnagoud** [comment]
@codervivek5 can you Pleaase assign me the issue

**Comment by codervivek5** [comment]
> @codervivek5 can you Please assign me the issue

its already assgned

**Comment by Saipradyumnagoud** [comment]
> > @codervivek5 can you Please assign me the issue
> 
> its already assgned

I have sent you the out put in discord can you please check @codervivek5 So that i can push
