### ISSUE TITLE
footer in mobile view

### ISSUE THREAD

**Issue by dhairyagothi** [codervivek5/VigyBag#2033]
aligning footer itms to left make it look better 

![image](https://github.com/user-attachments/assets/3e0bf638-bcfe-46e9-a1c8-3f137ee919df)

please assign me under gssoc @codervivek5

**Comment by hUnteRrooTs** [comment]
Assign this to me. I will make it

**Comment by codervivek5** [comment]
it is fine for now.... do not make any changes in footer.... maybe we'll update it later on so kindly find another issue

**Comment by hUnteRrooTs** [comment]
Can I install tailwind CSS . Because it us easy to style
