### ISSUE TITLE
Feature 🌟: Add dedicated "Licensing Page" 

### ISSUE THREAD

**Issue by Tejashri-Taral** [codervivek5/VigyBag#2045]
Hey @codervivek5 

Here is the feature request i want to implement -

To provide clear information about the licensing of the website's content and code, we need to add a dedicated "Licensing Page" that reflects the use of the MIT License.
This page will help users understand the terms under which they can use, modify, and distribute the website's resources.

****Screenshot****
![349678778-2156fb27-407b-4cc6-9ab7-8f1a3a1e14df](https://github.com/user-attachments/assets/ecb9c440-e872-4d48-a7cf-f60ef261394f)

Are you contributing under any open-source program?
GSSOC'24

I hope I was able to explain the issue and the expected solution.
If so, Could you please assign this issue to me under GSSoC 24?

**Comment by codervivek5** [comment]
this is already added
