### ISSUE TITLE
[GSSOC'23]Adding back to top button

### ISSUE THREAD

**Issue by purviporwal1812** [codervivek5/VigyBag#206]

**Comment by yellurividyendra** [comment]
i am GSSOC'23 contributor
i would like to do this issue using kotlin
so kindly assign me this issue
@codervivek5

**Comment by Lakshman4315** [comment]
Hello Sir,
I want to work on this issue.

**Comment by sagnik-p** [comment]
This issue has been inactive for a long time
I would like to work on this issue
Please assign
