### ISSUE TITLE
Bug: Navbar is blank in Mobile view 

### ISSUE THREAD

**Issue by SadafKausar2025** [codervivek5/VigyBag#2078]
In mobile the navbar must have like cart and wishlist icon to direct to cart page and wishlist page

![Screenshot (2275)](https://github.com/user-attachments/assets/8df2e2fb-c4a1-4f27-aa4f-db140142eb38)

**Comment by s-babaeizadeh** [comment]
If your navbar is blank in mobile view, start by checking your CSS media queries to ensure visibility (no display: none or visibility: hidden) and proper color contrast between the text and background. Next, verify the HTML structure, confirming correct markup with properly nested and closed tags, and the presence of any required mobile-specific elements like a hamburger menu. Inspect for JavaScript errors in the console and ensure any initialization scripts run correctly. If using a framework like Bootstrap, double-check that necessary CSS and JavaScript files are included and that you're using the appropriate responsive classes. Finally, utilize browser developer tools to inspect the navbar in mobile view, and test across different devices and browsers to identify any inconsistencies. By methodically working through these troubleshooting steps, you should be able to identify and resolve the issue with your mobile navbar

**Comment by Er-Sadiq** [comment]
is someone working on this issue if not i would like to take it

**Comment by SadafKausar2025** [comment]
> is someone working on this issue if not i would like to take it

this is done
