### ISSUE TITLE
Fixing hover effect in navbar & Font in search bar [GSSOC'23]

### ISSUE THREAD

**Issue by hereisSwapnil** [codervivek5/VigyBag#210]
I want to change the hover effect and UI of the navbar, I will also be changing the color and font style of the search bar.

![image](https://github.com/codervivek5/VigyBag/assets/85278243/f0a7252e-7034-4e87-8a15-9b96437fbb78)

![image](https://github.com/codervivek5/VigyBag/assets/85278243/63eab34b-a084-4ac7-b368-8fb3e0414473)

Please assign me this issue under GSSOC'23

**Comment by tanbirali** [comment]
@Swapnil-Singh-99 are you working on this? If not, can I work on this?

**Comment by hereisSwapnil** [comment]
@tanbirali I will be fixing the issue by tomorrow
As my Exams were going on
