### ISSUE TITLE
Adding Facebook Authentication

### ISSUE THREAD

**Issue by Ojas-Arora** [codervivek5/VigyBag#2101]
@codervivek5 I want to add Facebook Authentication to website. Kindly assign me this issue.

**Comment by codervivek5** [comment]
Let me know if you need anything for this functionality.... Test it with your credentials and after that let know... If anything need for vigybag

**Comment by codervivek5** [comment]
Let join discord for more communication

**Comment by Ojas-Arora** [comment]
@codervivek5 This authentication will just require the api keys from Firebase Console for the authentication.
