### ISSUE TITLE
Create a "Privacy Policy and terms page"

### ISSUE THREAD

**Issue by arunimaChintu** [codervivek5/VigyBag#2115]
Create and link to pages that outline the privacy policy and terms of service.

**Comment by arunimaChintu** [comment]
@codervivek5 Please assign me this issue

**Comment by SadafKausar2025** [comment]
hello @arunimaChintu 
this page is already been created
please see the website properly and bring good issues or bug

**Comment by codervivek5** [comment]
Already added
