### ISSUE TITLE
[NEW]: want to work in figma design

### ISSUE THREAD

**Issue by Ks103** [codervivek5/VigyBag#212]
As a designer and experienced in figma I want to contribute to the figma designso that it makes the website user friendly and attractive.Please assign me this task so that I can work on this project.

![Screenshot (125)](https://github.com/codervivek5/VigyBag/assets/86292101/97fa7292-c0c3-4315-90fc-8a6dcba2b8f4)

**Comment by codervivek5** [comment]
create some other pages like check out the page, payment page
