### ISSUE TITLE
Adding login and signup page (GSSOC'23)

### ISSUE THREAD

**Issue by Bharatpathak08** [codervivek5/VigyBag#213]
I would like to add login button  in home page and redirect it to new page.

**Comment by GleanCoder** [comment]
hey @codervivek5 ,  I saw your Figma Design and I am interested to make login page of your website 

![2023-05-25](https://github.com/codervivek5/VigyBag/assets/121458753/bf89ff49-58b2-4fcd-a73d-d4dae0c0a90b)

**Comment by codervivek5** [comment]
@Bharatpathak08 
try to make these pages with same as the Figma design. you can get the design from the readme file.
