### ISSUE TITLE
Making a django app within the Django project

### ISSUE THREAD

**Issue by Saumya40-codes** [codervivek5/VigyBag#218]
Making a Django app named "VigyBag" within the Django Project and shifting HTML and CSS files that follow the proper django structure.

I've made projects using Django and will be to do this.

**Comment by Saumya40-codes** [comment]
![image](https://github.com/codervivek5/VigyBag/assets/115284013/ef9ca51a-bc00-45fb-b165-9ad93c15f900)


there is also no manage.py file in the backend folder

**Comment by codervivek5** [comment]
i have update it so you can clone it again and create proper apps for development.

**Comment by Saumya40-codes** [comment]
> i have update it so you can clone it again and create proper apps for development.

is there any specific app name I have to follow?

**Comment by codervivek5** [comment]
make app name with some complex page like home,
contact, checkout,
payment


so that it will be easy to other person

**Comment by Saumya40-codes** [comment]
![image](https://github.com/codervivek5/VigyBag/assets/115284013/b0a5f2a5-9b5d-4867-8a1a-49e6b9383380)

Is this structure proper?

**Comment by codervivek5** [comment]
Yeah, this is proper structure.

**Comment by Saumya40-codes** [comment]
I am done with the file structure. Should I add/copy current HTML and CSS files in this, or will that be done afterward?

**Comment by davideke1** [comment]
I have done the app for the project. 
![image](https://github.com/codervivek5/VigyBag/assets/63519479/5fde353b-5b89-43b9-b7dd-2e117eb5ba66)

**Comment by davideke1** [comment]
https://github.com/codervivek5/VigyBag/assets/63519479/aee47c89-68b5-425e-985f-21e7ad6d717b

preview
