### ISSUE TITLE
Categorising products according to sections

### ISSUE THREAD

**Issue by techy4shri** [codervivek5/VigyBag#2180]
Catalouging products as per the different sections/pages we have on the website to make it easier for the user to navigate and only see what they opened. No unnecessary listing.
Will remove any product from the section not related to it.
Catalogue products section wise.
Enhance UX and overall mapping.

Kindly assign me this under GSSOC.

**Comment by codervivek5** [comment]
Tomorrow is the last day so if possible try to raise your PR before 7pm so that you can get your points

**Comment by techy4shri** [comment]
> Tomorrow is the last day so if possible try to raise your PR before 7pm so that you can get your points

Will do!
