### ISSUE TITLE
Icons Not loading in feedback page

### ISSUE THREAD

**Issue by vasudhawaman** [codervivek5/VigyBag#2246]
![Screenshot (731)](https://github.com/user-attachments/assets/c55693f9-18b0-4fe7-b20c-4ec3773279a1)

**Comment by vasudhawaman** [comment]
Can you assign me this issue?

**Comment by sweta123761** [comment]
you can assign me this issue. i will fix that issue

**Comment by TornovDutta** [comment]
I hope this message finds you well. I would like to formally request to be assigned to the issue regarding the implementation of a "No products found" message for filtered product results.
@sanjay-kv

**Comment by sanjay-kv** [comment]
@codervivek5 gssoc-ext , hacktoberfest-accepted label is missing,

hacktoberfest you just need to add in the topic session
