### ISSUE TITLE
Navbar Getting Fixed at Top 

### ISSUE THREAD

**Issue by Archisman141** [codervivek5/VigyBag#2283]
![Screenshot_20241009_091717_Chrome.jpg](https://github.com/user-attachments/assets/7c40d65b-3bad-44ec-8f0a-06dd687cfb69)

The navbar is getting fixed on the top and not showing the content of the page. I can solve this issue.

@codervivek5 Please assign me this issue. Please add gssoc-ext and hacktober-accepted labels.

**Comment by Archisman141** [comment]
@codervivek5 Can you assign the level for this issue

**Comment by codervivek5** [comment]
> @codervivek5 Can you assign the level for this issue

I have assigned you... You can start contributing

**Comment by Archisman141** [comment]
@codervivek5 Ok, thanks you for assigning me

**Comment by Archisman141** [comment]
@codervivek5 I have fixed the navbar issue please merge it

**Comment by Archisman141** [comment]
@codervivek5 please merge my PR

**Comment by xenomancy** [comment]
@codervivek5 i have a solution for this please assign to me so that i could fix this

**Comment by Archisman141** [comment]
@codervivek5 Please sir merge my PR
