### ISSUE TITLE
FIXING THE HEADER SECTION AS IT IS VERY BASIC

### ISSUE THREAD

**Issue by Shashwat0227** [codervivek5/VigyBag#23]

**Comment by SamridhiNancy** [comment]
"Hi there! I'm excited to contribute to this project'GSSOC;'23 I've taken a look at the codebase and I believe I can make some valuable improvements. I'll start working on it right away. If you have any specific requirements or suggestions, please let me know. Looking forward to collaborating with you all on this!

**Comment by Shashwat0227** [comment]
> 
bro lol i have made this issue , let me do the work if it gets under gssoc

**Comment by VishalVinayRam** [comment]
bro i woul like to do this since there is no update
