### ISSUE TITLE
NAVBAR FIX [ENHANCEMENT]

### ISSUE THREAD

**Issue by PR1YAM9** [codervivek5/VigyBag#240]
HI @codervivek5 
I would like to fix the navbar for all media widths as it is not responsive at all and is bad for User Experience.
**Reference to issue **
<img width="146" alt="image" src="https://github.com/codervivek5/VigyBag/assets/92604300/fb582f0e-1e60-4388-a7aa-30e0efaf1ba1">

I am also providing a reference image of the navbar from my previous projects which is 100% responsive for all media widths.

<img width="146" alt="Screenshot 2023-05-24 023841" src="https://github.com/codervivek5/VigyBag/assets/92604300/04699e06-34a2-4197-99de-f5be3dab9852">

<img width="149" alt="Screenshot 2023-05-24 023922" src="https://github.com/codervivek5/VigyBag/assets/92604300/7adfb662-31b8-4174-836a-636f8737a026">

I will add a better navbar keeping the theme of the web page in mind. Please assign me this issue under GGSOC 23'
Regards Priyam Maini

**Comment by codervivek5** [comment]
make it for mobile resposive
