### ISSUE TITLE
create clothing/accessories page

### ISSUE THREAD

**Issue by ManaswiKasiraju** [codervivek5/VigyBag#247]
I would like to create a webpage for clothing and accessories.

1. women
2. men
3. kids
I'll create a page for showing the categories in which a person wants to shop.

I'm a GSSOC'23 contributor.
Please assign me under the label gssoc'23.

**Comment by codervivek5** [comment]
try to fix all the section and add these section

**Comment by ManaswiKasiraju** [comment]
Ok sir
Thank you.
When is the deadline to submit sir?

**Comment by codervivek5** [comment]
you can make PR as soon as possible but it bug-free.

so you can take your time and patience.

**Comment by bilalshaikh292** [comment]
Heyy is the issue still open ? I would Like to Contribute.
