### ISSUE TITLE
[Bug] fix bug of home page. 

### ISSUE THREAD

**Issue by codervivek5** [codervivek5/VigyBag#256]

**Comment by PoulavBhowmick03** [comment]
I would like to fix the home page orientation and everything, if assigned @codervivek5

**Comment by sampadatiwari30** [comment]
I have a experience for this and i'm good at bug fixing please assign me @codervivek5

**Comment by bilalshaikh292** [comment]
Heyy is the issue still open ? I would Like to Contribute.

**Comment by ParthMadhvani2** [comment]
hey, can you please assign this issue to me as I am GSSoC'23 contributor.

**Comment by codervivek5** [comment]
hello @PoulavBhowmick03 , 
any update...if you are not able to it kindly inform me or you are woring then also inform me  othewise I have to assign to another candidate

**Comment by PoulavBhowmick03** [comment]
> hello @PoulavBhowmick03 , 
> any update...if you are not able to it kindly inform me or you are woring then also inform me  othewise I have to assign to another candidate 

I believe this issue was fixed along with other PRs, if there's anything more to be done, you can assign this to someone else
