### ISSUE TITLE
Add the ABOUT section on website

### ISSUE THREAD

**Issue by Meenal21i** [codervivek5/VigyBag#257]
I want to add the about section. Please assign me this issue under GSSOC'23.

**Comment by codervivek5** [comment]
try to refer figma from readme and use that color code

**Comment by yaten2302** [comment]
Hi @codervivek5, could you please assign this issue to me because no PR has been created for this issue since 2 weeks.

Please assign this issue to me under GSSOC'23, I have understood the issue and will quickly create the PR for this once you assign it to me 🙏

**Comment by bilalshaikh292** [comment]
heyy Can I work On this Issue
