### ISSUE TITLE
aligning the page layout and making it responsive and removing hte need of horizontal scrollbar

### ISSUE THREAD

**Issue by mridulsaggi** [codervivek5/VigyBag#258]
pls assign me this issue as i am interested in contributing towards this project by enhancing the ui and improving the css
issue example:
![image](https://github.com/codervivek5/VigyBag/assets/91930535/56cf7e97-8995-4aee-8021-fc865a77d2f6)

**Comment by iamparas0** [comment]
Please assign me this project i will make it responsive and make it adjustable to auto with respect to device size.
