### ISSUE TITLE
Creating Contact Us page

### ISSUE THREAD

**Issue by SasiVardhan247** [codervivek5/VigyBag#26]
@codervivek5 Can you assign this to me.

**Comment by SamridhiNancy** [comment]
"Hi there! I'm excited to contribute to this project'GSSOC;'23 I've taken a look at the codebase and I believe I can make some valuable improvements. I'll start working on it right away. If you have any specific requirements or suggestions, please let me know. Looking forward to collaborating with you all on this!

**Comment by Sadhana-Panthi** [comment]
I'm a contributor for GSSoC '23. Please, assign me an issue.

**Comment by codervivek5** [comment]
try to refer Readme file design

**Comment by tayyab-ilyas** [comment]
hey @codervivek5 can you assign this to me if nobody else is working on it?
