### ISSUE TITLE
Home page `Not Centered`

### ISSUE THREAD

**Issue by SyedImtiyaz-1** [codervivek5/VigyBag#261]
Hello @codervivek5 ,
Issue regarding the `Home Page`.

I have a request that please don't merge unless `PR` because this issue occurs by one of contributor which is in GSSoC23 so I think you must check and run the code before merge because it's spoiling the website and the `codebase`

## Screenshot - 
![Screenshot from 2023-05-26 23-43-48](https://github.com/codervivek5/VigyBag/assets/121503426/d4bce322-08e6-46fb-8662-35eed1da941a)

**Comment by sampadatiwari30** [comment]
I want to make the home page attractive, same as you shared and professionally please assign me this issue under GSSOC'23.

**Comment by SyedImtiyaz-1** [comment]
I already raised a `PR`

**Comment by codervivek5** [comment]
Try to fix it as soon as possible

**Comment by SyedImtiyaz-1** [comment]
It already fixed check the PR #279 
Merge this one it will fix all of  the website issue 👍🏻 
& a request please review the code before merging in GSSoC here are some freshers who raise not reponsive PR or irrerlative css that cause web structure alignment damage.
