### ISSUE TITLE
All the sections of the website are distorted 

### ISSUE THREAD

**Issue by PoulavBhowmick03** [codervivek5/VigyBag#275]
I want to fix the home page, which looks like this on PC
![image](https://github.com/codervivek5/VigyBag/assets/133862694/3d728ce5-1e29-4465-80e7-c263ec3b30be)

**Comment by PoulavBhowmick03** [comment]
@codervivek5 please look into this

**Comment by codervivek5** [comment]
After solve this issue kindly drop a message in discord and mention me also

**Comment by PoulavBhowmick03** [comment]
Sure!
