### ISSUE TITLE
Feature : Dark Mode

### ISSUE THREAD

**Issue by parasss19** [codervivek5/VigyBag#282]
### Current 
No dark theme available

### Change 
I can apply dark theme for better UI

## Work Sample (its just a sample i will make it more better)

https://github.com/codervivek5/VigyBag/assets/101205226/241f640c-19f1-44b0-99f7-3afc3935f8a1

## I want to work on this issue please assign me this

**Comment by parasss19** [comment]
Hii @codervivek5 Please review my issue once

**Comment by bilalshaikh292** [comment]
heyy @parasss19 I would Like To work on this issue ?

**Comment by codervivek5** [comment]
Can i see your changes

**Comment by bilalshaikh292** [comment]
yes sure
