### ISSUE TITLE
Add To Cart Functionality

### ISSUE THREAD

**Issue by Satyam0204** [codervivek5/VigyBag#29]
Hello @codervivek5, I am Satyam Pattanaik, a contributer in GSSOC 23', I want to make a fuctional add to cart feature the website for the ease of users'.
Please assign this to me, as i would love to contribute to this project.
Thankyou

**Comment by samsorrahman** [comment]
Sir I would like to work on it as a GSSOC23 contributer

**Comment by samsorrahman** [comment]
Thanks Sir for Assigning to me @codervivek5
