### ISSUE TITLE
Website is not `Responsive`

### ISSUE THREAD

**Issue by SyedImtiyaz-1** [codervivek5/VigyBag#290]
Hello @codervivek5 ,
Working on this too, assign me this and I'll make the website responsive for all the Devices.

### Currently it is working smoothly on Laptop and the Big Screens.
I'll make responsive the website as per the `Tablets and Mobile Phones`

### Soon will raise the optimize **PR**

**Comment by techmannih** [comment]
i can help with this issue.

**Comment by techmannih** [comment]
Hiiii @codervivek5 , 
I want to work on this issue.. please assign me the same
I'll make responsive of this website for all the Devices .
