### ISSUE TITLE
Adding LinkedIn Link in the footer section

### ISSUE THREAD

**Issue by Abhi200206** [codervivek5/VigyBag#293]
Adding LinkedIn Link in the footer under social connection section
<br>
<img width="950" alt="Screenshot 2023-05-29 145647" src="https://github.com/codervivek5/VigyBag/assets/120104020/f339f6ac-7707-41ba-b5d8-247abb3a0bdd">

**Comment by shellyverma** [comment]
Hey @codervivek5,I would like to add LinkedIn Link in the footer under social connection section.
I'm a contributor to GSSOC'23 please assign this issue to me as a part of GSSOC'23
