### ISSUE TITLE
Add YouTube link in the Social connection under footer section

### ISSUE THREAD

**Issue by Abhi200206** [codervivek5/VigyBag#296]
Add YouTube link in the social connection section. By including the YouTube Link in the Social connection section the YouTube Channel is accessible to all.
<br>
<img width="950" alt="Screenshot 2023-05-29 145647" src="https://github.com/codervivek5/VigyBag/assets/120104020/008592cf-8684-4c10-a1d9-07e489db34f4">

**Comment by Gyanthakur** [comment]
Please assign me under SSOC2023

**Comment by Gyanthakur** [comment]
#342  Youtube Link was added
<img width="895" alt="Screenshot 2023-06-05 143128" src="https://github.com/codervivek5/VigyBag/assets/98226958/a1fbacd3-063f-473d-91bc-a4b5e0cc73ce">
