### ISSUE TITLE
Login form is not responsive

### ISSUE THREAD

**Issue by akshaymundra** [codervivek5/VigyBag#301]
login form got distorted for smaller screens (for screen size less then 480px)

![image](https://github.com/codervivek5/VigyBag/assets/73519056/bc607df9-3103-46f0-9c95-e74ce627b445)

**Comment by priyanshu942** [comment]
I'm a GSSoC contributor ..
I would like to work on this section...

would you please assign me to this task ??

**Comment by ajit1219** [comment]
hello @Akshay272003 , I love to make websites responsive and device friendly by using Flexbox and media query. can you please assign this task to me?
Waiting for your response!!
Thank you!!
