### ISSUE TITLE
The item menu list is not scrollable so I would like to implement the same 

### ISSUE THREAD

**Issue by streetstylecoder** [codervivek5/VigyBag#304]
![Screenshot 2023-05-30 at 10 57 10 AM](https://github.com/codervivek5/VigyBag/assets/89967721/75d91aff-ffd1-4ff1-986b-191fbc87a986)
I would like to make this flexbox scrollable horizontally as a part of gssoc'23

**Comment by priyanshu942** [comment]
I'm a GSSoC contributor ..
I would like to work on this section...

would you please assign me to this task ??
