### ISSUE TITLE
Use of Django for Backend

### ISSUE THREAD

**Issue by tarun-hegde** [codervivek5/VigyBag#31]
@ImgBotApp @codervivek5 @Babunshil please assign me this issue as i could shift the codebase to django and build on the project using Django's Class Based Views and implement Authentication,Authorization,Registration

**Comment by Akshayp02** [comment]
hello sir i would like to hands in this task to resolve it am experience with Django i can implement User Account section such Registration, login, Logout and much more. i'm actively gssoc'23 Contributor.

**Comment by Babunshil** [comment]
> @ImgBotApp @codervivek5 @Babunshil please assign me this issue as i could shift the codebase to django and build on the project using Django's Class Based Views and implement Authentication,Authorization,Registration

no need to tag me, I am also a contributor brother , I have just contribute on this project at starting
