### ISSUE TITLE
Icons and Images needed to be fixed

### ISSUE THREAD

**Issue by Nikita110602** [codervivek5/VigyBag#312]
The icons are going out of the section and images are needed to be fixed.
make more attractive design and icons.
![Screenshot (33)](https://github.com/codervivek5/VigyBag/assets/111515819/dd8d9b34-97cf-4106-9ba0-5b9673cbbffc)

**Comment by priyanshu942** [comment]
I'm a GSSoC contributor ..
I would like to work on this section...

would you please assign me to this task ??

**Comment by khushiminda** [comment]
As a ui/ux designer i want to change your nav bar and make it more aethetic and more animated
i can add cool animation effects in any language you want
pls let me a try
i am eager to make it improved
