### ISSUE TITLE
There is same image all over the buy section

### ISSUE THREAD

**Issue by Nikita110602** [codervivek5/VigyBag#314]
There is same image all over the buy section that is not looking good.
![Screenshot (34)](https://github.com/codervivek5/VigyBag/assets/111515819/bc036344-cd41-4c45-beb3-6f8ab7619b1d)

**Comment by Sonikm** [comment]
Please assign this issue to me, I would like to work on it.

**Comment by Programmer0909** [comment]
This issue can easily be tackled by rendering few different images from the image folder rather that rendering the same image again and again as done in line 153, 190 , 227 , 264 and 301 . I would be grateful to you if you let me work on this project.

**Comment by abhradip-saha** [comment]
i would like to work on this issue
