### ISSUE TITLE
Building see more page

### ISSUE THREAD

**Issue by ePSA-eJya** [codervivek5/VigyBag#315]

**Comment by ojaswi18** [comment]
I would like to work on this issue. When clicked on see more,user will be taken to a new section displaying the list of all the related items.

**Comment by JigarJoshi04** [comment]
Please go ahead @ojaswi18 
Thanks

**Comment by ePSA-eJya** [comment]
> Please go ahead @ojaswi18 Thanks

I had opened this issue @JigarJoshi04

**Comment by ePSA-eJya** [comment]
> > Please go ahead @ojaswi18 Thanks
> 
> I had opened this issue @JigarJoshi04

Please assign it to me. @JigarJoshi04

**Comment by gurjeetsinghvirdee** [comment]
Bro what are you doing 
how can you assign to others in someone else issue @JigarJoshi04

**Comment by codervivek5** [comment]
@ePSA-eJya  now  you can go ahead but before work on it kindly contact to me once ......what changes you want to add or anything else
