### ISSUE TITLE
enhancing ui of signup page

### ISSUE THREAD

**Issue by mridulsaggi** [codervivek5/VigyBag#322]
the sign up  button is not properly  aligned and lacks margin and padding.
i would like to work on it and add border padding margin and alignment.
pls assign me the issue under gssoc
![image](https://github.com/codervivek5/VigyBag/assets/91930535/1ba6e77a-b2b1-4baa-9a41-bb0c6bfd5e02)

**Comment by sakshimaluskar2** [comment]
We can enhance ui of sign up page with using css styling. I would like to work on this issue usnder GSSoC '23 . Plaease assign me this issue.
