### ISSUE TITLE
improving ui of navbar

### ISSUE THREAD

**Issue by mridulsaggi** [codervivek5/VigyBag#324]
the hover effect is not clearly visible at the navbar and missing alignment and borders.

pls assign me this issue as i would like to contribute to this project under gssoc and enhance the ui

**Comment by khushiminda** [comment]
As a ui/ux designer i want to change your nav bar and make it more aethetic and more animated
i can add cool animation effects in any language you want
pls let me a try 
i am eager to make it improved
