### ISSUE TITLE
SignUp button in the navBar  section..

### ISSUE THREAD

**Issue by Badshah1508** [codervivek5/VigyBag#328]
hey @codervivek5 

I'm a GSSoC contributor ..
I would like to work on this section...

would you please assign  me to this task ??

**Comment by priyanshu942** [comment]
I'm a GSSoC contributor ..
I would like to work on this section...

would you please assign me to this task ??

**Comment by aditi-chaurasia** [comment]
Please assign this task to me for adding signup button in navbar.
