### ISSUE TITLE
Create APIs for user authentication 

### ISSUE THREAD

**Issue by sanya-mahajan** [codervivek5/VigyBag#34]
Create register/login/logout endpoints using django rest framework

**Comment by Rishi2602** [comment]
It can be easily implemented by sending http requests from the react frontend to api endpoint through Django rest framework with class based api that will be appropriate for it. I would like to work on this project as a GSSoC'23 contributor.Please Assign me on it.

**Comment by sanya-mahajan** [comment]
I've proposed this issue as am a contributer myself
