### ISSUE TITLE
Improve the UI of testimonial section

### ISSUE THREAD

**Issue by shruti8302** [codervivek5/VigyBag#345]
![Screenshot (446)](https://github.com/codervivek5/VigyBag/assets/93856491/2248696c-fa1f-4083-8f78-27f26764cd65)
As a part of GSSOC'23, I would like to improve the testimonial section of the website. Kindly assign this issue to me.

**Comment by Annany2002** [comment]
I can design a better UI for the testimonials section . I would ask you to assign the issue to me...
