### ISSUE TITLE
Add a "Scroll to Top" floating button [FEATURE]

### ISSUE THREAD

**Issue by harshitakaushik-dev** [codervivek5/VigyBag#35]
Hello,
As one can observe by viewing the website, the "scroll to top" button is missing. 
By addition of this feature, we can enhance the user experience as they will not have to scroll all the way up of the entire page and can reach home with just a click at the floating button.

I'd love to work on adding this functionality and have added it in my personal projects as can be see in my GitHub repos. 
Please assign this issue to me as GSSoC 2023 contributor ! 
Thank you :)

**Comment by sanketsaurav2411** [comment]
Hi @codervivek5 . I would like to give a shot at fixing this issue as well. Could you assign this to me as well under GSSOC'23?

**Comment by codervivek5** [comment]
another candidate is also working on a similar to this issue so at this time I cant assign it to you.
