### ISSUE TITLE
[GSSOC'23]- Improper Styling of Product Container

### ISSUE THREAD

**Issue by VyjayantiN** [codervivek5/VigyBag#353]
I wanted to bring to your attention an issue related to the styling of the product container on our website. Currently, the logos and overall design of the container are not visually appealing or catchy, which may impact the user experience.

As a team member with a keen eye for design and aesthetics, I would like to contribute by suggesting improvements to enhance the style of the product container. I believe that a visually appealing and attractive design can significantly impact the user's perception of our products and increase engagement. I would like to update the design of this section.

**Comment by VyjayantiN** [comment]
Please assign me this issue under GSSOC'23.

**Comment by priyanshu942** [comment]
Please assign me this issue under GSSOC'23.

**Comment by VyjayantiN** [comment]
@codervivek5 
Please look into it!!
