### ISSUE TITLE
Backend for product

### ISSUE THREAD

**Issue by ojaswi18** [codervivek5/VigyBag#367]
I would like to code backend for the product ,will be using Django framework for the same. The database will store the image, location, name, price and the rating. 
Please assign this issue to me @codervivek5

**Comment by mridul45** [comment]
@codervivek5  I would really like to work on the issue as a GSSOC contributor.

**Comment by JigarJoshi04** [comment]
Purely on first come basis, I'm assigning this to @ojaswi18 
Please keep contributing @mridul45
