### ISSUE TITLE
Improving Signup Card of Login Page

### ISSUE THREAD

**Issue by akankshachanana1** [codervivek5/VigyBag#371]
The login page's Sign Up card is currently out of alignment.I'd want to work on this problem.

https://github.com/codervivek5/VigyBag/assets/127978268/2a950358-4ed4-4fff-8532-50845abe04c0

**Comment by thezeeshann** [comment]
Hi, @akankshachanana1  I would like to work on this project. Please assign me.

**Comment by akankshachanana1** [comment]
please assign it to me

**Comment by codervivek5** [comment]
Try to fix bug like this is not looking good.
Then i will merge your PR
