### ISSUE TITLE
Add Launcher Icon to VigyBag Android

### ISSUE THREAD

**Issue by javaman97** [codervivek5/VigyBag#377]
## A launcher icon is a graphic that represents your app to users.

_**I will add the Launcher Icon to our VigyBag Android App from one of the mentioned below shapes**_ 
### Different Shapes of Launcher Icon 

![launcer_square](https://github.com/codervivek5/VigyBag/assets/75328768/c5040100-af18-4b14-bfc8-c81b3dd4f818)
**Square**
![launcher_circle](https://github.com/codervivek5/VigyBag/assets/75328768/bd7e53a1-9eb7-4883-9329-0ba6f84cbea1)
**Circle**
![launcer_rectangle_wide](https://github.com/codervivek5/VigyBag/assets/75328768/973e7b49-fd31-4572-a827-5a23802b518c)
**Wide Rectangle**
![launcer_rectangle](https://github.com/codervivek5/VigyBag/assets/75328768/f3346f0d-fb4a-4f5a-b4fc-352a00bc5ea3)
**Tall Rectangle**

**Comment by javaman97** [comment]
@codervivek5 Pls assign me this issue.

**Comment by 07jasjeet** [comment]
Have a go @javaman97!

**Comment by Cyclotron17** [comment]
please assign me this issue

**Comment by 07jasjeet** [comment]
> please assign me this issue

Hello, this issue is already assigned to someone. Please refer to my previous comment in order to get started.
