### ISSUE TITLE
Want to align Product Container properly

### ISSUE THREAD

**Issue by DeveloperAshish8** [codervivek5/VigyBag#385]
The website is not responsive for laptop screen as well.
The current project container looks distorted like the fashion and accessories icons and more are overflowing with hero section.

Want to enhance the distortion issue and responsiveness for desktop screen that is remove overflow issue

**Comment by DeveloperAshish8** [comment]
Please assign me this issue @codervivek5

**Comment by codervivek5** [comment]
try to remove the bottom scroll bar and reduced the size of the product.....if you can add a carousel effect on the product then you can use it.

In a single line there will be 5 products so remember it. you can reduce the product size as much you want but add 5 products in a single line

**Comment by akanksha984** [comment]
Please assign it to me under gssoc'23. I want to work on it

**Comment by akanksha984** [comment]
@codervivek5 it is done already..
