### ISSUE TITLE
Setting up Retrofit

### ISSUE THREAD

**Issue by essy16** [codervivek5/VigyBag#386]
I want to set up the Retrofit together with the clean architecture and MVVM

**Comment by 07jasjeet** [comment]
Hello @essy16, We are currently implementing the UI part for Android. I'm open to what you're suggesting only if you know what API's are at play in the backend. For now if you'd like to work on UI, let me know, there's ton of stuff to do.

**Comment by essy16** [comment]
Hello @07jasjeet I am willing to work on the UI part just tell me what needs to be done 
I will work on the retrofit part once everything is sorted out

**Comment by 07jasjeet** [comment]
@essy16 This [Figma link](https://www.figma.com/file/NSzGo2uHvqgq4aruqRc5Jf/VigyBag%3A-Android-App?type=design&node-id=1-2) is what we want the design to be. Currently another contributor is working on the login section issue #70, so I think you may as well pick up the home section or even create your own Figma file if you want.

**Comment by Cyclotron17** [comment]
Hey there I want to work on setting up Retrofit , please assign me this issue

**Comment by 07jasjeet** [comment]
> Hey there I want to work on setting up Retrofit , please assign me this issue

Hello @Cyclotron17, as I've said above, we would like to work on the UI part first and then move to Retrofit calls. For now you can either take up some UI work by looking at the website or set up dependency injection (should be quick work). Make an issue for whatever you like.

**Comment by Cyclotron17** [comment]
I'd like to setup dependency injection

**Comment by essy16** [comment]
Hello @07jasjeet I had previously requested to work on Retrofit using clean architecture

**Comment by 07jasjeet** [comment]
@essy16 I replied to you earlier that right now we are going to focus on UI only. You can create a new ticket for that purpose as stated above. I'm not going to assign this ticket to anyone until then.
