### ISSUE TITLE
Addition of auto-comment.yml file

### ISSUE THREAD

**Issue by DivyanshiNarang** [codervivek5/VigyBag#390]
We need to add an auto-comment.yml that will automatically welcome, greet and provide necessary information to the contributors when they create new issues, PR, and when these will get assigned or merged respectively. This will promote motivation and performance

@codervivek5  
Please assign me this issue under gssoc'23

**Comment by abhinav-m22** [comment]
Hey @codervivek5 
I want to work on this issue if it is inactive.
Please assign me the same

**Comment by DivyanshiNarang** [comment]
Hello @abhinav-m22 I am working on this.

**Comment by codervivek5** [comment]
@DivyanshiNarang sure ...you can continue 👍
