### ISSUE TITLE
Adapt Navhost for Navigation in VigyBag App

### ISSUE THREAD

**Issue by javaman97** [codervivek5/VigyBag#398]
## I will make the navigation using Navigation graphs for easy navigation.
**Using Official references as suggested:-**
 _https://developer.android.com/guide/navigation/get-started#add-navhost_

**Comment by javaman97** [comment]
@07jasjeet Please assign me this issue

**Comment by essy16** [comment]
Hello @javaman97 Are you making Navigation through JetPack Compose?

**Comment by 07jasjeet** [comment]
@javaman97 have a go!

**Comment by 07jasjeet** [comment]
@essy16 its in XML but you can do compose as well.

**Comment by essy16** [comment]
@07jasjeet I have seen the project is in Jetpack compose...Hence I assume it will be that

**Comment by 07jasjeet** [comment]
@essy16 it can be both actually.

**Comment by essy16** [comment]
How?

**Comment by 07jasjeet** [comment]
@essy16 https://developer.android.com/jetpack/compose/migrate/interoperability-apis
