### ISSUE TITLE
WANT TO ADD THIS JS FEATURE IN WEBSITE TEXT

### ISSUE THREAD

**Issue by Sushilverma002** [codervivek5/VigyBag#403]
IT MAKE OUR WEBSITE MORE ATTRACTIVE AND CLASSIC

HERE I PUT vedio also. please check this out 

https://github.com/codervivek5/VigyBag/assets/114687502/56930f1e-9eb6-45c1-8495-9a9bcbe3b6c3

**Comment by codervivek5** [comment]
perfect.....raised PR for this issue if you solved it.

**Comment by Sushilverma002** [comment]
PR added please check out.
