### ISSUE TITLE
[GSSOC'23] -- Adding a scroll to top button

### ISSUE THREAD

**Issue by VyjayantiN** [codervivek5/VigyBag#412]
**Issue Description:**
 I would like to suggest on having a "scroll to top" option available to easily navigate back to the top of the page. Currently, when I scroll down the webpage, I have to manually scroll back up, which can be inconvenient and time-consuming, especially on long pages. @codervivek5 Please assign me this issue.

**Expected Outcome:**
When implemented, the "scroll to top" option will provide a convenient way for users to quickly return to the top of the webpage with a single click or tap. This feature will enhance the user experience by improving the accessibility and usability of the website.

**Proposed Solution:**
To address this issue, we can add a scroll-to-top button or a similar UI element that remains fixed on the page. When the user clicks or taps on the button, the page will smoothly scroll back to the top, allowing for easy navigation. The button should be easily visible and accessible to users as they scroll down the page.

**Comment by vintech05** [comment]
I'm interested, could you please assign me this issue?

**Comment by akanksha984** [comment]
Please assign it to me under gssoc'23. I want to work on it
