### ISSUE TITLE
[GSSOC'23] - Poor UI of Testimonial Section

### ISSUE THREAD

**Issue by VyjayantiN** [codervivek5/VigyBag#414]
**Issue Description:**
The heading of the testimonial section is mixing with the user's message, resulting in a poor user interface (UI) experience on the live website. This issue needs to be addressed to ensure clear visual separation between the heading and the user's message within the testimonial section. @codervivek5 Please assign this issue to me.

![image](https://github.com/codervivek5/VigyBag/assets/106438430/1496ae0e-4c69-4e18-94a9-a273056b06ee)

**Expected Outcome:**
After resolving this issue, the testimonial section should have a visually appealing and user-friendly UI. The heading should be properly positioned and distinct from the user's message, allowing for better readability and comprehension of the testimonials.

**Proposed Solution:**
 By modifying margins, padding, and other relevant CSS properties, the testimonial section can be improved for better readability and a more user-friendly experience. Thorough testing should be conducted across different devices and browsers to ensure consistent and satisfactory results.

**Comment by akanksha984** [comment]
Please assign it to me under gssoc'23. I want to work on it
