### ISSUE TITLE
login page is not found ,i can make a login page 

### ISSUE THREAD

**Issue by Meenakshiratnawat** [codervivek5/VigyBag#42]
I can fix this issue ,So under GSSOC 23' , I request you to please assign the task to make a login page to me .
Thank you !

**Comment by sanketsaurav2411** [comment]
Hi @codervivek5 . I would like to give a shot at fixing this issue as well. Could you assign this to me as well under GSSOC'23?

**Comment by codervivek5** [comment]
another candidate is also working on a similar to this issue so at this time I can't assign it to you. if they are not able to do I will open this issue again.
