### ISSUE TITLE
Contact Us Footer Issue

### ISSUE THREAD

**Issue by SyedImtiyaz-1** [codervivek5/VigyBag#429]
Hello @codervivek5 ,
Here is a issue regarding contact us page - 
![Screenshot from 2023-06-21 20-02-40](https://github.com/codervivek5/VigyBag/assets/121503426/97874507-8687-4e44-8718-49148986f4a8)

### Working on this

**Comment by codervivek5** [comment]
What changes you want to make on it .......plz explain little bit
