### ISSUE TITLE
Cards are missing Hover effect its look not good

### ISSUE THREAD

**Issue by venkataraviraja5** [codervivek5/VigyBag#43]
please assign to me i will work on this issue

**Comment by PatilHarshh** [comment]
Hello ,
I'm harsh. I want to work on this issue under Gssoc'23. I am really eager to work on open source projects and contribute to this community.I've taken a look at the codebase and I believe I can make some valuable improvements. I'll start working on it right away.

Skills
HTML5, CSS3, JS, Bootstrap | node js mongodb | Php, mysql | MERN | Responsive Design 

Can you please assign this issue to me. @codervivek5

**Comment by venkataraviraja5** [comment]
@PatilHarshh Am not a admin bro.....i just raised a issue and am waiting for admin response
