### ISSUE TITLE
On boarding Screens 

### ISSUE THREAD

**Issue by essy16** [codervivek5/VigyBag#443]
Umh I also want to work on this area but I also have a suggestion the Android UI of this app is rather not pleasing and I'd request to please improve the firma Ui of the Android part and also the on Boarding screens and once all that is set I'll deliver the work as soon as possible

**Comment by essy16** [comment]
@codervivek5

**Comment by essy16** [comment]
@07jasjeet

**Comment by 07jasjeet** [comment]
For now we can ignore the onboarding section. Once we have the main screens setup then we can move forward. If you want you can improve the Ui of already existing layouts.

**Comment by essy16** [comment]
Okay
