### ISSUE TITLE
Responsiveness of the website 

### ISSUE THREAD

**Issue by abhayy143** [codervivek5/VigyBag#46]
Hey, I wanted to contribute to the website as a part of GSSoc'23.

## Issue 

As of I've mentioned the picture below as well, the website is not responsive and shows major UI flaws when opened on other devices such as mobile phones etc. 

![19](https://github.com/codervivek5/VigyBag/assets/53009878/080dfe0d-fd39-485b-a7ac-e203409c1249)

![20](https://github.com/codervivek5/VigyBag/assets/53009878/8d862636-75e6-42d9-9f13-ca134bd4b16e)

**Comment by codervivek5** [comment]
after creating all the pages I will assign this issue to you to make a responsive whole website with level 3.

Kindly wait till create a basic structure.

**Comment by abhayy143** [comment]
Okayy @codervivek5
