### ISSUE TITLE
Improvement in header 

### ISSUE THREAD

**Issue by khushbumaheshwarii** [codervivek5/VigyBag#466]
adding margin on the light mode dark mode icons

**Comment by codervivek5** [comment]
Explain me what changes you want to work

**Comment by khushbumaheshwarii** [comment]
> Explain me what changes you want to work

![image](https://github.com/codervivek5/VigyBag/assets/81244936/78be6285-7f8a-410b-bcda-bf624537c094)
adding spacing between these icon

**Comment by khushbumaheshwarii** [comment]
@codervivek5  please assign me

**Comment by codervivek5** [comment]
do not change any other code if you do not necessary................make sure that pull the code before the  fix bug

**Comment by akanksha984** [comment]
Please assign it to me under gssoc'23. I want to work on it
