### ISSUE TITLE
Creating a login page(Gssoc'23)

### ISSUE THREAD

**Issue by Bharatpathak08** [codervivek5/VigyBag#47]
Creating a login page as well as sign up page.

**Comment by Rishi2602** [comment]
It can be easily implemented using the Django user model and Oauth with a responsive template.I would like to contribute to the project as a GSSoC'23 contributor. Please Assign it to me.

**Comment by codervivek5** [comment]
another candidate is also working on a similar to this issue so at this time I cant assign it to you.
