### ISSUE TITLE
Create Services Page

### ISSUE THREAD

**Issue by abhinav-m22** [codervivek5/VigyBag#485]
The navbar and the footer shows **Services** option but the page does not exist.
I will develop the services page with appropriate content and animations in sync to the other pages.

<br>

<img width="960" alt="image" src="https://github.com/codervivek5/VigyBag/assets/113239388/783ef7f8-7e1b-48d7-81ad-1c6e3d80fbea">

<br>

I want to work on this feature implementation.
Please assign me the issue under GSSoC'23.

**Comment by Abhishek-kumar0503** [comment]
i am a gssoc23 contributor . please assign this issue to me @codervivek5. I will develop a service page with content
.

**Comment by codervivek5** [comment]
@abhinav-m22 any update
