### ISSUE TITLE
create a side navbar

### ISSUE THREAD

**Issue by ePSA-eJya** [codervivek5/VigyBag#487]
i am a gssoc23 contributor . pleaase assign this issue to me @codervivek5 
![image](https://github.com/codervivek5/VigyBag/assets/120899038/2cddc2ff-96d5-449d-be30-b3542bf925d7)
similar to this example

**Comment by mohitparmar1** [comment]
@ePSA-eJya I would like to work on this issue! please /assign

**Comment by ePSA-eJya** [comment]
I am already working on this issue

**Comment by ePSA-eJya** [comment]
![image](https://github.com/codervivek5/VigyBag/assets/120899038/f0eaa43a-7c97-4474-a235-dbca3ca8381c)
 check this @codervivek5
