### ISSUE TITLE
Signup and Login  Authentication not working due to inappropriate POST request and URL

### ISSUE THREAD

**Issue by Nishitbaria** [codervivek5/VigyBag#499]
The signup and login functionality on the website is currently not working as expected. After investigation, it has been identified that the issue lies with the inappropriate POST request and URL being used for these processes.

**Steps to Reproduce:**
1. Visit the website.
2. Attempt to sign up or log in using valid credentials.
3. Observe that the signup/login process fails to complete successfully.

**Expected Behavior:**
The signup and login processes should successfully create a new user account or authenticate an existing user, respectively.

**Actual Behavior:**
The signup and login processes are failing, preventing users from creating new accounts or logging in.

![image](https://github.com/codervivek5/VigyBag/assets/85815172/08ed8151-dc20-4afa-8cf5-e19f719f362b)

**Additional Information:**
Upon further analysis, it was found that the POST request being sent to the server is not correctly formatted or contains incorrect parameters. Additionally, the URL being used for the signup and login requests seems to be inappropriate or incorrect.

**Proposed Solution:**
To resolve this issue, I will handle  code responsible for handling the signup and login functionality. Ensure that the POST request is properly formatted with the required parameters and that the URL being used is appropriate for these operations. Once the necessary changes are made, retest the signup and login processes to ensure they are functioning as expected.

please assign me this issue ,I will fix it asap

**Comment by Nishitbaria** [comment]
Please @codervivek5  assign it to me I will create a PR today

**Comment by Nishitbaria** [comment]
@codervivek5  please review my pull request and assign appropriate level,I have contributed to my level best .

**Comment by codervivek5** [comment]
ok I will check it
