### ISSUE TITLE
I want to add app section as per figma.

### ISSUE THREAD

**Issue by Babunshil** [codervivek5/VigyBag#5]
![Screenshot (47)](https://user-images.githubusercontent.com/106283743/228343003-31e029c4-d47c-49cd-8704-6bccbc378eeb.png)

**Comment by codervivek5** [comment]
Kindly create PR for it I will merged

**Comment by Babunshil** [comment]
this section was also included in my previous PR, so you can close the issue

**Comment by codervivek5** [comment]
ok will do it
