### ISSUE TITLE
Fix Search Box Styling

### ISSUE THREAD

**Issue by MOHDNEHALKHAN** [codervivek5/VigyBag#50]
@codervivek5 Please assign this issue to me as a gssoc'2023 contributor I want to work on this issue
Before Changes - 
![Screenshot 2023-05-20 235243](https://github.com/codervivek5/VigyBag/assets/125626654/97e0f6eb-2d64-4512-ab2d-1cf0a3756421)
After Changes, it looks like -
![Screenshot 2023-05-20 235306](https://github.com/codervivek5/VigyBag/assets/125626654/ce530806-d8f7-4d9c-9927-e242643a57b1)

**Comment by codervivek5** [comment]
another candidate is also working on a similar to this issue so at this time I cant assign it to you.

**Comment by MOHDNEHALKHAN** [comment]
Ok Thanks for reply
