### ISSUE TITLE
[GSSOC'23] - Add -- Add to Cart 

### ISSUE THREAD

**Issue by komala777** [codervivek5/VigyBag#510]
Adding Add to Cart in the heading bar
![Headdin Bar](https://github.com/codervivek5/VigyBag/assets/114868231/75a6ec3b-8965-4a27-a873-08a67e89ddc6)
@codervivek5 Please assign this issue to me.

**Comment by SyedImtiyaz-1** [comment]
> Adding Add to Cart in the heading bar ![Headdin Bar](https://user-images.githubusercontent.com/114868231/249222852-75a6ec3b-8965-4a27-a873-08a67e89ddc6.png) @codervivek5 Please assign this issue to me.

I have added on click add to cart I don't think there is any need of `Add to cart` in header

**Comment by komala777** [comment]
> > Adding Add to Cart in the heading bar ![Headdin Bar](https://user-images.githubusercontent.com/114868231/249222852-75a6ec3b-8965-4a27-a873-08a67e89ddc6.png) @codervivek5 Please assign this issue to me.
> 
> I have added on click add to cart I don't think there is any need of `Add to cart` in header

I want to add this in the heading bar where all the user items are listed. IDK where you want to add this. Could you attach your issue here.

**Comment by SyedImtiyaz-1** [comment]
here is the video - @komala777 [Screencast from 28-06-23 10:59:52 AM IST.webm](https://github.com/codervivek5/VigyBag/assets/121503426/8342b22c-e2d1-4b8c-8630-d6a9e9f19718)
