### ISSUE TITLE
To highlight active tab in navbar 

### ISSUE THREAD

**Issue by I-shika** [codervivek5/VigyBag#515]
I want to add a feature to highlight the active tab in navbar .
![Screenshot (80)](https://github.com/codervivek5/VigyBag/assets/100770197/d3a3161d-ef8b-4596-a342-4529c1b6cd6a)

Please assign this issue to me under GSSoC'23

**Comment by Riyazul555** [comment]
Hey @codervivek5 I want to work on this issue ....please assign me this
