### ISSUE TITLE
Adding Flip Card Feature to the Products

### ISSUE THREAD

**Issue by parthksingh1** [codervivek5/VigyBag#52]
Will Add Flip Card Feature to the product which on backside will be having some details of the product, like size price rating

**Comment by parthksingh1** [comment]
Please Assign me this under @GSSOC'23 to make it better.

**Comment by codervivek5** [comment]
another candidate is also working on a similar to this issue so at this time I cant assign it to you.

**Comment by sagnik-p** [comment]
This issue has been inactive for a long time
I would like to work on this issue
Please assign
