### ISSUE TITLE
Contact us page

### ISSUE THREAD

**Issue by kasturimandlik** [codervivek5/VigyBag#54]
I want to create a fully functional contact us page for the website.

The contact us page will have all the necessary details which should be collected from the user like email address, name, mobile number, message, etc. It will also have other contact information.

I would like to work on this issue under GSSOC'23. Please assign me this isse

**Comment by codervivek5** [comment]
Actually, @kasturimandlik someone is already working on it so at this time I can't assign it to you. if they are not able to make it then I will definitely assign it to you.
