### ISSUE TITLE
Add icons to social links

### ISSUE THREAD

**Issue by sumitkr2000** [codervivek5/VigyBag#541]
Hey @codervivek5 I want to add the icons of social media in the footer. Please assign me this issue. Thank you!

![image](https://github.com/codervivek5/VigyBag/assets/100675296/b3dfee30-5f29-40dc-a361-2e769f276d37)

**Comment by Kajal2468** [comment]
I would like to work on the issue , please assign it to me I want add icons to social link with more functionality

Please assign in under GSSoc'23

Thank You!
