### ISSUE TITLE
A New Design for Footer  

### ISSUE THREAD

**Issue by parthksingh1** [codervivek5/VigyBag#55]
I will Make A New Good-Looking and Awesome Footer with hover button Effects and with nice looking social media icons with hover effect.
So please assign me this under GSSOC'23
Also the project is very helpful in shopping for things, and a lot can be added to make it a successful one 👍
Thank you !

**Comment by mahekkg** [comment]
Hey @codervivek5 
Improving the footer to the application can provide various benefits for functionality and user experience. Consider including navigation links, social media icons, copyright information, terms of service, privacy policy, and contact information. These elements enhance navigation, brand visibility, legal compliance, and user trust. Customize the footer based on your application's goals and target audience will be beneficial.

I have already contributed to similar task which makes it easier to successfully complete the task
Please assign me this task under GSSoC'23
Thank you

**Comment by green-veggies** [comment]
I am interested in contributing in this project under GSSoC'23

**Comment by codervivek5** [comment]
try to use the pre-build design from the readme.md file

**Comment by purviporwal1812** [comment]
i would love to contribute in this project Pls assign this to me

**Comment by PayalPadmalyaPrusty** [comment]
@codervivek5 I want to contribute.Please assign me
