### ISSUE TITLE
Search Area Design Enhancement

### ISSUE THREAD

**Issue by iamRabia-N** [codervivek5/VigyBag#560]
The current design of the search area is nice but it can be improved by making some design adjustment. By working on the styling properties, I can improve its design.
**Current Design**
![vigay-project (4)](https://github.com/codervivek5/VigyBag/assets/115794049/e359bf64-1536-439d-88d0-38b89afa98e2)

**Expected Updated Design**
![vigay-project (3)](https://github.com/codervivek5/VigyBag/assets/115794049/921252ff-9854-4edd-8816-e5bc98bf7a06)

**Comment by iamRabia-N** [comment]
@07jasjeet

**Comment by 07jasjeet** [comment]
Sorry @iamRabia-N but I can only assign issues related to Android. @JigarJoshi04 @codervivek5 are the ones who can assign you issues related to website or backend.

**Comment by iamRabia-N** [comment]
@codervivek5 Kindly assign me this issue

**Comment by iamRabia-N** [comment]
@JigarJoshi04

**Comment by codervivek5** [comment]
@iamRabia-N make these changes in the search bar
- shift this search bar below to the navigation bar
- make alignment in the center of the page
- Do not make any changes in size, font, padding, and text-style

**Comment by iamRabia-N** [comment]
Hi @codervivek5 
Kindly add level label in the issue.
