### ISSUE TITLE
"Headphones for you" Section Content Alignment Enhancement

### ISSUE THREAD

**Issue by iamRabia-N** [codervivek5/VigyBag#561]
The current design of this section is nice but it can be improved by working on the alignment of the content. By aligning the content in the center, I can improve the design of this section.

**Current Alignment**
![vigay-project (2)](https://github.com/codervivek5/VigyBag/assets/115794049/1dba20af-c2b2-4e9b-b90b-d7859cc229af)

**Expected Updated Alignment**
![vigay-project (1)](https://github.com/codervivek5/VigyBag/assets/115794049/7ee18105-ca5b-4bb9-939c-4495888c062d)

**Comment by iamRabia-N** [comment]
@codervivek5 Kindly assign me this issue.

**Comment by iamRabia-N** [comment]
@07jasjeet

**Comment by iamRabia-N** [comment]
@codervivek5 Kindly assign me this issue

**Comment by iamRabia-N** [comment]
@JigarJoshi04

**Comment by codervivek5** [comment]
kindly make this section responsive
