### ISSUE TITLE
Adding Navbar in About Page

### ISSUE THREAD

**Issue by krutikajichkar** [codervivek5/VigyBag#563]
Right now Home and contact is shown as a footer to navigate back , but this is not a good user expirience so i want to add navbar in About page as well . I am a gssoc'23 contributor , please assign me this under gssoc'23

![Screenshot (132)](https://github.com/codervivek5/VigyBag/assets/93243210/407eb8cc-58b3-416f-a562-1dd713494776)

**Comment by ree1500** [comment]
@krutikajichkar Please assign this task to me.
