### ISSUE TITLE
Android: Main Screen

### ISSUE THREAD

**Issue by 07jasjeet** [codervivek5/VigyBag#566]
This issue points out the lack of main screen in Vigybag Android, without which, the app has no meaning. The main screen consists of the layout of all the available shopping items as inspired by the website. UI should be constructed with the website in mind.

**Comment by javaman97** [comment]
@07jasjeet I would love to work on this issue.Pls assign me this issue

**Comment by 07jasjeet** [comment]
@javaman97 have a go!
