### ISSUE TITLE
Android: Improve sign-up and sign-in UI 

### ISSUE THREAD

**Issue by essy16** [codervivek5/VigyBag#567]
Sign-up / sign-in fragments could use some UI improvements in VigyBag Android App.

**Comment by javaman97** [comment]
@07jasjeet Assign me this issue, I will use Material 3 Design  to improve the UI

**Comment by 07jasjeet** [comment]
@javaman97 @essy16 none of you will be assigned this issue until or unless your previously assigned issues are closed. One issue at a time.

**Comment by Iamdivyak** [comment]
please assign this issue to me under gssoc

**Comment by 07jasjeet** [comment]
@Iamdivyak This issue corresponds to the UI of Android App and not the website.

**Comment by essy16** [comment]
@07jasjeet now can you assign me this issue.

**Comment by 07jasjeet** [comment]
@essy16 have a go! Make sure to leave before and after screenshots on your PRs.

**Comment by essy16** [comment]
Thank you for the correction... I'll do so

**Comment by essy16** [comment]
@07jasjeet can I also implement sign in and sign up with google , twitter and facebook?

**Comment by 07jasjeet** [comment]
@essy16 the scope of work for these sign-ins is very vast. I would recommend you to stick to what is already there. These sign-ups require backend support for which the owner seems to be offline/unavailable. Since we can't proceed with login or sign up right now, I would like you to focus on UI for now.

**Comment by essy16** [comment]
Ok but should I include those icons on the UI? @07jasjeet

**Comment by 07jasjeet** [comment]
@essy16 sure

**Comment by chhavisharma30** [comment]
I can work on this issue. Kindly assign me this.

**Comment by 07jasjeet** [comment]
@chhavisharma30 this issue is already assigned to @essy16 but there are a lot more issues you can work with. Just search with `android` label in issues.
