### ISSUE TITLE
[FEATURE] Add "Scroll-to-Top" button

### ISSUE THREAD

**Issue by sanketsaurav2411** [codervivek5/VigyBag#57]
Hi @codervivek5,
I would like to add a feature to scroll to top as a button on the home page.
Please assign me this issue under GSSOC'23.

**Comment by sanketsaurav2411** [comment]
Hello @codervivek5, 
Please assign me this issue.

**Comment by codervivek5** [comment]
another candidate is also working on a similar to this issue so at this time I cant assign it to you.
