### ISSUE TITLE
Make Login-page

### ISSUE THREAD

**Issue by sanketsaurav2411** [codervivek5/VigyBag#58]
Hi @codervivek5,
I would like to make a Login-page for the website.
Please assign me this issue under GSSOC'23.

Login-page:
![image](https://github.com/codervivek5/VigyBag/assets/75113050/b373f7cc-8605-4cfa-889b-0f5943217112)

**Comment by sanketsaurav2411** [comment]
Hello @codervivek5,
Please assign me this issue.

**Comment by sanketsaurav2411** [comment]
> Hello @codervivek5, Please assign me this issue.

I would like to build **LogIn** and **SignUp** page :)

**Comment by codervivek5** [comment]
Thank you for your interest but another person already working in the same issue so at this time I can't assign it to you.
I am really sorry but you can drop or create any other issue and wait for the assign. 

try to avoid work in any issue in any project with assign it. It will be helpful for you.

Thanka again
