### ISSUE TITLE
Add a creative footer

### ISSUE THREAD

**Issue by deepeshmlgupta** [codervivek5/VigyBag#580]
I have a quite good solution for your website to add an attractive and informative footer section which will consist of all the important information about the website and all the official social media handles.

<img width="952" alt="image" src="https://github.com/codervivek5/VigyBag/assets/108192513/43f93ca2-fcff-4400-adbe-97e6bdf548d3">
I have created the footer section like this for codesetgo website I can make this footer for you also 

So, please assign me this task under gssoc'23 
So, that I can start working on it

**Comment by Kajal2468** [comment]
I would like to work on the issue , please assign me 

Thank You!
