### ISSUE TITLE
Add logos for socials in the footer section

### ISSUE THREAD

**Issue by blindaks** [codervivek5/VigyBag#583]
There are no icons for Instagram
![Screenshot (31)](https://github.com/codervivek5/VigyBag/assets/128223364/bc12b15f-6e5e-4734-a111-3393a37151ce)
, Facebook, and LinkedIn in the footer section.

**Comment by blindaks** [comment]
@codervivek5 Please assign this issue to me.

**Comment by ree1500** [comment]
@codervivek5 Please assign this to me.
