### ISSUE TITLE
Android: Multiple Shopping Locations in Map

### ISSUE THREAD

**Issue by Swa-stika** [codervivek5/VigyBag#584]
###**Description**

The Google Maps API is utilized to mark multiple locations on a map, representing various shopping places. By providing the latitude and longitude coordinates of these places, users can conveniently view and navigate through them. This feature enhances user experience and facilitates exploration of different shopping destinations.

**Comment by Swa-stika** [comment]
@codervivek5 , please assign me this issue under gssoc23.

**Comment by Swa-stika** [comment]
@07jasjeet  , please  kindly assign me the issue under gssoc23

**Comment by 07jasjeet** [comment]
@Swa-stika I can only assign issues related to VigyBag Android. If you want to implement this in the Android app, sure I can assign it.

**Comment by Swa-stika** [comment]
@07jasjeet I will like to implement.

**Comment by 07jasjeet** [comment]
Alright @Swa-stika have a go!

**Comment by 07jasjeet** [comment]
Before beginning work, @Swa-stika please leave a pre-run on how you will go about implementing this.

**Comment by 07jasjeet** [comment]
@Swa-stika any updates?

**Comment by Swa-stika** [comment]
@07jasjeet I have used google map api and added multiple markers in the map till now . And trying to enhance and optimise further.

**Comment by 07jasjeet** [comment]
> @07jasjeet I have used google map api and added multiple markers in the map till now . And trying to enhance and optimise further.
> 
> 
> 
> 

@Swa-stika updates please?
