### ISSUE TITLE
Add GitHub link in the socials section

### ISSUE THREAD

**Issue by blindaks** [codervivek5/VigyBag#586]
I want to add a GitHub icon and link in the SOCIAL section of Footer.

**Comment by blindaks** [comment]
@07jasjeet Please assign this issue to me under GSSOC'23.

**Comment by 07jasjeet** [comment]
Sorry @blindaks but I can only assign issues related to Android. @JigarJoshi04 @codervivek5 are the ones who can assign you issues related to website or backend.
