### ISSUE TITLE
Removing scroll bars

### ISSUE THREAD

**Issue by kaur-rajdeep** [codervivek5/VigyBag#587]
There are several extra scrollbars present, even where not required. These need to be removed. 
Could you please assign me this issue under gssoc 23 ? I would like to work on it.
Thank you.
![image](https://github.com/codervivek5/VigyBag/assets/106001705/259ea358-ecc1-45be-9650-82f7f654c06f)

**Comment by sakshinikharge39** [comment]
I want to solve this issue.
Please assign me this issue

**Comment by codervivek5** [comment]
@sakshinikharge39 check it once in live mode then inform me
