### ISSUE TITLE
go  bottom to top button 

### ISSUE THREAD

**Issue by Sushilverma002** [codervivek5/VigyBag#589]
button is added go top to bottom
![image](https://github.com/codervivek5/VigyBag/assets/114687502/52544d0c-7a07-4222-b807-959e362f85e5)

https://github.com/codervivek5/VigyBag/assets/114687502/689676cc-3f1b-4ca1-aaaf-ec0e29b0ec70

it is ready to merge please assign me @codervivek5

**Comment by codervivek5** [comment]
kindly remove the mini scroll bar of this scroll button and shift this button to the right side below to chatbot

**Comment by Sushilverma002** [comment]
sir mini scroll bar is present in whole website that's why it showing @codervivek5

**Comment by Sushilverma002** [comment]
![image](https://github.com/codervivek5/VigyBag/assets/114687502/c81d32fe-9953-43d4-bbc8-f557a9c6e7f7)
is it okay ?@codervivek5
