### ISSUE TITLE
Header not visible in about section.

### ISSUE THREAD

**Issue by PiyushK79** [codervivek5/VigyBag#590]
The header for navigation is no available in the about us section. I would add the header for easy navigation.

Screenshot  
![image](https://github.com/codervivek5/VigyBag/assets/100259650/ca018a76-c3b8-40ff-93d9-27122417f466)

@codervivek5 Please assign this issue to mw under Gssoc23.

**Comment by sakshinikharge39** [comment]
please assign me this issue.
