### ISSUE TITLE
Footer does not show logos of the socials

### ISSUE THREAD

**Issue by PoulavBhowmick03** [codervivek5/VigyBag#598]
![image](https://github.com/codervivek5/VigyBag/assets/133862694/b59e9d86-55a7-4304-8709-efce2d10c629)

The social logos are not visible in the footer
I want to fix that

**Comment by PoulavBhowmick03** [comment]
@codervivek5 Please assign this

**Comment by ParthMadhvani2** [comment]
hey, I have solved this issue and sent a pull request for it please accept it as I am a GSSoC'23 contributor.
