### ISSUE TITLE
making the images of the items zoom in and zoom out while hovering

### ISSUE THREAD

**Issue by shramanpaul** [codervivek5/VigyBag#60]
Let me assign this issue under GSSoC'23.

**Comment by SaloniLathwariya** [comment]
Kindly assign this issue to me under GSSoC'23.

**Comment by shramanpaul** [comment]
I have made the pull request please review it and merge the files.

**Comment by shramanpaul** [comment]
@codervivek5

**Comment by sagnik-p** [comment]
This issue has been inactive for a long time
I would like to work on this issue
Please assign
