### ISSUE TITLE
Fix Dark Mode Button & Structure of the landing page

### ISSUE THREAD

**Issue by parasss19** [codervivek5/VigyBag#608]
## Current
-  Dark mode button is not properly applied 
- its not working properly

## Change
- I will re  write the whole code properly
- Apply proper CSS for that
- And adding proper functionality for it

**Comment by codervivek5** [comment]
@parasss19 try to fix the whole landing page design.....I don't know hoe contributors make changes
it is not possible for me to read code line by line then merged PR :(

**Comment by anubhav1206** [comment]
Can I work on this?
