### ISSUE TITLE
Adding hover effect on arrows in Testimonial section

### ISSUE THREAD

**Issue by Priyaaa1** [codervivek5/VigyBag#609]
I would like to add some hover effect to arrows of the carousel in the Testimonial section, which would gook better. Please assign me this under GSSoC'23 label.
Thankyou!

**Comment by FelixAmofahDev** [comment]
This will be fun and cool to do. Please assign me this project.

**Comment by FelixAmofahDev** [comment]
This will be fun and cool to do. Please assign me this project.
