### ISSUE TITLE
Android: Search Bar

### ISSUE THREAD

**Issue by 07jasjeet** [codervivek5/VigyBag#611]
# Problem
Currently search bar of android app is inoperable. The search bar should be used to search for products available on VigyBag.

# Action
The search bar should be able to show results by querying a remote database through an API endpoint, but since the server is not live yet, fake or mock data must be used to populate search results.

**Comment by javaman97** [comment]
@07jasjeet Please assign me this issue

**Comment by 07jasjeet** [comment]
@javaman97 have a go!
