### ISSUE TITLE
Android: Refresh Indicator

### ISSUE THREAD

**Issue by 07jasjeet** [codervivek5/VigyBag#612]
# Problem
When the app makes an API call to fetch data from server, the user should be notified with a circular progress indicator.

# Action
Since our server is not live yet, we an still have a refresh indicator and leave space for the API call when the server goes live.

**Comment by biplavmz** [comment]
I would like to work @07jasjeet

**Comment by javaman97** [comment]
@07jasjeet Would you please assign me this issue?

**Comment by 07jasjeet** [comment]
@javaman97 have a go!
