### ISSUE TITLE
Android: Product Page

### ISSUE THREAD

**Issue by 07jasjeet** [codervivek5/VigyBag#613]
# Problem
When a user clicks a product, nothing happens, which is in contrast to what should happen on a usual shopping website, where the product page should open.

# Action
Design and implement a product page which is reusable across the app.

**Comment by biplavmz** [comment]
I would like to work on this issue @07jasjeet

**Comment by essy16** [comment]
@07jasjeet please assign me this

**Comment by 07jasjeet** [comment]
@essy16 have a go!
