### ISSUE TITLE
Android: Settings fragment and theme switch

### ISSUE THREAD

**Issue by 07jasjeet** [codervivek5/VigyBag#614]
# Problem
Having settings in an app is intuitive. A user always navigates to settings when they have to perform some app specific actions like change theme.

# Action
Design settings fragment and implement theme switch as well.

**Comment by essy16** [comment]
@07jasjeet Can you give me this task?

**Comment by 07jasjeet** [comment]
@essy16 You are already assigned one issue, please finish that first.

**Comment by javaman97** [comment]
@07jasjeet Please assign me this issue

**Comment by biplavmz** [comment]
Hii @07jasjeet i would like to work. please assign me

**Comment by 07jasjeet** [comment]
> Hii @07jasjeet i would like to work. please assign me

@biplavmz This issue  is **Android** app related and as far as I can see you have experience in Web dev. Are you sure about this?

**Comment by biplavmz** [comment]
ya @07jasjeet  let me give a try

**Comment by 07jasjeet** [comment]
@biplavmz Alright have a go but make sure to use Kotlin and Preference Fragment.

**Comment by 07jasjeet** [comment]
@biplavmz any updates?

**Comment by biplavmz** [comment]
you can assign this task other as i am trying not able to do it @07jasjeet

**Comment by 07jasjeet** [comment]
> you can assign this task other as i am trying not able to do it @07jasjeet

Alright thanks for trying!
