### ISSUE TITLE
Starting django project and updating urls for css and images as per static files

### ISSUE THREAD

**Issue by harshit21-02** [codervivek5/VigyBag#62]
I want to work on this issue. I am a Gssoc23 contributor, Please assign me!

**Comment by codervivek5** [comment]
Try to follow these steps.
-  make a folder with the name "Backend Code"
-  you should manage all the files under this folder.

**Comment by Saumya40-codes** [comment]
@codervivek5 @harshit21-02 if this is still active, then ill like to contribute/collaborate on this.

**Comment by harshit21-02** [comment]
> Try to follow these steps.
> 
> * make a folder with the name "Backend Code"
> * you should manage all the files under this folder.

Okay, so I will copy all html files needed and create a separate django project inside "Backend"Folder.

Will that work?

**Comment by harshit21-02** [comment]
@codervivek5   I think copying separate files will be difficult for merging future changes in future.. So we should just move required files inside django project instead of copying them

**Comment by harshit21-02** [comment]
I am creating a pull request. Please merge, it includes a separate folder for backend
