### ISSUE TITLE
Brand logo is not visible

### ISSUE THREAD

**Issue by krutikajichkar** [codervivek5/VigyBag#622]
Brand logo is not visible due to path given to the image , i want fix that , please assign me this under gssoc'23

![Screenshot (172)](https://github.com/codervivek5/VigyBag/assets/93243210/17b7b990-ad20-450d-985d-1ca2d61534a0)

**Comment by s4shantanu** [comment]
Hi @codervivek5 i want to work on this issue please can you assign me this issue with GSSoc label.

**Comment by codervivek5** [comment]
sorry for the inconvenience

you can enhance this About Us page like make some changes to it

remove smit and shift the below text in this place
change the image of the about us page
replace about us vigybag with about us only in a single line and change the text color with the theme color
using the navbar from the index.html file that is better from this one
