### ISSUE TITLE
Android: Implement Dependency Injection

### ISSUE THREAD

**Issue by 07jasjeet** [codervivek5/VigyBag#629]
# Problem
Currently VigyBag Android has no dependency injection.

# Action
Use Koin or Dagger to implement dependency injection.

**Comment by javaman97** [comment]
@07jasjeet Please assign me this issue, I would love to work on this issue

**Comment by 07jasjeet** [comment]
> @07jasjeet Please assign me this issue, I would love to work on this issue

Please refrain from asking me to assign new issues while you are already working on one.

**Comment by javaman97** [comment]
@07jasjeet Would you assign me this issue now, as I have successfully completed my last assigned work?

**Comment by 07jasjeet** [comment]
@javaman97 have a go!
