### ISSUE TITLE
Creating models with all required feilds

### ISSUE THREAD

**Issue by harshit21-02** [codervivek5/VigyBag#63]
I want to work on this issue. I am a Gssoc23 contributor, Please assign me!

**Comment by davideke1** [comment]
I would love to work on this issue

**Comment by HemantS404** [comment]
I want to contribute on the django models part, i am a Gssoc23 contibutor. I have been working with django for about 2 yrs now. So i find myself worthy to contribute here. I have also bulit many live projects using django REST as a backend.
