### ISSUE TITLE
Add GitHub link in footer

### ISSUE THREAD

**Issue by blindaks** [codervivek5/VigyBag#638]
I want to add a GitHub link in the footer section.

**Comment by blindaks** [comment]
@codervivek5 Please assign this issue to me under GSSoC'23.

**Comment by aniiegithub** [comment]
I want to add GitHub link in footer.
Please assign this issue to me @codervivek5

**Comment by codervivek5** [comment]
no need to add GitHub link ....we should not share our source code publically guys
