### ISSUE TITLE
[BUG]: website is broken 

### ISSUE THREAD

**Issue by Sushilverma002** [codervivek5/VigyBag#641]
currently-:

https://github.com/codervivek5/VigyBag/assets/114687502/4e7abd42-7b6b-403b-804d-2109c42059e4

after update:

https://github.com/codervivek5/VigyBag/assets/114687502/125a5c58-8cf5-4371-9f8f-886ffc1d3e5b

one more feature is added:-when ever user click on service button it will redirected services  section;-

https://github.com/codervivek5/VigyBag/assets/114687502/228a7d67-7798-4ae9-b19a-e201187e702a

**Comment by Sushilverma002** [comment]
@codervivek5 HAVE A LOOOKKKKKKKKKKKKK!!!!!!!!!!!!!!!!!!!!
IT IS READY TO MERGE PLEASE ASSIGN ME UNDER GSSOC'23.

**Comment by Sushilverma002** [comment]
@codervivek5

**Comment by Sushilverma002** [comment]
@codervivek5

**Comment by codervivek5** [comment]
make PR
