### ISSUE TITLE
[BUG]: HEADER LINKS ARE BROKEN 🪲

### ISSUE THREAD

**Issue by 0xabdulkhaliq** [codervivek5/VigyBag#644]
## Description
- The header links like `About Us`, `Contact Us` are broken whenever we try to traverse through them
- We need to fix those broken links otherwise it will break the entire site.

##  Recording of Bug
https://github.com/codervivek5/VigyBag/assets/92252895/94763533-d588-49e4-8c39-cf70c3bf0b85

**Comment by 0xabdulkhalid** [comment]
Hey there @aniketsinha2002 👋🏻

Please make sure to assign this issue to me asap to make the work done!

Thank you.

**Comment by 0xabdulkhaliq** [comment]
Hey there @codervivek5  👋🏻

Please make sure to assign this issue to me asap to make the work done!

Thank you.

**Comment by codervivek5** [comment]
this work in  process bro
