### ISSUE TITLE
Website not responsive

### ISSUE THREAD

**Issue by akanksha984** [codervivek5/VigyBag#650]
![image](https://github.com/codervivek5/VigyBag/assets/97845909/c3f4f7be-ffa9-418b-899a-f9e20d559542)

I want to make it responsive please assign it to me under gssoc'23.
@codervivek5

**Comment by codervivek5** [comment]
Can you make it responsive?

**Comment by akanksha984** [comment]
yes soon will be creating pr for this
@codervivek5

**Comment by akanksha984** [comment]
@codervivek5 please check the pr #742

**Comment by sakshinikharge39** [comment]
please assign me this issue.
I want to solve it
