### ISSUE TITLE
Fix missing icon

### ISSUE THREAD

**Issue by akanksha984** [codervivek5/VigyBag#656]
![image](https://github.com/codervivek5/VigyBag/assets/97845909/569ce074-ad73-4a99-9dbb-e68787368850)
![image](https://github.com/codervivek5/VigyBag/assets/97845909/8f6c11f5-11af-4a96-bf71-0533e0735df2)

The 3rd icon vanished on hover, I want to fix this. Please assign it to me under gssoc'23

**Comment by codervivek5** [comment]
now these properly working
