### ISSUE TITLE
UI of cards Improvement

### ISSUE THREAD

**Issue by akanksha984** [codervivek5/VigyBag#657]
![image](https://github.com/codervivek5/VigyBag/assets/97845909/c50303d4-e06e-4550-8fac-0dc3bcacd89f)
![image](https://github.com/codervivek5/VigyBag/assets/97845909/c2dcc381-e7d4-4c11-93a7-b1057953f384)
![image](https://github.com/codervivek5/VigyBag/assets/97845909/9c1a2bee-e777-44c3-9201-73735940dd1a)

Improve the ui of the cards.
Please assign it to me @codervivek5 under gssoc'23. I want to improve the ui of the cards

**Comment by codervivek5** [comment]
Share any output at PR time also  mention issue number
