### ISSUE TITLE
Creating APIs for CRUD operations in Product Model

### ISSUE THREAD

**Issue by harshit21-02** [codervivek5/VigyBag#66]
I want to work on this issue. I am a Gssoc23 contributor, Please assign me!

**Comment by harshit21-02** [comment]
I'll be using DjangoRestFramework for creating Restful APIs

**Comment by syedawanya18** [comment]
I want to work on this issue as a contributor.
Pleasure Assign so that I can show my skills under GSSoC'23.
I will be using Node.js

**Comment by HemantS404** [comment]
I want to work on the crud apis using DRF , I am Gssoc23 Contirbutor. I am well versed with django REST api, and built many live projects on it
