### ISSUE TITLE
Button alignment issue 

### ISSUE THREAD

**Issue by biplavmz** [codervivek5/VigyBag#675]
<img width="81" alt="image" src="https://github.com/codervivek5/VigyBag/assets/68702055/b82d12cf-8140-4d81-a999-91e4b5351b67">
I'm a GSSoC'23 contributor please assign me this issue under gssoc label and level.

**Comment by Kajal2468** [comment]
@codervivek5 please assign this issue in under GSSoc'23

Thank You!

**Comment by codervivek5** [comment]
I think .....some one already working in this same issue....you guys can check it
