### ISSUE TITLE
[Gssoc'23] Contact page login button not working(bug)

### ISSUE THREAD

**Issue by kanishkasah20** [codervivek5/VigyBag#679]
In contact page login button is not working properly , i will fix it .
Please assign me this issue under gssoc'2

https://github.com/codervivek5/VigyBag/assets/114860158/5d2bf38c-4bdc-45ad-b01a-6d70d44dc46d

**Comment by kanishkasah20** [comment]
Please assign me this @codervivek5 sir

**Comment by codervivek5** [comment]
its working now

**Comment by codervivek5** [comment]
you can work in another issue
