### ISSUE TITLE
Responsive Contact page

### ISSUE THREAD

**Issue by krutikajichkar** [codervivek5/VigyBag#687]
I want to make contact page responsive , please assign me this under gssoc'23

![Screenshot (209)](https://github.com/codervivek5/VigyBag/assets/93243210/447bc4f7-7fe4-446b-a821-05a141e94958)

**Comment by Kajal2468** [comment]
please assign this issue i want to work on this issue

Thank You!!

**Comment by karantec** [comment]
please assign this issue i want to work on this issue
