### ISSUE TITLE
Adding functionalities: Like button  , Rating Stars , Add to cart ; UI modifications

### ISSUE THREAD

**Issue by HeyfromNandini** [codervivek5/VigyBag#69]
Hello , I am a GSSOC  contributor here and i would like to implement functionalities to the rating stars and the like button , also there is text error in the add to cart  area ; I would like  to modify some UI such as footer area and outline the available buttons,etc.
Looking forward to useful contributions....
Thankyou.

**Comment by syedawanya18** [comment]
I want to work on this issue as a contributor.
Pleasure Assign so that I can show my skills under GSSoC'23.

**Comment by codervivek5** [comment]
try to reduce the side of all the fields where you want to work.
