### ISSUE TITLE
About Section Issue

### ISSUE THREAD

**Issue by SyedImtiyaz-1** [codervivek5/VigyBag#697]
Hello @codervivek5 ,
About Section issue regarding the footer.

## Screenshot 
![image](https://github.com/codervivek5/VigyBag/assets/121503426/e89f3c52-d4f3-4a2a-9ca4-b8735aa39c25)

### soon will raise a PR

**Comment by codervivek5** [comment]
some one already working on this issue so I can't assign it to you at this time.
