### ISSUE TITLE
Login Section in VigyBag Android

### ISSUE THREAD

**Issue by javaman97** [codervivek5/VigyBag#70]
@codervivek5 I would like to work on the Android App of VigyBag from design to development.

**I will use the following Tech Stack**:-
1) FIGMA ( for Designing UI)
2) Kotlin
3)  Xml
4) Material Design 3

Following the best practices and whatever is required to give a better user-friendly experience.

**Comment by javaman97** [comment]
@codervivek5 Please assign me this task

**Comment by codervivek5** [comment]
any update?

**Comment by javaman97** [comment]
@codervivek5 Yes Sure, I have started designing with _Figma._

**https://www.figma.com/file/NSzGo2uHvqgq4aruqRc5Jf/VigyBag%3A-Android-App?type=design&node-id=1%3A2&t=ghOeBIn6U5TeJRwV-1**

**Please have a look**
Share your valuable feedback!

**Comment by 07jasjeet** [comment]
Just created the Android repo, @javaman97 have a go!

**Comment by javaman97** [comment]
Thank you @07jasjeet,Let's do it

**Comment by Cyclotron17** [comment]
Please assign me this issue I am interested in setting up Retrofit using MVVM clean architecture.
