### ISSUE TITLE
[bug] fix see more button

### ISSUE THREAD

**Issue by codervivek5** [codervivek5/VigyBag#702]
![image](https://github.com/codervivek5/VigyBag/assets/62784060/b5f5b0b3-1f5f-4d00-a090-9a1de3c3d834)
this is the issue in the home page see more option foe the product

**Comment by codervivek5** [comment]
also, add  bottom to top button and chatbot on this page

**Comment by Pragati-3003** [comment]
@codervivek5 , I would like to work on this issue ,please assign this to me.
