### ISSUE TITLE
Product Wishlist icon in not working

### ISSUE THREAD

**Issue by codervivek5** [codervivek5/VigyBag#704]
![image](https://github.com/codervivek5/VigyBag/assets/62784060/814976bb-7415-401a-afa4-ca388c5d6948)

**Comment by tayyab-ilyas** [comment]
hey @codervivek5 sorry for the delay, i'll be creating a PR shortly

**Comment by tayyab-ilyas** [comment]
Please merge my PR @codervivek5 🙏
