### ISSUE TITLE
Add some space on Cart Icon and enhance the cart page

### ISSUE THREAD

**Issue by codervivek5** [codervivek5/VigyBag#705]
add some space in this icon

![image](https://github.com/codervivek5/VigyBag/assets/62784060/14e7461b-90e2-4841-93e0-858bf23b7731)

Enhance this cart page

![image](https://github.com/codervivek5/VigyBag/assets/62784060/91229323-b923-42ca-8383-8947eeb15623)

**Comment by codervivek5** [comment]
also add a product remove button on it so that costumer can remove any product which they want

**Comment by DivyanshiNarang** [comment]
I would like to work on this issue. please assign this to me @codervivek5

**Comment by codervivek5** [comment]
any update ???

**Comment by DivyanshiNarang** [comment]
@codervivek5 I am working on it.
