### ISSUE TITLE
Creating an array of products where listing the products dynamically  from there

### ISSUE THREAD

**Issue by Satyam0204** [codervivek5/VigyBag#71]
Hey, I am Satyam Pattanaik, a contributor in GSSOC 23', I want to make the listing of products dynamic by adding the objects of the products in js files by modelling them and then rendering them dynamically.

I request you to please assign this to me as it will help to list more products to the site and opens scope for a lot of features like search filtering.

**Comment by codervivek5** [comment]
Thank you for your interest @Satyam0204 but will do it via the backend so I think there is no need to create it for the frontend view. If you are interested in this project then you can go through the backend process.

Again thank you, you can also work on another issue if you see....you can follow a design that is in the readme.md file

**Comment by Satyam0204** [comment]
Thankyou, I shall see the backend process
