### ISSUE TITLE
Dark Theme Missing In Contact Us Page

### ISSUE THREAD

**Issue by tayyab-ilyas** [codervivek5/VigyBag#712]
The method to switch between light and dark theme is missing on the navbar of contact us page: 

<img width="1120" alt="Screenshot 2023-07-30 094418" src="https://github.com/codervivek5/VigyBag/assets/110786036/27e0725e-de15-4853-b706-b598606a0955">

**Comment by tayyab-ilyas** [comment]
hey @codervivek5 can you assign this to me under Gssoc'23? thanks!

**Comment by codervivek5** [comment]
can you able to work on this issue ?
https://github.com/codervivek5/VigyBag/issues/704

**Comment by tayyab-ilyas** [comment]
> can you able to work on this issue ? #704

can you tell me more about it? also is this one invalid?

**Comment by codervivek5** [comment]
> > can you able to work on this issue ? #704
> 
> can you tell me more about it? also is this one invalid?

no no no...this is valid but if you want to work on that ..then you can

**Comment by tayyab-ilyas** [comment]
> > > can you able to work on this issue ? #704
> > 
> > can you tell me more about it? also is this one invalid?
> 
> no no no...this is valid but if you want to work on that ..then you can 

okay I can work on that 👍, please remove the invalid label from this one :)
