### ISSUE TITLE
ReDesign The Navbar

### ISSUE THREAD

**Issue by parasss19** [codervivek5/VigyBag#713]
## Description
- Right now the navbar is not looking good
- I will add some glassmorphism effects with proper css

<img width="960" alt="Screenshot 2023-07-30 140126" src="https://github.com/codervivek5/VigyBag/assets/101205226/84778c37-f3c6-4d7b-8c29-e4e5468d68e2">

**Comment by codervivek5** [comment]
bro can you share any output so that i can review it

**Comment by parasss19** [comment]
> bro can you share any output so that i can review it

Oki wait
