### ISSUE TITLE
Add functionality to the see more option in the clothes section

### ISSUE THREAD

**Issue by rolikaagarwal** [codervivek5/VigyBag#73]
I want to add some functionality to that option such that it displays a variety of options when clicked. I am a GSSoC'23 contributor. Kindly assign me this issue.
![image](https://github.com/codervivek5/VigyBag/assets/81984963/04921e41-6144-4ebd-9d88-41acbf81b73c)

**Comment by syedawanya18** [comment]
I want to work on this issue as a contributor.
Pleasure Assign so that I can show my skills under GSSoC'23.
