### ISSUE TITLE
Gap between Social media icons

### ISSUE THREAD

**Issue by Priyaaa1** [codervivek5/VigyBag#733]
There must be some gap between the Social media Icons, so that it will be more readable. I would like to resolve this.

![Screenshot (177)](https://github.com/codervivek5/VigyBag/assets/105431748/e0dd2213-f735-4fec-a7bc-1ccb2aa27e93)

**Comment by Kota-Karthik** [comment]
Hi 
I am interested in doing this issue
so kindly assign me this
I will do my best to reach your expectations
Thank You  : )

**Comment by sakshinikharge39** [comment]
can you assign me this issue? 
i want to solve it

**Comment by codervivek5** [comment]
@sakshinikharge39 kindly feagure out website one time and afte that if you feel any issue then share the screen shot what  you want to fix

**Comment by Kota-Karthik** [comment]
can you assign me this issue?
I want to solve it

**Comment by codervivek5** [comment]
@Kota-Karthik if @sakshinikharge39  do not reply then you can start woking on it or ou can find any other issue then contribute on there
