### ISSUE TITLE
Dark theme issues

### ISSUE THREAD

**Issue by HimanshuNarware** [codervivek5/VigyBag#735]
Description
When we change the theme of the website from white to dark Service section loose its visibility

##Screenshot
![2](https://github.com/codervivek5/VigyBag/assets/83147410/3f79dc59-106c-4001-b6c1-3ecd6965b248)
![3](https://github.com/codervivek5/VigyBag/assets/83147410/3b399375-f9af-460d-ad61-21a78446701c)

**Comment by sakshinikharge39** [comment]
I want solve this issue
