### ISSUE TITLE
social icon and theme 

### ISSUE THREAD

**Issue by BhartiNagpure** [codervivek5/VigyBag#738]
On clicking social icon it open in same tab by replacing website.
I would like to add code to open the social media on next tab .

Also I would like to add theme button in contact page.

**Comment by Kajal2468** [comment]
please assign this I want to work on this issue!

Thank You!

**Comment by RajJ59** [comment]
I want to work on this issue

**Comment by codervivek5** [comment]
Kindly share issue with screenshot
