### ISSUE TITLE
[Docs] : Update Readme

### ISSUE THREAD

**Issue by Parul1606** [codervivek5/VigyBag#755]
I would like to add the missing 2 points in the Readme- contributing section.
Git remote add upstream, git remote -v, and for fetching git pull upstream main

Please assign me this issue I would like to work under gssoc.

for reference purpose:
![image](https://github.com/codervivek5/VigyBag/assets/80768852/df08b2e9-ed9d-44a6-ad3e-29991aaeec80)

**Comment by codervivek5** [comment]
also check these bug

![image](https://github.com/codervivek5/VigyBag/assets/62784060/1a0ff5cc-6c16-4f86-8dcd-7f88b7e55ac6)

![image](https://github.com/codervivek5/VigyBag/assets/62784060/df51a544-d8b4-4985-be7b-f637ccf56aaf)


as you share with me there is no any issue like that ....but if you can fix these issues which I share with you then go through it

**Comment by Parul1606** [comment]
Okay, I will try to solve this too as soon as possible. Thank you for assigning!

**Comment by SyedImtiyaz-1** [comment]
```

```

**Comment by Parul1606** [comment]
> Hello @Parul1606 , cc: @codervivek5 , Also update the copyright section - ![image](https://user-images.githubusercontent.com/121503426/258634099-b1d98c0c-d3f1-4555-ba06-b76c4a2968b4.png)
> 
> * & the project admins img is too big so can you please make it as a medium size also with the alignment in the center. I think it will look great.

@codervivek5 should I work on it?
