### ISSUE TITLE
Adding links to the social media Icons.

### ISSUE THREAD

**Issue by Srija-Burugula** [codervivek5/VigyBag#76]
The social media icons are not redirecting. Adding appropriate links would help the user. I would like to solve this issue under GSSoC'23. please assign this issue to me.

**Comment by syedawanya18** [comment]
I want to work on this issue as a contributor.
Pleasure Assign so that I can show my skills under GSSoC'23.

**Comment by Srija-Burugula** [comment]
thank you @codervivek5 for assigning this issue to me. I will start working on it. I request you please provide me with links for the social media pages.

**Comment by codervivek5** [comment]
> thank you @codervivek5 for assigning this issue to me. I will start working on it. I request you please provide me with links for the social media pages.

you can get  my social media link from readme file

**Comment by Srija-Burugula** [comment]
ok @codervivek5, thank you.

**Comment by Srija-Burugula** [comment]
@codervivek5 The link for Facebook page is not given in the readme file. I request you to please provide me with it.

**Comment by Chavisn** [comment]
I want to work on this issue as a contributor.
Pleasure Assign so that I can show my skills under GSSoC'23.
