### ISSUE TITLE
Want to add our Contributor page in the website

### ISSUE THREAD

**Issue by HimanshuNarware** [codervivek5/VigyBag#771]
Details
Is your feature request related to a problem? Please describe.
Our Contributors page in the website
Describe the solution you'd like
We can add a Contributors page in the website. which is shows the name and the profile image of the contributor.and the number of commits is done by the contributor

**Comment by Kota-Karthik** [comment]
Hi 
I am interested in doing this issue
so kindly assign me this
I will do my best to reach your expectations
Thank You  : )

**Comment by codervivek5** [comment]
This is already added
