### ISSUE TITLE
Pop Up Model design

### ISSUE THREAD

**Issue by parasss19** [codervivek5/VigyBag#772]
## Description
- Right now the pop model is not looking good with with website UI
- Also the some of the bottom content is over flowing from the pop up screen 
- Also the discounted price is incorrect

<img width="533" alt="popup" src="https://github.com/codervivek5/VigyBag/assets/101205226/4042c389-e823-42c6-8445-38ca2ef80875">

## Change 
- I will design the whole new pop up model

**Comment by parasss19** [comment]
Hey @codervivek5 Please review it

**Comment by Muhammad0320** [comment]
Seen, please can you assign me for this task
