### ISSUE TITLE
as the headphones, tshirts and mobile all are showing same content make it different

### ISSUE THREAD

**Issue by priyanshibhatn** [codervivek5/VigyBag#773]
those headphones tshirts and mobile make more variety of them

**Comment by Kota-Karthik** [comment]
Hi 
I am interested in doing this issue
so kindly assign me this
I will do my best to reach your expectations
Thank You  : )

**Comment by sakshinikharge39** [comment]
can you assign me this issue?

**Comment by codervivek5** [comment]
Continue contribution and if  you feel and issue then feel free to ask
