### ISSUE TITLE
Adding hover effect on Download VigyBag Today! 

### ISSUE THREAD

**Issue by GameOver2811** [codervivek5/VigyBag#78]
Kindly assign this task to me so that UX can be increased

https://github.com/codervivek5/VigyBag/assets/118586647/767ec45c-6691-4e0c-b696-bdd2957c2273

**Comment by codervivek5** [comment]
Remove this effect and add underlined animation effect as a hover.

**Comment by Cheemma1** [comment]
Hi @codervivek5   can you assign me to the issue?

**Comment by codervivek5** [comment]
@GameOver2811 any update?
