### ISSUE TITLE
Style: Search Bar Redesign

### ISSUE THREAD

**Issue by parasss19** [codervivek5/VigyBag#780]
## Description
- RIght now the navbar now suited with the UI of the webstie
- The margin padding is also not proper

## Change
- Redesign the navbar
- Also add the type writer words effect like myntra website search bar
-  I will properly add the margin padding

**Comment by Muhammad0320** [comment]
Okay, Please assign me for this issue

**Comment by BhartiNagpure** [comment]
I would like to work on this issue

**Comment by Kota-Karthik** [comment]
Hi 
I am interested in doing this issue
so kindly assign me this
I will do my best to reach your expectations
Thank You  : )
