### ISSUE TITLE
Creating Contact Us page 

### ISSUE THREAD

**Issue by GameOver2811** [codervivek5/VigyBag#79]

**Comment by syedawanya18** [comment]
I want to work on this issue as a contributor.
Pleasure Assign so that I can show my skills under GSSoC'23.

**Comment by codervivek5** [comment]
Kindly follow the readme file. there is a figma design so you can refer that design.

**Comment by PayalPadmalyaPrusty** [comment]
@codervivek5 I want to contribute.Please assign me

**Comment by Chavisn** [comment]
@codervivek5 I want to work on this Project. Please assign this to me
