### ISSUE TITLE
[Request]: Noticed to Add alt-text of Image Elements, ARIA Attributes to Social Links and Multiple Form Sections

### ISSUE THREAD

**Issue by NarendraKoya999** [codervivek5/VigyBag#792]
### Issue Description
- Observed Missing alt attribute text in Lot of Image elements in Most of the Files.
- Also, missing ARIA attributes to Social Links and Form Sections.
- Additionally, I want to add Tooltip for Social Links.
- In Some HTML Files, this bug is there `<body bgcolor="#575A89">. This is not correct. Actual correct property name is background-color`
### Why I am Proposed these Things
- ARIA attributes enable modifying an element's states and properties as defined in the accessibility tree. Note: ARIA only modifies the accessibility tree, modifying how assistive technology presents the content to your users. ARIA doesn't change anything about an element's function or behavior.
- The alt attribute specifies an alternate text for an area, if the image cannot be displayed. The alt attribute provides alternative information for an image if a user for some reason cannot view it (because of slow connection, an error in the src attribute, or if the user uses a screen reader).

**Comment by NarendraKoya999** [comment]
Hi @codervivek5 . I want to work on this Issue. Please Review on this Issue as soon as Possible.

**Comment by karantec** [comment]
Hi @codervivek5 . I want to work on this Issue. Please Review on this Issue as soon as Possible.
