### ISSUE TITLE
[Request]: Poor Enhancement of Footer Section like Payments Icons & Copyright Section🌟🌟

### ISSUE THREAD

**Issue by NarendraKoya999** [codervivek5/VigyBag#793]
### Issue Description
- Go to https://codervivek5.github.io/VigyBag/
- **Scroll Down to Bottom Footer Section.**
- **Do Hovering Action on Respective Payments Icons. There is no Hovering Effect and Cursor Point.**
- **Even Copyright Text is not Good Attracting as per Enhancement Point of View. I want to Improve Font Size and Weights.**

**Comment by NarendraKoya999** [comment]
Hi @codervivek5 . Please Review on this Issue as soon as Possible. If Selectable, Please assigned Me. Thank You !

**Comment by Muhammad0320** [comment]
hi @codervivek5 . Please assign me for this task
