### ISSUE TITLE
Spacing around search button

### ISSUE THREAD

**Issue by rahulrana701** [codervivek5/VigyBag#8]
<img width="931" alt="Screenshot 2023-04-19 125956" src="https://user-images.githubusercontent.com/123585591/233001427-34a57ef7-b211-4243-ad7b-4c3ce6b37569.png">
I think if we add some spacing above the search button it will look better.....

**Comment by rahulrana701** [comment]
@codervivek5 if you want, you can assign this issue to me, I can work on this...

**Comment by rahulrana701** [comment]
hi @codervivek5 I want to work on this issue...

**Comment by rahulrana701** [comment]
hi @codervivek5  are you maintaining this project..

**Comment by AmanMittal-3305** [comment]
Hi
I would like to work on this issue

**Comment by ruchagosavi** [comment]
@codervivek5  I would like to work on this issue

**Comment by ArunMaramraj** [comment]
Hello @codervivek5. Arun here and a contributor to GSSOC '23. I would like to work on this issue

**Comment by krittika2004** [comment]
@codervivek5  please assign this to me

**Comment by s0oraj** [comment]
Hi @codervivek5, iam a GSSOC23 contributer and I would like to resolve this issue

Can you assign me this issue? Or any other issues you might have?
Heres My Resume which you might find useful: [Resume](https://github.com/codervivek5/VigyBag/files/11521351/Resume.pdf)
Ive more than 1 year of experience in android development(check profile for more details)

**Comment by ArunMaramraj** [comment]
Thank you for assigning me @codervivek5... will come back to you in short!

**Comment by ArunMaramraj** [comment]
Hello @codervivek5 i have added margin space around search bar and created PR. Could you please check? Thanks!
