### ISSUE TITLE
[REQUEST]:Website not fully responsive  therefore request to work on the navbar and search bar.

### ISSUE THREAD

**Issue by anshika-kamboj** [codervivek5/VigyBag#800]
**GSSoC'23 Contributor**
**Issue Description**

-Go to https://codervivek5.github.io/VigyBag/ 

- Right click and inspect the website.
- On  adjusting the frame for different dimensions ,the navbar is unresponsive and the search-bar hides behind navbar.
Thus, I want to work on the Navbar and search-bar   to make it more responsive and make improvement on the above mentioned issues.

Kindly assign me the issue as soon as possible @codervivek5 .Thankyou!

**Comment by codervivek5** [comment]
now every thing is fine
