### ISSUE TITLE
[bug] - Home page

### ISSUE THREAD

**Issue by codervivek5** [codervivek5/VigyBag#805]
![image](https://github.com/codervivek5/VigyBag/assets/62784060/b22c4586-a2b3-4299-a8c3-5f7b965faf5d)

**Comment by Sch476** [comment]
I will fix this bug .

Please assign this issue to me.

**Comment by Muhammad0320** [comment]
Could you please assign me

**Comment by KamakshiOjha** [comment]
Hey, can you please assign me this task.

**Comment by codervivek5** [comment]
@KamakshiOjha kindly check the issue explain the issue which one you want to solve if possible then add a screen shot also for better understanding

**Comment by KamakshiOjha** [comment]
The website is not responsive so I'm gone add more responsiveness to this Website.
<img width="469" alt="Screenshot 2023-09-08 at 11 18 20 AM" src="https://github.com/codervivek5/VigyBag/assets/114620432/15a6e22e-f7a3-40d8-9dce-390f99658963">
