### ISSUE TITLE
[GSSoc '23] Adding a new page showing users' location using MapBox API

### ISSUE THREAD

**Issue by PrathmeshN99** [codervivek5/VigyBag#81]

**Comment by yellurividyendra** [comment]
Adding a new page  and showing users location using MapBox API is a good feature and good users experience.
as i am GSSOC'23 contributor
i would like to do this issue using kotlin
so kindly assign me this issue
@PrathmeshN99

**Comment by yellurividyendra** [comment]
Adding a new page and showing users location using MapBox API is a good feature and good users experience.
as i am GSSOC'23 contributor
i would like to do this issue using kotlin
so kindly assign me this issue
@PrathmeshN99

**Comment by yellurividyendra** [comment]
Adding a new page and showing users location using MapBox API is a good feature and good users experience.
as i am GSSOC'23 contributor
i would like to do this issue using kotlin
so kindly assign me this issue
@PrathmeshN99

**Comment by yellurividyendra** [comment]
Adding a new page and showing users location using MapBox API is a good feature and good users experience.
as i am GSSOC'23 contributor
i would like to do this issue using kotlin
so kindly assign me this issue
@PrathmeshN99 
sir please do reply to this comment :)

**Comment by codervivek5** [comment]
@yellurividyendra try to talk with @PrathmeshN99 if he agrees then I will assign it to you.

Actually, I can't break gssoc rule that's why firstly I have to assign it to @PrathmeshN99 

I am really sorry for it

**Comment by yellurividyendra** [comment]
ok sir thank you.
and @PrathmeshN99 if you agree i will assign this work, will you :)

**Comment by PrathmeshN99** [comment]
@codervivek5  can you assign this issue to me, as I'm a contributor in GSSoC

**Comment by JigarJoshi04** [comment]
Hey @codervivek5 ,
I think this issue was reported by @yellurividyendra and he expressed his interest to work on it before @PrathmeshN99 .
So I think @yellurividyendra  should be assigned this issue.
Is there any guideline of GSSOC that we would violate if we do this?

@PrathmeshN99, we're really sorry that we might be giving this issue to @yellurividyendra  (If there is no violation of any guidelines of GSSOC). Can you pick any other tasks? We will keep you informed.

Thanks @yellurividyendra @PrathmeshN99 for your interest in this issue.

**Comment by PrathmeshN99** [comment]
@JigarJoshi04 , I thought of the feature first, that is why created the issue in the first place. As I am not familiar with open source contribution procedure, I didn't know if I had to comment asking for the issue to be assigned. That is why I thought the issue would be assigned to me as I created it. Hence, @codervivek5 assigned the issue to me. Thank you.

**Comment by JigarJoshi04** [comment]
> @JigarJoshi04 , I thought of the feature first, that is why created the issue in the first place. As I am not familiar with open source contribution procedure, I didn't know if I had to comment asking for the issue to be assigned. That is why I thought the issue would be assigned to me as I created it. Hence, @codervivek5 assigned the issue to me. Thank you.

Okay, I understand.
Yes in that case we will assign the issue to you.
But for future, issue creation and issue assignment are two different parts.
Issue is kind of a feature request that comes from the user of a product
And issue is assigned to the contributor, maintainer of the product.
So in future for any project if you create issue and want to work on it, then add a comment to notify that you are interested that would be helpful for maintainers.
I hope that helps.
Thanks for being contributor to our project.

Sorry @yellurividyendra we will be assigning this to @PrathmeshN99 .
Feel free to pick any other issue.

Thank you @PrathmeshN99 @yellurividyendra

**Comment by codervivek5** [comment]
Hello @PrathmeshN99 @yellurividyendra 
There is a deadline for every issue (It is created by you or any other candidate). If you have not completed that task or inactive for a long time so the issue will be assigned to another candidate.

if you have any trouble or want more time to complete the task then you have to at least inform your mentors and also the project admin. if they agree then you can continue or they will definitely give you more time to complete your task.

I hope you can under.

**Comment by PrathmeshN99** [comment]
Hello @codervivek5 , I've already expressed the problem caused by the MapBox API on discord, which is why I wasn't able to close this issue. Rest assured once I get the key, I'll make the PR.
Thank you.
