### ISSUE TITLE
Dark Mode Not Working In Landing Page

### ISSUE THREAD

**Issue by parasss19** [codervivek5/VigyBag#810]
## Description 

- The dark mode is not working in landinf page

@codervivek5 Reivew it

**Comment by amartyaroy** [comment]
@parasss19 i didnt find this issue the dark mode is working fine only

**Comment by parasss19** [comment]
> @parasss19 i didnt find this issue the dark mode is working fine only

Because it's resolved pls check the PR before commenting anything
