### ISSUE TITLE
Team JS {DarkMode NULL}

### ISSUE THREAD

**Issue by SyedImtiyaz-1** [codervivek5/VigyBag#816]
Hello @codervivek5 ,
I found one more bug which is about the DarkMode.
### Video :
[Screencast from 10-08-23 02:07:43 PM IST.webm](https://github.com/codervivek5/VigyBag/assets/121503426/7cc4704e-bc9f-40cf-ba79-28e0be2e2490)

### Assign me this so I can add the feature again.

**Comment by kriznaw** [comment]
can i work on this bug ? please assign this issue to me
@codervivek5

**Comment by codervivek5** [comment]
> can i work on this bug ? please assign this issue to me @codervivek5

what changes you want to add ?

**Comment by kriznaw** [comment]
in the team section there is no change when the light theme or dark theme is toggled , so i can work on that
( i'm new to open source so i want to work on small issues first )
