### ISSUE TITLE
refactor code

### ISSUE THREAD

**Issue by RitiChandak** [codervivek5/VigyBag#818]
the code is repeated in the file it self too many times

![image](https://github.com/codervivek5/VigyBag/assets/96969496/a55e422b-a966-42d6-8a27-8d9f70b1bbd1)
![image](https://github.com/codervivek5/VigyBag/assets/96969496/bed06808-6479-4ece-ae85-9c5da048a89c)

**Comment by RitiChandak** [comment]
@codervivek5 please look into it

**Comment by Muhammad0320** [comment]
Could you please assign me for this task

**Comment by rohit-yadavv** [comment]
Please Assign me this task as i am working on it
