### ISSUE TITLE
change background colour and font colour for clear visibility of menu bar

### ISSUE THREAD

**Issue by POORVI2303** [codervivek5/VigyBag#823]
![Capture](https://github.com/codervivek5/VigyBag/assets/132765791/d37812a4-0434-4180-83ee-7459363de541)

**Comment by POORVI2303** [comment]
please assign me i want to work on this

**Comment by codervivek5** [comment]
kindly look the figma design ...I want to add changes look like that...you can get file from readme.md.....if you can make like that then plz drop a comment in discord with this issue

**Comment by Muhammad0320** [comment]
Excuse me, please can I contribute to this website?
I want to work on this or any other issue that's associated with front end

**Comment by debrajrout** [comment]
Is This issue still open? I wanna work on it.

**Comment by codervivek5** [comment]
Yes @debrajrout if you want to contribute on it then find the issue and  tell me I Will assign to you and you can work on it

**Comment by debrajrout** [comment]
Yaa I am working on it.

**Comment by debrajrout** [comment]
I have made a commit with some cool changes please review.

**Comment by codervivek5** [comment]
kindly make a pr so that i can check your changes
