### ISSUE TITLE
[GSSOC'23] Create a login page

### ISSUE THREAD

**Issue by flawed-hooman** [codervivek5/VigyBag#83]
I want to update the Login page under GSSOC'23. Can you please assign me this project?
![Screenshot from 2023-05-21 19-44-58](https://github.com/codervivek5/VigyBag/assets/117461708/f948a49a-fd47-4fe1-a7d5-23506a668203)

**Comment by syedawanya18** [comment]
I want to work on this issue as a contributor.
Pleasure Assign so that I can show my skills under GSSoC'23.

**Comment by codervivek5** [comment]
actually one is already working on it so kindly wait for the response. If they are not able to solve this issue then I will assign it to you.
