### ISSUE TITLE
Contact us page is not reponsive 

### ISSUE THREAD

**Issue by ratishjain12** [codervivek5/VigyBag#834]
@codervivek5 contact us page is not responsive and gets cluttered on resize 

Assign me this issue so I can resolve it

**Comment by Ganaik2004** [comment]
@codervivek5 I want to work on this project please assign it to me

**Comment by codervivek5** [comment]
Kindly share your changes before PR so that I can atleast view tham make PR for code review...

**Comment by ratishjain12** [comment]
Suree
