### ISSUE TITLE
Enhance : Item section [GSSOC'23]

### ISSUE THREAD

**Issue by Pragati-3003** [codervivek5/VigyBag#84]
I would like to change the item section of the website. 
![IMG_20230521_195543](https://github.com/codervivek5/VigyBag/assets/132778037/5f2541a3-88c5-47bc-b5fb-ac3b000fd17b)

*****EXPECTED CHANGE ******
I would like to enhance the visual appeal of the item section by incorporating distinct background colors for different item categories or by applying margin and padding adjustments. My objective is to modify the UI of the item section to create a more visually appealing and attractive design.
So, please assign this issue to me under GSSOC'23. 
Thanking you.

**Comment by codervivek5** [comment]
After assign it you kindly refer figma design which is added in the readme file after it you can enhance this section.
