### ISSUE TITLE
Non-responsive Navbar on Mobile and Tablet Devices

### ISSUE THREAD

**Issue by premsaivarmachekuri** [codervivek5/VigyBag#85]
Hi @codervivek5, I have identified an issue with the non-functional navbar on the website.

**Problem:**
* The navbar on the website is not responsive on mobile and tablet devices.
* Users are unable to access important sections of the website due to the non-responsive navbar.

Phone 
![image](https://github.com/codervivek5/VigyBag/assets/110842297/0cd4122b-443a-433e-9627-0318faae8e77)

Tablet 
![image](https://github.com/codervivek5/VigyBag/assets/110842297/2e6f29b2-1bdf-4333-baee-4c985ec8f194)

**Feature:**
* The navbar should be made fully responsive on mobile and tablet devices.
* Users should be able to easily navigate through the website using the navbar on these devices.

**Additional Information:**
* This issue is particularly crucial to address as it impacts the usability and accessibility of the website.
* The website is being developed as part of GSSOC23, and I am actively working on resolving this issue.
* I have prior experience in tackling similar challenges on different projects.

By addressing the non-responsive navbar, we can greatly enhance the user experience and ensure seamless navigation on mobile and tablet devices. Your attention and support in resolving this issue are greatly appreciated.

Best regards,
Premsai Varma

**Comment by codervivek5** [comment]
Make ir mobile responsive....make menu side menu

**Comment by codervivek5** [comment]
kindly mention the issue number at PR time. try to make I attractive with these theme color.
