### ISSUE TITLE
Reduced height of search option  

### ISSUE THREAD

**Issue by codervivek5** [codervivek5/VigyBag#851]
![Screenshot 2023-09-26 at 1 02 06 PM](https://github.com/codervivek5/VigyBag/assets/62784060/862dc34a-5843-45f1-8f96-ef0525d0313f)

**Comment by Nikhil743** [comment]
hello vivek 
please assign me to this project.

**Comment by Gauravtb2253** [comment]
Hello @codervivek5 , I hope you're doing well. I'm interested in contributing to this task. I am eager to help in any way I can and believe I can make valuable contributions to the project. I humbly request you to assign me with the task.
