### ISSUE TITLE
Reduced size of accesories sectiona and also fix UI

### ISSUE THREAD

**Issue by codervivek5** [codervivek5/VigyBag#852]
![Screenshot 2023-09-26 at 1 03 30 PM](https://github.com/codervivek5/VigyBag/assets/62784060/2badc06a-1841-4fe7-a8a3-0990d266a147)

- reduced the size of this section
- make it responsive
- Also add a title name - "Our Services"

**Comment by parasss19** [comment]
Hey @codervivek5 assigned this issue to me

**Comment by parasss19** [comment]
@codervivek5 PLease review it
