### ISSUE TITLE
Fix size and overflow

### ISSUE THREAD

**Issue by codervivek5** [codervivek5/VigyBag#853]
![Screenshot 2023-09-26 at 1 06 17 PM](https://github.com/codervivek5/VigyBag/assets/62784060/b80b688d-835f-4747-b009-7337af199cf2)

- Reduced size of each product 
- also fix overflow of product 
- try to add a Slider button for the overflow product

**Comment by Tanush-J** [comment]
I will give this a try

**Comment by Tanush-J** [comment]
@codervivek5 can you help me setup the development environment for this project

**Comment by codervivek5** [comment]
sure but clear one thing that you want to work in backend or frontend or android ?

**Comment by Tanush-J** [comment]
I will be working on the frontend, I will start with fixing overflow and adding a slider.

**Comment by codervivek5** [comment]
follow the readme flle structure 👍 
or you can watch my youtube video "my first contribution"
 i have covered all the required thing in the video

**Comment by Tanush-J** [comment]
Ok it worked with live server, So all the changes related to home page should be made in index.html right?

**Comment by codervivek5** [comment]
> Ok it worked with live server, So all the changes related to home page should be made in index.html right?

threre are multiple pages ..so  you can check accourding to your need
