### ISSUE TITLE
Fix this section size and responsiveness

### ISSUE THREAD

**Issue by codervivek5** [codervivek5/VigyBag#855]
![Screenshot 2023-09-26 at 1 10 10 PM](https://github.com/codervivek5/VigyBag/assets/62784060/e73eb919-42a6-466f-92aa-55afa9179326)

- reduces size and makes these all in one line.
- make it mobile responsive by 3x3 in two rows

**Comment by parasss19** [comment]
Hey @codervivek5 assigned this issue to me

**Comment by Nikhil743** [comment]
Hey @codervivek5 assigned this issue to me

**Comment by sujal1885** [comment]
Hello , @codervivek5 Please assign  this issue to me
