### ISSUE TITLE
Reduced size of footer & improve UI

### ISSUE THREAD

**Issue by codervivek5** [codervivek5/VigyBag#856]
![Screenshot 2023-09-26 at 1 13 07 PM](https://github.com/codervivek5/VigyBag/assets/62784060/d834aea6-18ea-43fd-bbf7-ab8acbda6342)

- Reduced the height of the footer section and made it responsive 
- Improve user experience

**Comment by parasss19** [comment]
Hey @codervivek5 pls assigned this issue to me

**Comment by Gauravtb2253** [comment]
Hello @codervivek5 , I hope you're doing well. I'm interested in contributing to this task. I am eager to help in any way I can and believe I can make valuable contributions to the project. I humbly request you to assign me with the task.

**Comment by parasss19** [comment]
> Hello @codervivek5 , I hope you're doing well. I'm interested in contributing to this task. I am eager to help in any way I can and believe I can make valuable contributions to the project. I humbly request you to assign me with the task.

This issue is already assigned and one issue is assigned to one person only pls find some other issue which is not assigned to anyone
