### ISSUE TITLE
Improve contact us UI

### ISSUE THREAD

**Issue by codervivek5** [codervivek5/VigyBag#859]
- fix color according to theme color
 - improve Contact Us form according to the theme color
 - fix the exact logo, you can get from figma file from README.md file 
 - over all improve user experience

**Comment by JoelJaison394** [comment]
hey! Can I work on this task

**Comment by JoelJaison394** [comment]
I have worked and finished these tasks
- [x] **Fix Color According to Theme:** Ensure all colors are in line with the specified theme color.
- [x] **Improve Contact Us Form:** Enhance the Contact Us form design and functionality according to the theme.
- [x] **Fix Exact Logo:** Use the logo from the Figma file specified in the README.md.
- [x] **Overall Improve User Experience:** Enhance the overall user experience of the Contact Us page.

This is the preview , Is any more modifications neeeded

![image](https://github.com/codervivek5/VigyBag/assets/105162603/307ddf38-7fa8-4727-b720-c323e37d5bab)

**Comment by PixProgrammer** [comment]
@JoelJaison394 Are you working on this issue

**Comment by codervivek5** [comment]
> @JoelJaison394 Are you working on this issue

yes
