### ISSUE TITLE
I Want to create a Login Page.Could you please assign me this issue

### ISSUE THREAD

**Issue by shreeja5060** [codervivek5/VigyBag#86]
User Authentication: A login page allows you to implement user authentication, ensuring that only authorized users can access the app's features and data. It helps protect user information and maintain data privacy.

Personalized Experience: By requiring users to log in, you can personalize their experience within the app. User-specific settings, preferences, and data can be stored securely, providing a customized experience tailored to each individual.

User Management: A login page facilitates user management by enabling features like user registration, password reset, and account recovery. It allows users to create and manage their accounts, update profile information, and control their app-related activities.

Access Control and Security: With a login page, you can implement access control mechanisms, such as user roles and permissions. Different users can be granted different levels of access to specific app functionalities or data based on their roles, enhancing security and preventing unauthorized access.

**Comment by syedawanya18** [comment]
I want to work on this issue as a contributor.
Pleasure Assign so that I can show my skills under GSSoC'23.

**Comment by codervivek5** [comment]
@shreeja5060 actually another contributor is working on front-end design. so as soon as possible they complete the front page then I will re-open this issue.
I am really sorry for this time.
