### ISSUE TITLE
Add header and footer in login page

### ISSUE THREAD

**Issue by codervivek5** [codervivek5/VigyBag#860]
![Screenshot 2023-09-26 at 1 26 28 PM](https://github.com/codervivek5/VigyBag/assets/62784060/498b31e3-fb8c-440d-bde9-9e12e88e1e32)

- improve the over all design of login page
- you can get the design from figma file.
- get design from README.md file
- https://www.figma.com/file/hXcM6chTK70O6rAqCTFxuc/Vigy?node-id=0%3A1&t=px6VNjlFCos5Ll9z-1

**Comment by reyrinbafs** [comment]
Hey vivek, I would like to work on this issue.

**Comment by ZainabR11** [comment]
I believe that adding a polished header and footer to the login page can significantly elevate its overall aesthetics and user-friendliness. I'm excited to take on this task, leveraging my design skills and attention to detail to create a seamless and visually appealing login experience for our users.

**Comment by Nikhil743** [comment]
Hello, Vivek 
please assigned me on this project.

**Comment by namithashaji** [comment]
Can I work on this issue

**Comment by Nikhil743** [comment]
Hello, Vivek
please assigned me on this project.

**Comment by Surajit0573** [comment]
Hi @codervivek5, I can improve the over all design of login page. Can you please assign me to this issue !!

**Comment by Gauravtb2253** [comment]
Hello @codervivek5 , I hope you're doing well. I'm interested in contributing to this task of adding header and footer to the login page. I am eager to help in any way I can and believe I can make valuable contributions to the project. I humbly request you to assign me with the task.
Thank you for considering my request. I look forward to your response.

**Comment by codervivek5** [comment]
any update @namithashaji

**Comment by namithashaji** [comment]
Almost done. Will be finished in these days.

**Comment by codervivek5** [comment]
OK..... I will check and if everything is okay then I will merge your PR :)
