### ISSUE TITLE
Non Responsive Footer

### ISSUE THREAD

**Issue by Haris-Mohanty** [codervivek5/VigyBag#872]
## Problem:
The footer of the website/application is currently not responsive, which means it doesn't adapt well to different screen sizes and devices. This can lead to usability issues and a poor user experience on smaller screens.

## Expected Behaviour:
The footer should be responsive and adjust its layout and content to fit various screen sizes, including mobile devices, tablets, and desktops.

## Steps to Reproduce:
-> Open the website/application in a web browser.
-> Resize the browser window to a smaller width or use a mobile device.
-> Observe that the footer does not adapt or becomes unusable on smaller screens.

##Screenshots:
![Screenshot 2023-10-01 190532](https://github.com/codervivek5/VigyBag/assets/108195360/39587d7a-3455-4c5b-9c88-4286b7441c81)

**Comment by Haris-Mohanty** [comment]
@codervivek5, could you please assign me this issue?

**Comment by Haris-Mohanty** [comment]
Hey @codervivek5 , pls assign me this issue.

**Comment by tayyab-ilyas** [comment]
Hi @Haris-Mohanty thanks for opening an issue! you can start working on it

**Comment by Haris-Mohanty** [comment]
@tayyab-ilyas, Thank You

**Comment by Haris-Mohanty** [comment]
@codervivek5  and @tayyab-ilyas, Please check my PR #882  and give feedback.

**Comment by Haris-Mohanty** [comment]
@codervivek5, Please add "hacktoberfest-accepted" label otherwise it will not count in Hacktoberfest.
