### ISSUE TITLE
Add environment variables in settings.py file in backend code

### ISSUE THREAD

**Issue by rajuljha** [codervivek5/VigyBag#878]
Currently, the secret_key used by django's settings.py file is hard-coded. This is a security hazard as described by this [stackoverflow thread](https://stackoverflow.com/questions/7382149/whats-the-purpose-of-django-setting-secret-key).

**Solution:** Add the secret_key as an evironment variable instead.

**Comment by tayyab-ilyas** [comment]
Hi @rajuljha ! thanks for opening the issue, you can start working on it!

**Comment by akadeepesh** [comment]
Assign this to me please, I can do this

**Comment by tayyab-ilyas** [comment]
this issue has already been assigned to someone else, you can wait for a while and see if they're able to finish this or look for some other issues :)

> Assign this to me please, I can do this
