### ISSUE TITLE
Reduced space betwen search and services

### ISSUE THREAD

**Issue by codervivek5** [codervivek5/VigyBag#884]
![Screenshot 2023-10-06 at 11 10 46 AM](https://github.com/codervivek5/VigyBag/assets/62784060/2525aa46-e46e-4419-9ace-6d926e0e21af)

**Comment by abhi5hek001** [comment]
Please assign issue #884, "Reduced Space Between Search and Services," to me. I am well-versed in HTML, CSS, and JavaScript and have a proven track record of resolving similar design and layout issues. With my attention to detail and prior experience, I am confident in delivering a timely and effective solution. Thank you for considering my request.

**Comment by parasss19** [comment]
Hey  @codervivek5 i submitted the PR please review it

**Comment by abhi5hek001** [comment]
Dear @codervivek5 ,

I kindly request your approval for Pull Request #889, titled "Reduced Space Between Search and Services." This change aims to enhance the user experience in 'VizyBag' by reducing excess spacing. The code is thoroughly tested, and your approval to merge it would greatly benefit the project. Your consideration is much appreciated.

Thank you.

Best regards,
Abhishek Sahay
