### ISSUE TITLE
Spelling mistake in cart

### ISSUE THREAD

**Issue by Gaurang-Agrawal1** [codervivek5/VigyBag#89]
There in a spelling mistake in Add to cart in Place of cart there is "card"
I want to work on this issue please assign it to me.

**Comment by Gaurang-Agrawal1** [comment]
please assign this issue to me

**Comment by s4shantanu** [comment]
Please Review my code.

**Comment by s4shantanu** [comment]
Thank you @codervivek5 for accepting my first PR <3 .
