### ISSUE TITLE
Improve the UI of the website

### ISSUE THREAD

**Issue by singodiyashubham87** [codervivek5/VigyBag#890]
I want to improve the UI of the website and make it more appealing.
The alignment is completely disturbed as well as some buttons are out of scope of the UI.
Currently it looks very odd: 

![image](https://github.com/codervivek5/VigyBag/assets/93720428/17304234-2fa0-42c7-95fe-cea5c3c2267d)

# Kindly assign me under Hacktoberfest'23

**Comment by Jagtap01sumit** [comment]
I want to work to improve UI of the website. And contribute in this project with my skills.
The content in footer section in About us is disturbed  i want to fix it please assign this to me i can fix it.
![Screenshot (634)](https://github.com/codervivek5/VigyBag/assets/109575992/6debafa5-94ad-4ed7-9349-b68c8c63088c)

**Comment by Arush005** [comment]
I want to contribute to this project with my best of skills.

**Comment by Logic133** [comment]
I want to contribute to  in  this project   plz assign it to me.

**Comment by codervivek5** [comment]
Some one is already working on this so you need to find another issue
