### ISSUE TITLE
Google play button not working

### ISSUE THREAD

**Issue by singodiyashubham87** [codervivek5/VigyBag#891]
When I clicked on the Google Play button nothing happened.

To fix: 
I will add an alert informing the user that this feature is not currently available, which will make the UX better.

![image](https://github.com/codervivek5/VigyBag/assets/93720428/9f201007-6793-45e3-87b3-9c66c1086947)

**Comment by sakshinikharge39** [comment]
please assign me this issue

**Comment by OmChillure** [comment]
@codervivek5 can you please assign this issue to me under GSSoC'24 !
