### ISSUE TITLE
Reduce product size and update product 4 to 5

### ISSUE THREAD

**Issue by codervivek5** [codervivek5/VigyBag#9]
In this issue, you will change the number of products from 4 to 5 and reduced the product size

**Comment by Gaurang-Agrawal1** [comment]
@codervivek5 I want to work on this issue please assign this issue to me

**Comment by s0oraj** [comment]
Hi @codervivek5, iam a GSSOC23 contributer and I would like to resolve this issue

Can you assign me this issue? Or any other issues you might have?
Heres My Resume which you might find useful: [Resume](https://github.com/codervivek5/VigyBag/files/11521351/Resume.pdf)
Ive more than 1 year of experience in android development(check profile for more details)

**Comment by shwetasharma10** [comment]
Can you assign this issue to me Please?
