### ISSUE TITLE
Fix About US Page!

### ISSUE THREAD

**Issue by mohitparmar1** [codervivek5/VigyBag#900]
About Us page heading and footer section are not aligned well or may be messed up by someone! 
![Screenshot (189)](https://github.com/codervivek5/VigyBag/assets/100152343/89c8dea4-50dd-4892-85a8-5993c54bf7f4)

/assign @codervivek5

**Comment by Jagtap01sumit** [comment]
Please assign me this issue. I want to solve it and contribute it.
