### ISSUE TITLE
Improve Web Accessibility for Improved User Inclusivity

### ISSUE THREAD

**Issue by usernayeem** [codervivek5/VigyBag#920]
**Objective:**
Improve web accessibility to ensure an inclusive user experience.

**Proposed Changes:**
- Accessible Frames: Implemented accessible names for frames to improve navigation for users relying on assistive technologies.

- Discernible Text for Buttons: Ensured that Buttons now have discernible text.

**Benefits:**
Boost user inclusivity, align with accessibility standards.

**Screenshot**
![Screenshot (11)](https://github.com/codervivek5/VigyBag/assets/93907431/f9379659-105e-4219-b557-07fee55115fe)

**Comment by Utkarsht2310** [comment]
@md5nayeem can u please explain this issue more ?

**Comment by codervivek5** [comment]
what you want to add or make changes..... kindly explain little bit more
