### ISSUE TITLE
Improving Features & maintain responsiveness

### ISSUE THREAD

**Issue by Durgesh4993** [codervivek5/VigyBag#924]
![image](https://github.com/codervivek5/VigyBag/assets/98798977/556097ee-ba97-43e2-82c5-b6f94c64cd81)

![image](https://github.com/codervivek5/VigyBag/assets/98798977/cf8de1dc-675f-4218-90be-009919ba3dbc)

![image](https://github.com/codervivek5/VigyBag/assets/98798977/25f016d0-3ec4-4fe8-a65b-cca7d4bbd57e)

**Comment by Durgesh4993** [comment]
As i'll sean there are some simple errors and website can't be reponsive can i work on that

**Comment by Durgesh4993** [comment]
@codervivek5

**Comment by codervivek5** [comment]
ok...let me show after make changes so that i can review and after that  I can merge your PR

**Comment by Albert-2** [comment]
hey @codervivek5
I'd really like to contribute to this project 
Can you please assign me this issue as I'm quite good at frontend
THANK YOU FOR CONSIDERING..... :)

**Comment by Durgesh4993** [comment]
@Albert-2 Sorry bro, I am already working on this issue could you please raise any other isuue.
And thank you for cooperating..

**Comment by Albert-2** [comment]
okayyy✌️

**Comment by codervivek5** [comment]
@Durgesh4993 any update ?

kindly let me know ASAP

**Comment by Durgesh4993** [comment]
https://github.com/codervivek5/VigyBag/assets/98798977/dd15de52-13bf-49d7-86c6-cf04e9f9db94

**Comment by Durgesh4993** [comment]
@codervivek5 Can i send PR or need any changes

**Comment by codervivek5** [comment]
bro it is not looking good make it attractive and try to minimize Footer height

**Comment by Durgesh4993** [comment]
ok

**Comment by Yuvika-14** [comment]
Pls assign this issue. I will make the website responsive.

**Comment by codervivek5** [comment]
This is already fixed kindly choose another
