### ISSUE TITLE
[Design] Revamp the Sign-in and Sign-up page of android app 

### ISSUE THREAD

**Issue by princeraj-pr** [codervivek5/VigyBag#929]
Android Sign-in and Sign-up page UI are not optimized and have a lot of issues like logo is hard to see in the dark background, button text is clipping, etc.

I can optimize the website Sign-in and Sign-up page for the Android app

Screenshots
![Screenshot_2023-12-19-22-43-28-24_235928f9e78ce07171a0ad6882fe1740](https://github.com/codervivek5/VigyBag/assets/40030547/5523e833-1ef5-4760-bc82-092e9a4ac36c)
![Screenshot_2023-12-19-22-43-31-01_235928f9e78ce07171a0ad6882fe1740](https://github.com/codervivek5/VigyBag/assets/40030547/5598e16a-fa91-4a64-a4fd-c8d306c0d07e)

**Comment by princeraj-pr** [comment]
Hello @codervivek5, Please review this issue and assign it to me.

**Comment by AshitaBidkar** [comment]
I want to work on this issue, kindly assign it to me.

**Comment by codervivek5** [comment]
@AshitaBidkar  if Prince will not work then I will assign it to you after his response

**Comment by AshitaBidkar** [comment]
@codervivek5 Ok Sir, Thankyou!

**Comment by princeraj-pr** [comment]
@AshitaBidkar I am currently working on this issue
