### ISSUE TITLE
[Issue] : Enhance Message Input Visibility

### ISSUE THREAD

**Issue by ramith-kulal** [codervivek5/VigyBag#937]
### Issue Description:
The text typed into the message input box in the "Contact Us" section is not visible, likely due to insufficient contrast with the background. This makes it challenging for users to see what they are typing.

I would like to request a change in the text color within the message input box to ensure better visibility. 

### Screenshot:
![Screenshot 2024-01-19 125402](https://github.com/codervivek5/VigyBag/assets/142984776/21f48226-5a4b-4ef6-999e-ff9e08c1dad6)

**Working under JWoC'24**

**Comment by codervivek5** [comment]
start contributing

**Comment by Tanishka023** [comment]
@codervivek5  Please assign this to me under GSSoC'24.

**Comment by codervivek5** [comment]
@Tanishka023  start working on it and also let me know when you done this

**Comment by Tanishka023** [comment]
> @Tanishka023  start working on it and also let me know when you done this

Sure @codervivek5

**Comment by Tanishka023** [comment]
> > @Tanishka023  start working on it and also let me know when you done this
> 
> Sure @codervivek5 

I'm done with the changes, will merge soon! @codervivek5

**Comment by codervivek5** [comment]
kindly mention the PR number next time when you raised the PR

**Comment by aashkaaaaaa** [comment]
Please assign this to me under GSSoC'24.

**Comment by codervivek5** [comment]
@aashkaaaaaa wait for some time @Tanishka023  is working in it so kindly find another issue then I will aasign it to you

**Comment by riddhi5474** [comment]
Please assign this issue to me under GSSoC'24

**Comment by codervivek5** [comment]
any update @Tanishka023

**Comment by Tanishka023** [comment]
> any update @Tanishka023 

image
Take a look, please. I think it looks good.
Can I make a new issue and merge?
@codervivek5

**Comment by Tanishka023** [comment]
> any update @Tanishka023 

Check the pr please @codervivek5
