### ISSUE TITLE
BUG : Misplaced Links on Contact Us Page.

### ISSUE THREAD

**Issue by ramith-kulal** [codervivek5/VigyBag#938]
### Issue Description
On the "Contact Us" page of the website, the links for Instagram and LinkedIn logos are misplaced. Clicking on the Instagram logo redirects to LinkedIn, and clicking on the LinkedIn logo redirects to Instagram.

### Steps to Reproduce
1. Visit the "Contact Us" page.
2. Observe the Instagram and LinkedIn logos.
3. Click on the Instagram logo and check the redirection.
4. Click on the LinkedIn logo and check the redirection.
### Expected Behavior
Clicking on the Instagram logo should redirect to the Instagram profile, and clicking on the LinkedIn logo should redirect to the LinkedIn profile.
### Screenshots
![Screenshot 2024-01-19 221743](https://github.com/codervivek5/VigyBag/assets/142984776/aebe1861-886a-45eb-a290-4bec6806fda2)

**Working under JWoC'24**

**Comment by Utkarsht2310** [comment]
@ramith-kulal @codervivek5 I want to work on this issue under JWOC'23

**Comment by Utkarsht2310** [comment]
@ramith-kulal @codervivek5 I want to work on this issue under JWOC'23

**Comment by Gokilp** [comment]
please assign me

**Comment by codervivek5** [comment]
recomment after mid night

**Comment by ramith-kulal** [comment]
> please assign me

Just wanted to let you know that issue has been already fixed.
