### ISSUE TITLE
fixing the footer

### ISSUE THREAD

**Issue by NaveenChandraAdhikari** [codervivek5/VigyBag#939]
![Screenshot from 2024-01-21 01-34-55](https://github.com/codervivek5/VigyBag/assets/44281971/34bf8990-ee44-4bb0-b923-477e3559fbd6)
ASSIGN ME UNDER JWOC

**Comment by vishal2005025** [comment]
please assign it to me under JWOC'2024.

**Comment by Gokilp** [comment]
please assgin me

**Comment by Yuvika-14** [comment]
Kindly assign me this issue. I will be obliged to fix this.

**Comment by codervivek5** [comment]
this is already fixed if you seen any other pages kindly let me know
