### ISSUE TITLE
fixing the text alignment of home  for better UI

### ISSUE THREAD

**Issue by NaveenChandraAdhikari** [codervivek5/VigyBag#940]
![Screenshot from 2024-01-21 01-35-35](https://github.com/codervivek5/VigyBag/assets/44281971/0dba18c0-5cb9-43c4-8e08-12bd9c23a4c5)

ASSIGN ME UNDER JWOC

**Comment by thesri** [comment]
@codervivek5  please assign this to me under jwoc 2024 , if the assigned mentee couldnt do it in assignted time

**Comment by NaveenChandraAdhikari** [comment]
@codervivek5 ill merge the pr by tomorrow with full reposiveness

**Comment by codervivek5** [comment]
Any update ??

**Comment by Prithwi32** [comment]
@codervivek5 Please could you assign me this issue under GSSoC'24

**Comment by Tanishka023** [comment]
@codervivek5 Please assign this to me under GSSoC'24

**Comment by codervivek5** [comment]
This is alredy fixed you can check another issue
