### ISSUE TITLE
Not responsive for mobile devices, I want to make it responsive 

### ISSUE THREAD

**Issue by Zenitssuu** [codervivek5/VigyBag#942]
Your website is not responsive, specially for mobile devices, elements were not aligned in proper position. I want to make it responsive, please assign it to me under JWOC'24

![IMG_20240125_113346](https://github.com/codervivek5/VigyBag/assets/154405878/80fbbfd5-5674-4c8c-b553-5c9dc0d6fdb4)

**Comment by kaif969** [comment]
please assign it to me under JWOC'2024.

**Comment by codervivek5** [comment]
@Zenitssuu any update ??

**Comment by jayraj175coder** [comment]
Hi @codervivek5, I just see your website is not properly on mobile devices. The responsive ability still is not there.
Could you assign this issue to me under gssoc24 after 7.00 pm today.
This is my first contribution.
Hope you assign this.🙏🏻
![Screenshot_2024-05-10-11-55-52-499_com android chrome](https://github.com/codervivek5/VigyBag/assets/135996214/6b2ca4d4-ed22-4771-87b1-704b269620f4)

**Comment by codervivek5** [comment]
@jayraj175coder kindly let me know before raised the PR so that conflict will not occurred and this will successfully meaged

**Comment by jayraj175coder** [comment]
Hi @codervivek5 I wanted to do pull Request now. 
I complete my work...

**Comment by codervivek5** [comment]
ok .. you can create PR and after review I will merge it but first share some screen shot so that if anything is need to change then you can make after that you can make PR

**Comment by codervivek5** [comment]
first share some screenshot

**Comment by jayraj175coder** [comment]
![Screenshot 2024-05-10 202837](https://github.com/codervivek5/VigyBag/assets/135996214/0f245dcd-4b6c-466a-9736-a691671080a7)
![Screenshot 2024-05-10 202857](https://github.com/codervivek5/VigyBag/assets/135996214/45118598-34de-4b13-8e0c-13a00baad4d0)
![Screenshot 2024-05-10 202917](https://github.com/codervivek5/VigyBag/assets/135996214/087d2701-f375-441c-8da1-f7ecee9efa61)
THis one is @codervivek5. I submit pr sorry yaar I cant see your message..   Just Beginner things..

**Comment by codervivek5** [comment]
![329624641-0f245dcd-4b6c-466a-9736-a691671080a7](https://github.com/codervivek5/VigyBag/assets/62784060/5a09e9f6-98dd-4e74-8e6c-24cc957cfdc8)
![329624665-45118598-34de-4b13-8e0c-13a00baad4d0](https://github.com/codervivek5/VigyBag/assets/62784060/97c55291-aebf-41e6-8aaa-5c5259df7894)
 make these changes

**Comment by codervivek5** [comment]
![329624677-087d2701-f375-441c-8da1-f7ecee9efa61](https://github.com/codervivek5/VigyBag/assets/62784060/ad436c0d-b6bd-4fea-8a49-583b4459bfbf)
convert these review as a carousel which will automatic slide .


for this you can use bootstrap classes
