### ISSUE TITLE
Link, Input field and footer issue 

### ISSUE THREAD

**Issue by SyedImtiyaz-1** [codervivek5/VigyBag#949]
Hello Vivek,
I have seen some issues on the contact page, As we talk earlier regarding contributions on linkedin I'm giving this opportunity to @pavithraswath 👍🏻 

Kindly assign this issue to her. 

### Screenshot - 
![image](https://github.com/codervivek5/VigyBag/assets/121503426/6efba344-5079-4528-99a4-e68c1995f38e)

Thank You.

**Comment by pavithraswath** [comment]
Please assign me this issue.

**Comment by codervivek5** [comment]
Thankyou for your contribution kindly check the required labels in your PR

**Comment by vishal2005025** [comment]
I would like to work on this issue .
Please assign it to me under JWOC'2024.
