### ISSUE TITLE
Fix Navbar

### ISSUE THREAD

**Issue by abhishekdumaniya** [codervivek5/VigyBag#962]
![fix navbar](https://github.com/codervivek5/VigyBag/assets/123349721/8a7bfdce-2ec6-48fd-b2a3-612aead27fd8)

I'd like to request the removal of excessive content from the navbar, specifically by reducing the descriptions provided for each item. This is causing clutter and usability issues.

**Comment by abhishekdumaniya** [comment]
I want to work on this issue @codervivek5  please assign me

**Comment by codervivek5** [comment]
sure yu can work....Kindly let me know what changes you want to make ?

**Comment by abhishekdumaniya** [comment]
![Navbar](https://github.com/codervivek5/VigyBag/assets/123349721/491dd731-b11e-4a6f-ae1a-0e56e3e61b35)

I have done a lot of work on Navbar

**Comment by codervivek5** [comment]
ok if have done this then make a PR and I will review it

**Comment by Gokilp** [comment]
please assign to me

**Comment by Yuvika-14** [comment]
Please assign me this issue. I am best at fixing navbars :) since jwoc.

**Comment by codervivek5** [comment]
This is already fixed so kindly find another
