### ISSUE TITLE
UI Bug in the home page !

### ISSUE THREAD

**Issue by SyedImtiyaz-1** [codervivek5/VigyBag#972]
Hello PA,
There is a bug in the home page.
It's a css issue causing due to display properties.

## Image
![image](https://github.com/codervivek5/VigyBag/assets/121503426/33c8eb79-3ca7-4c04-8b1e-b896a559f813)

Please assign me this issue.

**Comment by Gokilp** [comment]
please assign the issues

**Comment by codervivek5** [comment]
@Gokilp kindly recomment after midnight so that you can get your point if I assign you at this point then you will not get you point for gssoc 2024 contribution

**Comment by Gokilp** [comment]
okie please assign to me

**Comment by codervivek5** [comment]
@Gokilp kindly wait for 10 May if I assign it to you at this time then you will not get your points so wait till then

**Comment by Gokilp** [comment]
okie i started tommorw please assign to me

**Comment by Anshydv18** [comment]
please assign me to do it , i will start from today

**Comment by codervivek5** [comment]
@Gokilp  can you solve this issue if yes then kindly let me know so that I can assign it to you

**Comment by Gokilp** [comment]
Yes

**Comment by codervivek5** [comment]
> Yes

ok continue then let me know an update in Discord or Linked when you make any changes
