### ISSUE TITLE
[New Page] Create User profile page

### ISSUE THREAD

**Issue by codervivek5** [codervivek5/VigyBag#98]
you can refer to this design for development purpose.
https://www.figma.com/file/hXcM6chTK70O6rAqCTFxuc/VigyBag?type=design&node-id=0%3A1&t=XsHlxKAHMDFgsOwr-1

**Comment by bishalde** [comment]
I would like to Contribute to the Create User Profile page...! and it will be easy for me to follow your FIGMA desing.

so kindly assign me this under #GSSOC'2023.
![image](https://github.com/codervivek5/VigyBag/assets/67416966/67ae5993-7a0a-4d7b-9105-8c940395647f)

**Comment by Chavisn** [comment]
I would like to work on this issue. Please assign this to me

**Comment by Tushar98644** [comment]
Hey @codervivek5 , may i take up the issue if it hasn't been assigned yet?

**Comment by spaul-12** [comment]
hey @codervivek5 , Please assign me this issue to work on.

**Comment by ManasaKaza** [comment]
I would like to work on this issue under GSSoC

**Comment by codervivek5** [comment]
@bishalde any update ?

**Comment by sampadatiwari30** [comment]
I want to add a welcome page very attractive and professionally please assign me this issue @codervivek5

**Comment by Chavisn** [comment]
@codervivek5   I have mailed you regarding issue #98 . Kindly check it.
