### ISSUE TITLE
What our costumer say page

### ISSUE THREAD

**Issue by Swapnita06** [codervivek5/VigyBag#980]
I can improve what our costumer say page in a better and proffesional way. Please assign this to me

**Comment by codervivek5** [comment]
kindly share the screenshot and explain what you want to change so that i can understand

**Comment by Swapnita06** [comment]
![review](https://github.com/codervivek5/VigyBag/assets/127416976/1cf9ebbe-e1d1-4088-a3d3-d71dd54add27)
something like this

**Comment by codervivek5** [comment]
start working

**Comment by Swapnita06** [comment]
Sure sir.. Thank you!
