### ISSUE TITLE
Responsiveness 

### ISSUE THREAD

**Issue by Bhoovi333** [codervivek5/VigyBag#984]
Hey,
I just saw the app in my phone, though it has creativity and  well designed,

•But I felt it is not responsive in mobile and small screens,if you say I could do that. 

•Also,I think I can made it dynamic,I can add animations to make it more attractive.

**Comment by codervivek5** [comment]
IF you want to work on mobile app then continue .... for web someone is already working

**Comment by somrima-09** [comment]
Hi. Under GSSOC'24, I would like to work on this issue.
Please Assign me this task.

**Comment by codervivek5** [comment]
@Bhoovi333 any update if you can't then tell me atleat so that I can reassign it to another  candidate

**Comment by Bhoovi333** [comment]
Oh.. I'm interested in web only..yu can assign to others.
