### ISSUE TITLE
Adding contact number of the shop owners . 

### ISSUE THREAD

**Issue by Shreya-060304** [codervivek5/VigyBag#986]
In case of any emergency or to check the availability of any item , add a contact number button

**Comment by Jaivignesh-afk** [comment]
Can i work on this issue?

**Comment by aloku901** [comment]
Please assign this issue me for Adding contact number

**Comment by codervivek5** [comment]
share a over view so that I can understand what you guys are want to change

**Comment by Jaivignesh-afk** [comment]
I think by adding a button to each component in see_more.html would be a start.

**Comment by DevjitSikdar** [comment]
I am a GSSOC contributor, Di can i work on this plzz?

**Comment by codervivek5** [comment]
where you want to add the number just tell me in-depth and also share any screenshot where you want to make changes

**Comment by Jaivignesh-afk** [comment]
adding an emergency contact number here
![Screenshot 2024-05-12 122102](https://github.com/codervivek5/VigyBag/assets/108923524/5efce56a-94e5-4e5d-865f-83bfa5386668)
or 
![Screenshot 2024-05-12 122110](https://github.com/codervivek5/VigyBag/assets/108923524/64a48ca9-53ee-429d-8d42-8d7eed6d6947)
would be good i think
the code change should be done here in see_more.html

![Screenshot 2024-05-12 121949](https://github.com/codervivek5/VigyBag/assets/108923524/cafca914-01bd-40ab-9f60-971d90be9d2f)

**Comment by codervivek5** [comment]
no need to add here we will add a contact number in contact us page like a costumer care number
