### ISSUE TITLE
While cloning Got an error : SECRET_KEY NOT FOUND

### ISSUE THREAD

**Issue by Shadowsweep** [codervivek5/VigyBag#988]
![image](https://github.com/codervivek5/VigyBag/assets/122604770/06ea96aa-555c-4bfa-a6df-2b34d40e3fd9)
while cloning the repo i installed the required libraries and faced this error  for Django Contribution

**Comment by Jaivignesh-afk** [comment]
You need to basically give a value to the `SECRET_KEY`. You can do so by giving it a random hash code(length 50) and set it as a environment variable in your system. Here is the cmd line shortcut to do so
`setx SECRET_KEY ="your_secret_key"`

**Comment by Jaivignesh-afk** [comment]
Give a default secret key as a second argument
`SECRET_KEY = config("SECRET_KEY", "your_default_key")` in settings.py

**Comment by Shadowsweep** [comment]
ok thanks

**Comment by Shadowsweep** [comment]
after changing showing this error  .  i have use the SECRET KEY in settings.py , now showing this error :
![image](https://github.com/codervivek5/VigyBag/assets/122604770/fa45aa7a-8724-4c66-80cb-a16f9b1c68a4)

**Comment by Jaivignesh-afk** [comment]
Can you show me the code?

**Comment by Shadowsweep** [comment]
![Screenshot: 2024-05-11 104716](https://github.com/codervivek5/VigyBag/assets/122604770/4a28ab1a-c6b5-4ce5-82ca-efa0e1854ce1)
Sure, here are the changes that i made

**Comment by Jaivignesh-afk** [comment]
Maybe try setting an environment variable named SECRET_KEY

**Comment by codervivek5** [comment]
> ![Screenshot: 2024-05-11 104716](https://private-user-images.githubusercontent.com/122604770/329755853-4a28ab1a-c6b5-4ce5-82ca-efa0e1854ce1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MDYwNjksIm5iZiI6MTcxNTQwNTc2OSwicGF0aCI6Ii8xMjI2MDQ3NzAvMzI5NzU1ODUzLTRhMjhhYjFhLWM2YjUtNGNlNS04MmNhLWVmYTBlMTg1NGNlMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMVQwNTM2MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NjUxMDRjZjBiYTU3OTBiODFhMGRlZTVlY2IyNjY2ZTllYzc5OTE0Yjg1Y2ZmZDUwNzBkODQzNmI0MzFkNzIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.W_OlqslKpUMFgwHt_p99ZoROwoF9WTdsXySWw0s56Us) Sure, here are the changes that i made

is it working?

**Comment by Shadowsweep** [comment]
Not till yet

**Comment by Jaivignesh-afk** [comment]
Have you tried the environment variable?

**Comment by codervivek5** [comment]
I have fixed this issue you try again

**Comment by Shadowsweep** [comment]
ok sir  👍
