### ISSUE TITLE
Improve testimonals styling.

### ISSUE THREAD

**Issue by jayraj175coder** [codervivek5/VigyBag#989]
I want to make it very attractive testimonal.
I basically fix the UI of this page align center add boxes and many more.
Could you assign this issue under gsoc24
![Screenshot 2024-05-10 202424](https://github.com/codervivek5/VigyBag/assets/135996214/7f2f0e2a-3d0e-4ada-b568-78f6b8a851d5)

**Comment by codervivek5** [comment]
what you want to make change  first explain bcz someone is already working on it

**Comment by jayraj175coder** [comment]
I basically align the center of all the part.
Change the font color,style,etc.
U also made suitable border ,boxes on it.
This is simple format I choose:-
@codervivek5 
![IMG_20240510_205925](https://github.com/codervivek5/VigyBag/assets/135996214/0acf3607-01e6-47ad-a3d1-765af7c0f63d)

**Comment by codervivek5** [comment]
![image](https://github.com/codervivek5/VigyBag/assets/62784060/c168eaf6-1a03-4864-bbfe-bd594a765ffb)
can you make it same look like this

**Comment by jayraj175coder** [comment]
Yes, but I need 2 days for it.
I first complete mobile responsiveness bugs then I do this @codervivek5. Thanks.

**Comment by codervivek5** [comment]
ok you can take you time  and let me know after 10 am tomorrow ... you will done or not but let know so that I can't assign it to another

**Comment by codervivek5** [comment]
Its done
