### ISSUE TITLE
Create products View page 

### ISSUE THREAD

**Issue by codervivek5** [codervivek5/VigyBag#99]
you can refer this design.
https://www.figma.com/file/hXcM6chTK70O6rAqCTFxuc/VigyBag?type=design&node-id=0%3A1&t=XsHlxKAHMDFgsOwr-1

**Comment by Chavisn** [comment]
@codervivek5 I would to work on this issue. Please assign this to me.

**Comment by Chavisn** [comment]
Sir what is the deadline for this issue..?

**Comment by codervivek5** [comment]
You can submit till Wednesday so that I will give you review for basic changes if possible

**Comment by Chavisn** [comment]
Ok sir I will try my best.

**Comment by Chavisn** [comment]
Sir what are the Instagram and Twitter handles as I need to attach their
link's.

**Comment by Chavisn** [comment]
Can you please extend the deadline till tomorrow..?

**Comment by Chavisn** [comment]
@codervivek5  I have created the pull request .Please check it.

**Comment by codervivek5** [comment]
> @codervivek5 I have created the pull request .Please check it.

sure
