### ISSUE TITLE
Redesign or Recrease BACKEND Code 

### ISSUE THREAD

**Issue by codervivek5** [codervivek5/VigyBag#994]
The backend is not properly working I tried to solve it but it is showing error code 400 bad request.

if anyone can redesign it after checking all the features so let me know as soon as possible.

**Comment by Ankitapanda25** [comment]
@codervivek5 could you provide more details about the issue, maybe i can help?

**Comment by jeetbhuptani** [comment]
@codervivek5 Hello! I would love to know more about it and see the problem, well I even runned the backend part but with few of the import file issue I am not able to check the main problem
![Capture](https://github.com/codervivek5/VigyBag/assets/122789036/e559500f-9966-4e9d-9ef3-95a62551df88) settings.py
![Capture1](https://github.com/codervivek5/VigyBag/assets/122789036/4e95c8fc-307e-4e61-8e29-e61d6b2f9207) views.py
do I need to install any lib. or any other issue

**Comment by TomLucasakaTGeek** [comment]
I am an expert node.js backend engineer and I would be inspecting the backend requests and read docs for writing clear and concise code, please assign this issue to me @codervivek5 .

**Comment by externalPointerVariable** [comment]
I think the rest framework's requests are not routed properly
Approach: Diagnosing and debugging the code and if necessary making significant changes I will do that too. So, please assign this issue to me @codervivek5

**Comment by codervivek5** [comment]
let try to solve  and who is solve it first.... kindly let me know in this issue after that I will assign this issue to them and then they can create PR

**Comment by externalPointerVariable** [comment]
> let try to solve and who is solve it first.... kindly let me know in this issue after that I will assign this issue to them and then they can create PR

Hi, I started working on this issue and solved the bad request issue. Here is the image of the home page:

![Screenshot (19)](https://github.com/codervivek5/VigyBag/assets/75372728/6de61c04-6f33-49af-ac9b-67728d4faad7)

I wanted to confirm whether this is the correct one or not and also I need to discuss some things about this issue so It would be convenient if you would contact me as soon as possible.
And one more thing the issue should be marked as Level1/2/3, could you please rectify that error

**Comment by codervivek5** [comment]
any update ?

**Comment by externalPointerVariable** [comment]
Yes I need mentor's help with this I tried to connect with them but I got this instead 
![Screenshot_2024-05-14-23-40-28-34_e307a3f9df9f380ebaf106e1dc980bb6.jpg](https://github.com/codervivek5/VigyBag/assets/75372728/9ff913e2-306a-44ee-80ee-77a59f79d15f)

If you are open to discussion tell me

**Comment by codervivek5** [comment]
just give me some time till the morning I will try to connect her so that she can help you and I will also try to resolve this issue

**Comment by codervivek5** [comment]
@thakurboy004 Bro just Create a PR then I will give them review role then you can interact with mentors

**Comment by externalPointerVariable** [comment]
Okay I will do it today

**Comment by codervivek5** [comment]
sure
