### ISSUE TITLE
Redesign cards of the testimonials component

### ISSUE THREAD

**Issue by Ankitapanda25** [codervivek5/VigyBag#996]
The cards on the testimonials could be designed better than the current. I can improve it

<img width="281" alt="image" src="https://github.com/codervivek5/VigyBag/assets/123666302/1cd8b6d5-4501-4429-8486-9a6443415e35">

This is how it actually looks currently.

Please assign this to me under GSSOC'24 medium

**Comment by Jidnyasa21** [comment]
Helloo
The UI of the testimonial card doesn't look good. Please assign me this project so that I can design it better using figma by using proper color pallete and font size. 
-Jidnyasa|Contributor GSSOC'24

**Comment by codervivek5** [comment]
kindly share some sample so that i can better understand what exactly you want

**Comment by varshithar12** [comment]
I would like to work on this issue.
Please Assign me this task.
